### ISSUE TITLE
password change form checkbox bug

### ISSUE THREAD

**Issue by inuryyev** [userfrosting/UserFrosting#1008]
clicked checkbox is not checked.

![Annotation 2019-07-03 141959](https://user-images.githubusercontent.com/32765448/60588183-ec845580-9d9e-11e9-8a0e-24e37f20216f.png)

file path > `app/sprinkles/admin/assets/userfrosting/js/widgets/users.js`
line no > ` 229`

`e.preventDefault()` preventing it.

  ```
  // On submission, submit either the PUT request, or POST for a password reset, depending on the toggle state
            modal.find("input[name='change_password_mode']").click(function(e) {
                e.preventDefault();

                var changePasswordMode = $(this).val();
                toggleChangePasswordMode(modal, userName, changePasswordMode);
            });
```

**Comment by lcharette** [comment]
I've experience this before. If anyone wants to get a PR in, that would be great.
