### ISSUE TITLE
on role page users table action buttons bug

### ISSUE THREAD

**Issue by inuryyev** [userfrosting/UserFrosting#1010]
on role page users table action buttons not working

![Annotation 2019-07-04 123323](https://user-images.githubusercontent.com/32765448/60656685-8e1bad80-9e58-11e9-98c4-70f63914a394.png)

the reason is buttons are not binded.

**Comment by lcharette** [comment]
Can you elaborate, I'm not sure what's the issue here? Actions works on my test system?

**Comment by inuryyev** [comment]
they do nothing when you click.

**Comment by amosfolz** [comment]
These are not working on my test site either. This is only on the `roles` page.

**Comment by lcharette** [comment]
Replicated to now. Was looking at wrong page.
