### ISSUE TITLE
Package guzzle/guzzle is abandoned, you should avoid using it. Use guzzlehttp/guzzle instead.

### ISSUE THREAD

**Issue by amosfolz** [userfrosting/UserFrosting#1016]
Not sure if this is already documented somewhere else... Here is dependency tree for abandoned `guzzle/guzzle`.

```
userfrosting/userfrosting
└── thephpleague/flysystem-rackspace
          └── rackspace/php-opencloud (WILL NOT BE UPDATED)
                  └── guzzle/guzzle (abandoned)
```
[`rackspace/php-opencloud`](https://github.com/rackspace/php-opencloud) has already expressed they will not be updating to `guzzlehttp/guzzle` and suggest to use `php-opencloud/open-stack` instead. So it comes down to whether or not `thephpleague/flysystem-rackspace` will be updated to use this or not.

**Comment by lcharette** [comment]
I believe this is already fixed in `develop` with the great dependencies update. To confirm...

**Comment by amosfolz** [comment]
> 
> 
> I believe this is already fixed in `develop` with the great dependencies update. To confirm...

[See here.](https://github.com/userfrosting/UserFrosting/blob/develop/app/sprinkles/core/composer.json#L39)

**Comment by lcharette** [comment]
Oh you're right, the warning is still there... :/

**Comment by lcharette** [comment]
Question now is why do we require `league/flysystem-rackspace` ... Apparently it's for the Filesystem service. Laravel doc still says to use that dependency... https://laravel.com/docs/5.8/filesystem#driver-prerequisites

**Comment by lcharette** [comment]
Since rackspace  might not be a popular choice, one thing we could do is remove that dependency and change the doc so anyone requiring rackspace storage have to add this dependency to their sprinkle. 

Could probably do the same with S3...? 

https://github.com/userfrosting/UserFrosting/blob/2c50344af0dfc17b39a26da21b4efc17c1b5b0e0/app/sprinkles/core/config/default.php#L160
