### ISSUE TITLE
Chained method formatting preference for style guide

### ISSUE THREAD

**Issue by Silic0nS0ldier** [userfrosting/UserFrosting#1020]
Currently formatting of chained methods is inconsistent throughout the repo (and most likely all UF projects). We should decide on a preference (all on one line, and the various ways to format on multiple lines). Would help readability of source quite a bit.

# Ideas
## 1
One line
```php
$t->foo()->bar();
```
## 2
Multi-line, standard indentation
```php
$t->foo()
    ->bar();
```
## 3
Multi-line, aligned arrows
```php
$t->foo()
  ->bar();
```
## 4
Multi-line, everything on separate line with standard indentation
```php
$t
    ->foo()
    ->bar();
```

**Comment by lcharette** [comment]
I don't think N° 2 will pass StyleCI validation. N°4 is horrible.

It's either N°1 or N°3. My usual rule is if you have two or less `->`, it goes on the same line, unless it produce a more than 80 characters long line... 

But I can't say I'm consistent on the way I do it. Best would be to add a StyleCI rule, if there's one.
