### ISSUE TITLE
Error "Database hosts array is empty."

### ISSUE THREAD

**Issue by amosfolz** [userfrosting/UserFrosting#1022]
Here's what I had to do to reproduce:

1. Fresh clone of UF and ran `composer install`.
2. The `.env` file does NOT exist. (or `DB_HOST` does not exist inside the file)
3. When trying to run `php bakery bake` I get the following error: `"Database hosts array is empty."`
4. If I modify [this line](https://github.com/userfrosting/UserFrosting/blob/master/app/sprinkles/core/config/default.php#L128) and change to something like 

```
                'host'      => getenv('DB_HOST') ?: 'localhost',
```
then I can complete setup. 

![image](https://user-images.githubusercontent.com/33728190/62810120-f9e1dd80-baca-11e9-9747-9cde70bc542a.png)

So, it appears that the [`ConnectionFactory.php`](https://github.com/illuminate/database/blob/master/Connectors/ConnectionFactory.php#L192-L207) does not like null value?

**Comment by lcharette** [comment]
Remplicated.

> 4\. If I modify [this line](https://github.com/userfrosting/UserFrosting/blob/master/app/sprinkles/core/config/default.php#L128) and change to something like

It does work, but create a new warning :
<img width="860" alt="Capture d’écran, le 2019-08-09 à 20 00 56 1" src="https://user-images.githubusercontent.com/2566513/62814743-7e8b2680-bae0-11e9-887f-d99cb80dcd33.png">

**Comment by lcharette** [comment]
Checkout 52e7673 and let me know if it solves it
