### ISSUE TITLE
Migration dependencies should work with and without leading `\`

### ISSUE THREAD

**Issue by unguul** [userfrosting/UserFrosting#1023]
I'm creating this issue following https://github.com/userfrosting/learn/pull/89.

Currently, at least as of v4.2.3, database migration dependencies have to be provided with a leading slash. This is a detail that can easily be overlooked so I created the PR mentioned above.

However, as @lcharette mentioned, we should be able to use both variants (with and without leading slash).

**Comment by lcharette** [comment]
Note the dependencies can be hardcoded with or without a leading slash, so the code compairing the dependencies should make sure to strip any forward slashes before.

**Comment by lcharette** [comment]
...and rollback also need to be adapted

**Comment by lcharette** [comment]
If anyone wants to take a look at this issue, see draft PR with a test for this issue : https://github.com/userfrosting/UserFrosting/pull/1024

There's an issue I can't solve right now, if you return the class with the stripped/added slash, the original version should be returned if possible to avoid BC and other issues.

**Comment by unguul** [comment]
@lcharette If the current expectation is to use slashes then could we not just modify the constructor of `MigrationDependencyAnalyser` to add the slash to any dependencies which don't start with one?

**Comment by unguul** [comment]
@lcharette That's what I was going to do anyway when I was looking into this before phpstorm started to disappoint me :smile:

**Comment by lcharette** [comment]
Tried that, but I was still getting unresolved dependency (which shouldn't be) somehow. 

```
    protected function validateClassDependencies(string $migrationName): bool
    {
        // Strip leading slashes
        $migrationName = '\\' . ltrim($migrationName, '\\');
```

**Comment by unguul** [comment]
@lcharette Weird. What about XDebug with a couple of breakpoints?
