### ISSUE TITLE
Locale translation files need translated

### ISSUE THREAD

**Issue by amosfolz** [userfrosting/UserFrosting#1027]
Missing translation keys were added in `4.3` but we still need translators to assist with translations. 

The keys that need translated have been commented out in each locale file. 

- [x] ar (Arabic)
- [x] de_DE (German)
- [x] el (Greek)
- [x] fa (Persian)
- [x] fr_FR (French)
- [ ] it_IT (Italian)
- [ ] pt_PT (Portuguese)
- [x] ru_RU (Russian) 
- [x] th_TH (Thai)
- [ ] tr (Turkish)
- [ ] zh_CN (Chinese)

**Comment by Le-Morri** [comment]
Hey, I'm happy to do the de_DE locale. Let me know if you're still interested in it

**Comment by amosfolz** [comment]
@Le-Morri They have not been updated, please do. They keys are commented out that need updated.

**Comment by Le-Morri** [comment]
@amosfolz thanks for the hint. to which branch should I open the PR? as for the arabic to hotfix?

**Comment by lcharette** [comment]
> which branch should I open the PR?

Hotfix

**Comment by uatthaphon** [comment]
Hi, I want to take th_TH (Thai) if nobody works on it (^v^).

**Comment by nikolaos-spyratos** [comment]
I can take on Greek.

**Comment by lcharette** [comment]
@nikolaos-spyratos [Might still need updating](https://github.com/userfrosting/UserFrosting/blob/hotfix/app/sprinkles/account/locale/el/messages.php#L65) :)

**Comment by arminkhoshbin** [comment]
@amosfolz #1045 for the missing Persian translations.

**Comment by alannaidon** [comment]
PT_BR isn't required at the moment? I could help with that.

**Comment by lcharette** [comment]
@alannaidon There's no `PT_BR` locale yet, but you're welcome to add it if you want :)

**Comment by nina-py** [comment]
@amosfolz, just a quick note to say that the ru_RU locale appears to be 100% complete and should be ticked off your list.

**Comment by amosfolz** [comment]
> 
> 
> @amosfolz, just a quick note to say that the ru_RU locale appears to be 100% complete and should be ticked off your list.

Thanks for confirmation

**Comment by josemachado94** [comment]
#1178  -  pt_PT review

**Comment by lcharette** [comment]
A new issue will be opened for UF5
