### ISSUE TITLE
NPM install failing

### ISSUE THREAD

**Issue by TheMainJoe** [userfrosting/UserFrosting#1046]
I recently did a fresh install of UF and I keep getting npm errors:

![image](https://user-images.githubusercontent.com/1809371/67145822-016cf200-f285-11e9-970a-0868edafde0b.png)

When I try to run the app I get the following:

![image](https://user-images.githubusercontent.com/1809371/67145830-18134900-f285-11e9-948f-3c5ca2608c40.png)

When looking at the folders, the vendor folder folder which should contain font-awesome and bootstrap does not exist. If I try to to add the assets separately I get the following:

![image](https://user-images.githubusercontent.com/1809371/67145856-6f191e00-f285-11e9-8993-246bb4f48d54.png)

**Comment by lcharette** [comment]
Do you have more info on your env? Can't replicate on my setup (Ubuntu).

**Comment by TheMainJoe** [comment]
env details are as follows:

DB_DRIVER=mysql
DB_HOST=localhost
DB_PORT=3306
DB_NAME=coda
DB_USER=test
DB_PASSWORD=test
SMTP_HOST=smtp.gmail.com
SMTP_USER=********@gmail.com
SMTP_PASSWORD=********

I'm running on a windows machine, if that makes a difference.

**Comment by lcharette** [comment]
Ping @Silic0nS0ldier. Could be a Windows issue...

**Comment by amosfolz** [comment]
Are you running on homestead/vagrant?

**Comment by Silic0nS0ldier** [comment]
No idea what would cause this, next step is probably to increase log verbosity (I cannot recall how). I won't have time to look into this on my end for quite some time.

**Comment by TheMainJoe** [comment]
> Are you running on homestead/vagrant?

I am running on laragon and uniserve, just normal folders on my machine.

**Comment by TheMainJoe** [comment]
I will try an installation on a VM I setup last night and see if I get the same issue, to narrow it down to a windows issue.

**Comment by amosfolz** [comment]
I believe I've seen similar issues in the past and it was related to symbolic links...

**Comment by denispiovarci** [comment]
hey, i got the exact issue. Did you find a solution to this?

**Comment by Silic0nS0ldier** [comment]
Is this still an issue with the latest version of UserFrosting? If so, what is the output of `php bakery build-assets`?

**Comment by Silic0nS0ldier** [comment]
Closing as no follow up.
