### ISSUE TITLE
Userfrosting.com down

### ISSUE THREAD

**Issue by SamIvory1** [userfrosting/UserFrosting#1053]
The userfrosting.com website is down, as well as the documentation and chat

**Comment by lcharette** [comment]
We're investigating a DNS issue with our provider, [as this seams to not affect everyone](https://www.whatsmydns.net/#A/userfrosting.com)

**Comment by alexweissman** [comment]
@SamIvory1 whereabouts in the world are you located and what ISP? Trying to isolate the area of effect.

**Comment by malle-pietje** [comment]
Here in the Netherlands userfrosting.com is also down.

**Comment by alexweissman** [comment]
@malle-pietje I'm monitoring https://www.whatsmydns.net/#A/userfrosting.com but it seems like the results are continuously changing...

**Comment by malle-pietje** [comment]
Hmm, this is using 1.1.1.1

**Comment by alexweissman** [comment]
Ticket opened with Cloudflare.

**Comment by capitalfuse** [comment]
From Japan, suddenly disconected(DNS 1.1.1.1). I tried to connect with Tor Browser, it will be OK.

**Comment by malle-pietje** [comment]
Here in the Netherlands using 1.1.1.1 connectivity is now restored. Will post updates here when needed.

**Comment by capitalfuse** [comment]
Confirmed the connection from Japan, thanks.
