### ISSUE TITLE
Accessing the current locale code from Twig

### ISSUE THREAD

**Issue by Poldovico** [userfrosting/UserFrosting#1056]
I can't seem to figure out how to get the current locale code (say "en_US" or "it_IT") from Twig in a simple way.
I may just be missing how to do it, but in case there currently isn't a self-contained way, I propose adding a dedicated key to each locale translation as a simple fix.

**Comment by Poldovico** [comment]
If we do go with adding a dedicated key, I can make the PR myself but I'm not sure to which file.

**Comment by lcharette** [comment]
That's actually a valid point. The default locale can be found in `site.locale.default`, but this can be overwritten by the user own locale...

Adding a key in the translation files is indeed a quick and easy fix. However, I'm working on improvement on the locale system for the next version, I'll add this to my list.

**Comment by Poldovico** [comment]
I actually assumed the value of site.locale.default would NOT be
overwritten by the user's selected locale. If it is, then that's what I
need, though I would argue the name to be confusing. That leaves us with
the opposite problem of how to get the default locale, though.
An example use case would be with a JS plugin such as Uppy, which has its
own localisation system that just needs you to tell it what locale to use.

Il mar 17 dic 2019, 14:17 Louis Charette <notifications@github.com> ha
scritto:

**Comment by lcharette** [comment]
Actually, what I meant was, **The current locale** can be overwritten by the user locale. So `site.locale.default` will always show the correct default locale, but this value might not be up to date with the user locale...

**Comment by lcharette** [comment]
Implemented in d3f3138 for UF 4.4. Will be available using the `currentLocale` global Twig variable: 

```
{{ currentLocale }}
```

Result :
```
en_US
```
