### ISSUE TITLE
Cannot run migration if it's a not supported grammar for transactions

### ISSUE THREAD

**Issue by ktecho** [userfrosting/UserFrosting#1059]
Some days ago I added a new migration but didn't run migrations until today while trying to rebuild the docker environment. I was getting this message:

`A facade root has not been set`

I've been able to get where the problem is, but not why. If you go to `Migrator::runMigration`, you can see that there is a check:

```
if ($this->getSchemaGrammar()->supportsSchemaTransactions()) {
    $this->getConnection()->transaction($callback);
} else {
    $callback();
}
```

So it seems that if the migration is written in a supported grammar like the next one, it will work going trough `if` :

```
public function up() {
    if (!$this->schema->hasTable('table_name')) {
        $this->schema->create('table_name', function (Blueprint $table) {
            $table->string('blabla', 255);
        });
    }
}
```

But if you put this kind of grammar, it will fail with the `A facade root has not been set` message, going trough the `else`:

```
public function up() {
    DB::table('table_name')
        ->where('slug', 'group-admin')
        ->update([
            'slug' => 'account-admin'
        ]);
}
```

So it seems that the `else` way is broken, right?

**Comment by lcharette** [comment]
UserFrosting doesn't support the Laravel `DB` Facade. Thats's why we uses the `schema` method, or uses the Model directly.

**Comment by ktecho** [comment]
@lcharette Ok, but it would be nice to print an error message like `We don't support using DB facade. Please use schema instead`. That way if someone comes from Laravel don't lose hours and hours like I did.

**Comment by lcharette** [comment]
I'm not sure that's something UF can catch. Do you have the full stack of the `A facade root has not been set` error?

**Comment by ktecho** [comment]
@lcharette Oh, I thought that it was the entire `else` that was unsupported, but I guess sometimes it does work so you cannot put the message there.

The `bakery migrate` don't output more than that line. Is there any way to enable debug or something?

**Comment by ktecho** [comment]
@lcharette Besides that, the link `advanced queries` [here](https://learn.userfrosting.com/database/overview) points to the DB Facade docs in Laravel. It would be nice that it points to the Eloquent part [here](https://laravel.com/docs/5.4/eloquent).

**Comment by lcharette** [comment]
Fair enough. Can you [submit a PR](https://github.com/userfrosting/learn/blob/hotfix/pages/12.database/01.overview/docs.md) to edit that page?

**Comment by ktecho** [comment]
Yes. Done here: https://github.com/userfrosting/learn/pull/95
