### ISSUE TITLE
Clear-cache not working as intended

### ISSUE THREAD

**Issue by ktecho** [userfrosting/UserFrosting#1066]
When I do a deploy to Production, there are so much things I need to remember to do:

- `bakery build-assets -c` <-- This is fine: we need to build the assets
- `bakery clear-cache` <-- What does this do?
- Using the `Clear cache` option in the admin  <-- This deletes cache so pages refresh with new changes
- `rm app/cache/routes.cache` <-- This is to avoid the `your route cache may be stalled` problem.

I think we should have 2 commands to make the entire deploy successful:

1- Build assets: `bakery build-assets -c`
2- Clean everything: `bakery clean-all`

What do you think?

**Comment by lcharette** [comment]
I think `clear-cache` already does that? It clears the cache service cache, Twig cache, and [router cache](https://github.com/userfrosting/UserFrosting/blob/d35dfa8efe60f06896703137ebd12d7daaea63ca/app/sprinkles/core/src/Bakery/ClearCacheCommand.php#L54-L59).

Note the Clear cache option in the admin should be the same as running `bakery clear-cache`.

**Comment by ktecho** [comment]
No, they're not doing that. If they should, then there is a bug.

**Comment by lcharette** [comment]
Could be. [This area is not covered by test](https://codecov.io/gh/userfrosting/userfrosting/src/develop/app/sprinkles/core/src/Bakery/ClearCacheCommand.php).

Can you provide/confirm : 
1) Does the env (production or default) have an impact;
2) Your Env details (can paste `bakery debug` info here) & steps to reproduce on Vanilla UF if possible;
3) When command is run, does `app/cache/routes.cache` gets deleted;
4) While using the `file` cache driver, running the command empties `app/cache/` subdirs.

**Comment by ktecho** [comment]
Will try to give some more light to this the next time it happens.

**Comment by ktecho** [comment]
Mmmmm... at least this message:

`Message: Route not found, looks like your route cache is stale.`

Is solved when you do:

`php bakery clear-cache`

Maybe I had some wrong permissions that got corrected afterwards. I think I'll close the issue and re-open if the problem happens again.

**Comment by ktecho** [comment]
`php bakery clear-cache` won't clear the same as the Clear cache option in the admin. Right now I needed to make it refresh. The problem was in a translation, if that says something to someone :)

**Comment by lcharette** [comment]
> The problem was in a translation

What do you mean by this?

**Comment by ktecho** [comment]
> > The problem was in a translation
> 
> What do you mean by this?

Oh sorry :)

I changed a translation in the `en_US.php` to a different value but after the deploy and after the `php bakery build-assets -c ; php bakery clear-cache`, the screen was showing [KEY_OF_TRANSLATION] instead of the translated text. So I went to the admin and clicked the link "Clear cache" and it was fixed.

**Comment by lcharette** [comment]
Do you know which translation was causing issue? one of the default one, or yours?

**Comment by ktecho** [comment]
It was mine, and it was already existing for a long time. I just changed the translation text.

**Comment by lcharette** [comment]
So it's not an issue with UF...?

**Comment by ktecho** [comment]
Yes, it is. clear-cache is not clearing everything.

**Comment by lcharette** [comment]
I don't understand... You'll need to post instructions on how to replicate this.
