### ISSUE TITLE
Add Bakery options for: smtp:<port>, secure:<true|false>, auth:<true|false>

### ISSUE THREAD

**Issue by waldenn** [userfrosting/UserFrosting#1067]
In order to make the email functionality work on my SMTP server (which forwards emails to a secure ISP relay), I had to make these changes in the userfrosting/app/sprinkles/core/config/default.php:

>   'port' => 25,
>   'auth' => false,
>   'secure' => 'false'

Please consider adding these options to the setup options (and documentation).
I had to create a PHPMailer application to debug my SMTP connection problem, hopefully other people can avoid that with these settings.

Thanks for a great user management framework!

**Comment by gyaaniguy** [comment]
I am going for a PR. How should this be ideally handled ?

**Comment by lcharette** [comment]
@gyaaniguy Thanks!

I see three things that needs to be done : 

1. Add new ENV variables to `.env.example`
1. Implement said variables to the config file
1. Add the new options to the [SetupSmtpCommand  Bakery command](https://github.com/userfrosting/UserFrosting/blob/master/app/sprinkles/core/src/Bakery/SetupSmtpCommand.php#L26).

**Comment by mikkoaf** [comment]
I was looking through up-for-grabs issues. 

I found out that the linked, closed PR https://github.com/userfrosting/UserFrosting/pull/1077 was merged to master in https://github.com/userfrosting/UserFrosting/commit/82a1706c902f37fb690ae7b2019bb5822f0106e2 and is included on the release https://github.com/userfrosting/UserFrosting/releases/tag/v4.5.0

Can this issue be closed or is there still work to be done?
