### ISSUE TITLE
[FEATURE REQUEST] Make Debug::debug second parameter accept all kind of variables

### ISSUE THREAD

**Issue by ktecho** [userfrosting/UserFrosting#1072]
Right now, at least on my setup, if you pass a variable that is not an array to the second parameter of a `Debug::debug` expression, the execution is halted with an error:

```
var1 = 'Hey there';
Debug::debug('Value of variable:', var1);
functionAA();
```

```
Argument 2 passed to Monolog\Logger::debug() must be of the type array, string given, called in /app/app/system/Facade.php on line 239
```

That will not print the debug and the functionAA is not executed either because the Debug failed.

Would it be difficult to accept all kind of variables and just dump them to the log? The current way I need to check every time if what I want to print is an array. I've ended putting [ ] around everything just to be sure.

Maybe we can do something like:

```
if (variable_passed is type array) {
     dump variable_passed;
} else {
    dump [variable_passed];
}
```

**Comment by ktecho** [comment]
Editing to reflect that you don't get error message in the log, but I'm getting it on the screen.

**Comment by lcharette** [comment]
Looks like a limitation on [Monolog side](https://github.com/Seldaek/monolog/blob/bec314a9c14ce8a40650cf13923f5941ef1bfe0a/src/Monolog/Logger.php#L487). We would need to encapsulate the debug method so we convert string to array manually. 

FYI, I usually do, with whatever kind of var I have : 
```
Debug::debug(print_r($foo, true));
```

**Comment by lcharette** [comment]
Debug facade is not available in UF5 anymore.
