### ISSUE TITLE
Update to the latest Laravel (8.x)

### ISSUE THREAD

**Issue by tm1000** [userfrosting/UserFrosting#1074]
I realize this was done in #907 however #907 updated Illuminate to 5.8.x (current at the time). Laravel recently released 7.x

Whats the time frame for this project on updating libraries like Laravel (Illuminate) to newer versions? 

Would we be able to look into going to Illuminate 7.x?
- https://laravel.com/docs/6.x/upgrade
- https://laravel.com/docs/7.x/upgrade

As for something like Slim (3 to 4) that might be a way more drastic upgrade than Illuminate 5.8 to 7 (See Slim 3 => 4: http://www.slimframework.com/docs/v4/start/upgrade.html)

**Comment by lcharette** [comment]
It's not high on our priority at the moment. Depends on the complexity of the upgrade, I would say maybe something for V5, unless someone wants to tackle this and submit a PR.

Side note, Laravel 6 is considered LTS (bug fix until September 3rd, 2021), while Laravel 7 is not (Bug fix until September 3rd, **2020**). So we're better off switching to Laravel 6 for the time being.

**Comment by elijahcruz12** [comment]
If I may see about helping with this up-for-grabs, I use Laravel on a daily basis and would love to help upgrade all the way to Laravel 8, as it wouldn't be that difficult for me.

**Comment by Silic0nS0ldier** [comment]
I recommend we split this task in 2 (or more). Laravel and Slim upgrades (to the best of my knowledge) can happen separately, batching them like this implies that is not the case.

**Comment by lcharette** [comment]
> I recommend we split this task in 2 (or more). Laravel and Slim upgrades (to the best of my knowledge) can happen separately, batching them like this implies that is not the case.

I removed `& Composer Packages (Slim 4.x)` from title, as Laravel will be handled in 4.6, but Slim is planned for UF5. I won't open an issue for Slim as it's implied in UF5 roadmap.
