### ISSUE TITLE
Update build/package.json to use new gulp task name

### ISSUE THREAD

**Issue by alexweissman** [userfrosting/UserFrosting#1078]
As brought up in chat by @faligor:

> Hi everyone! 
> I think I found a bug with latest release in terms of assets compiling - when I do 
> `php bakery bake ` 
> I receive following error regarding `gulp bundle` task:
> `Task never defined: bundle`
> I think it happens because task name was changed in file `build/gulpfile.esm.js` from *bundle* to *build* but it wasn't changed in file `build/package.json`:
> `"uf-bundle": "./node_modules/.bin/gulp bundle",`
> after changing it to *build*, command `bakery build-assets -f` goes smoothly without errors. Would be nice to fix it and I'm sorry if it was already mentioned somewhere.

**Comment by lcharette** [comment]
Ref. : https://github.com/userfrosting/UserFrosting/commit/cc5fd7b64cd2a3fd63b9b1ffdffde89ce532aea1#diff-0509e37bb2d073d996ceb93b5078f6e8L9-R9

**Comment by lcharette** [comment]
A Github action should probably be used to test this...
