### ISSUE TITLE
Log browserified vendor bundles, and their named exports

### ISSUE THREAD

**Issue by Silic0nS0ldier** [userfrosting/UserFrosting#1080]
We run browserify against packages installed with `npm` to permit consumption without requiring a common-js aware environment, however while this feature exists the impact it has practically invisible to developers. It would be nice if successfully browserified packages were logged during assets installation, including the name of the resulting bundles.

Dependency task: https://github.com/userfrosting/browserify-dependencies/issues/11

**Comment by lcharette** [comment]
Not relevant in UF5 anymore
