### ISSUE TITLE
Minification of unbundled CSS and JS

### ISSUE THREAD

**Issue by Silic0nS0ldier** [userfrosting/UserFrosting#1081]
Currently unbundled CSS and JS are not minified in production builds as additional work was required to ensure it doesn't break builds. As of 4.4, the build scripts are now clean enough that this is something I'm willing to drive forward.

The main blocker here is that some vendor packages include template files which contain invalid syntax (either because of compilation directives, or due to being the start/end of a wrapper). The solution here is to add `try..catch` logic for applicable assets, vinyl chunks will also need to be cloned to ensure source files are not impacted should rollback be required.

One other consideration here is that the minifier not result in code that behaves differently. Generally this means keeping optimisations to a minimum, or leaving it running at default settings. Something to look for regardless.

Thought should also be put into minifying a wider range of assets (e.g. images).

**Comment by lcharette** [comment]
Not relevant in UF5 anymore
