### ISSUE TITLE
Version not updated with 4.4.2

### ISSUE THREAD

**Issue by malle-pietje** [userfrosting/UserFrosting#1097]
Wanted to report a minor bug where the UF version isn't updated with the 4.4.2 release. From `app/defines.php`:
```php
define('UserFrosting\VERSION', '4.4.1');
```

**Comment by malle-pietje** [comment]
Don't think this requires a PR😉

**Comment by lcharette** [comment]
Fixed in f4c021a5819412d8c006bbbfc88e0f65c472db4e for 4.4.3 release

**Comment by malle-pietje** [comment]
Thanks!
