### ISSUE TITLE
Use Laravel's `env` helper instead of `getenv`

### ISSUE THREAD

**Issue by alexweissman** [userfrosting/UserFrosting#1098]
The solution here is to not use the native `getenv` at all, but rather Laravel's [`env` helper](https://laravel.com/docs/7.x/helpers#method-env) which takes a default value as its second parameter. So this can just be `env('CSRF_ENABLED', true)`. This also has the nice side effect of allowing falsy values like `false` in the environment variable.

_Originally posted by @alexweissman in https://github.com/userfrosting/UserFrosting/pull/976/review_comment/create_

**Comment by alexweissman** [comment]
Labeling this as a bug because `CSRF_ENABLED=false` does not work with our current implementation using `getenv`.

**Comment by lcharette** [comment]
Is it compatible with DotEnv ?

**Comment by lcharette** [comment]
Note for later : https://github.com/illuminate/support/blob/master/Env.php

**Comment by alexweissman** [comment]
Yes, in fact Laravel uses DotEnv as well.  `env` is just a wrapper around the `getenv` function which DotEnv overloads.

**Comment by lcharette** [comment]
And what's the issue with `CSRF_ENABLED` ? How can we reproduce ?

**Comment by alexweissman** [comment]
It's not really specific to `CSRF_ENABLED`, it's just that that variable happens to be one that takes a true/false value. You can try creating any new variable in `.env` and setting it to `false`. If you import it with `getenv`, you will get the string `"false"` (which evaluates to a boolean true) rather than an actual boolean value of `false`.
