### ISSUE TITLE
Multi-columns relationships

### ISSUE THREAD

**Issue by d3str0y3r** [userfrosting/UserFrosting#1099]
Is there currently a possibility to build relationships using multiple columns?
If not, it would be nice to implement [Compoships](https://github.com/topclaudy/compoships).

**Comment by lcharette** [comment]
UF support Eloquent natively, so everything Eloquent can do, UF can do. As for Compoships, I don't see the need to have it ship it with UF, but you can definitely implement it in your own sprinkle, using the the `Awobaz\Compoships\Compoships` trait.

**Comment by d3str0y3r** [comment]
I read about the trait, but how to use it together userfrosting's sync method?
E.g. userfrosting returns _HasManySyncable_, but Compoships _HasMany_ in the hasMany function.

**Comment by lcharette** [comment]
@alexweissman could help you more on `HasManySyncable`

**Comment by d3str0y3r** [comment]
@alexweissman: Would be nice if you can :)
