### ISSUE TITLE
Separate out custom Handlebars helpers

### ISSUE THREAD

**Issue by alexweissman** [userfrosting/UserFrosting#1125]
A lot of our custom Handlebars helpers would be useful to use outside of a Handlebars context. We should separate them out into some kind of helper class, and then register Handlebars on those helper methods.  So something like:

```
var ufHelpers = {
  phoneUSFormat: function (phoneNumber) {
    ...
  },
  ...
};

Handlebars.registerHelper("phoneUSFormat", ufHelpers.phoneUSFormat);
```

Not sure exactly what the syntax would be but you get the idea.

**Comment by lcharette** [comment]
Closing. Focusing on removing Handlebar for vue.js instead.
