### ISSUE TITLE
Default messages in HttpException and subtypes are out of date

### ISSUE THREAD

**Issue by alexweissman** [userfrosting/UserFrosting#1129]
The default messages in `HttpException` and its subtypes are actually translator keys. But, the key names are outdated and need to be updated. See for example: https://github.com/userfrosting/support/blob/master/src/Exception/HttpException.php#L38

I believe this is now `ERROR.SERVER`.

This also brings up an architectural issue, in that the `support` module sort of has a soft dependency on the translation module because of these translation keys.

In the meantime we should probably just update the translation keys in `support`.

**Comment by lcharette** [comment]
Fun fact, `notFoundHandler ` [is gone in Slim 4](https://stackoverflow.com/questions/57648078/replacement-for-notfoundhandler-setting/57648863). Slim4 returns [it's own exceptions](https://www.slimframework.com/docs/v4/middleware/error-handling.html#new-http-exceptions), which means UF exception won't be used in the future... It doesn't seams that bad, until you consider it will make translating the exception title/message/description difficult.

> This also brings up an architectural issue, in that the support module sort of has a soft dependency on the translation module because of these translation keys.

Easy fix is to move the exception to Core actually.

**Comment by lcharette** [comment]
For V5, User facing messages are now tied to the exception in the handler based on the status code (eg `ERROR.403.TITLE`) since Slim's Exception will be used (can't overwrite them). Messages have been updated in the locale : https://github.com/userfrosting/sprinkle-core/commit/25042af414b98d327b4023ecfcb7d24fa65cd4ce
