### ISSUE TITLE
Remove rel=author, rel=publisher tags from base template

### ISSUE THREAD

**Issue by alexweissman** [userfrosting/UserFrosting#1136]
These are no longer supported by Google, and I doubt they are supported by any other major search engines either.

See:
- https://support.google.com/webmasters/thread/3064840?hl=en
- https://searchengineland.com/goodbye-google-authorship-201975

**Comment by Silic0nS0ldier** [comment]
Fairly sure schemas at https://schema.org/ have since covered this. Would be worth looking into (particularly if there is a direct replacement).
