### ISSUE TITLE
Asset dependency install fails on Windows with NPM v7

### ISSUE THREAD

**Issue by lcharette** [userfrosting/UserFrosting#1140]
See here : https://github.com/userfrosting/UserFrosting/runs/2061948433?check_suite_focus=true#step:7:47

```
Installing frontend vendor assets
---------------------------------

> npm run uf-assets-install

> uf-assets-install
> ./node_modules/.bin/gulp assetsInstall

'.' is not recognized as an internal or external command,
operable program or batch file.

Error: ] assets installation has failed       
                                                                         
Error: Process completed with exit code 1.
```

Should be the only missing piece for 4.5.0 release (beside usual stuff).

**Comment by Silic0nS0ldier** [comment]
I forgot about that. Fix should be to remove `./` from `build/package.json` scripts should do the trick. NPM v7 would be responsible for this.

**Comment by Silic0nS0ldier** [comment]
With this being a bug on develop and having been resolved there, I'm closing this.
