### ISSUE TITLE
Missing node version in Bakery Debug command

### ISSUE THREAD

**Issue by lcharette** [userfrosting/UserFrosting#1141]
I noticed the Bakery debug command doesn't show the current node version anymore : 

```
---------------------- --------------------------------------------- 
  UserFrosting version   4.5.0-dev                                    
  OS Name                Linux                                        
  Project Root           /home/runner/work/UserFrosting/UserFrosting  
  Environment mode       debug                                        
  PHP Version            7.2.34-18+ubuntu20.04.1+deb.sury.org+1       
  Node Version                                                        
  NPM Version            6.14.11                                      
 ---------------------- --------------------------------------------- 
```

For example : 
https://github.com/userfrosting/UserFrosting/runs/2061948500?check_suite_focus=true#step:12:24

**Comment by Silic0nS0ldier** [comment]
Damnit, that would be because of a misnamed variable. https://github.com/userfrosting/UserFrosting/blob/develop/app/sprinkles/core/src/Bakery/Helper/NodeVersionCheck.php#L36

Thoughts on gradually adding strict types to guard against these kind of mistakes in the future @lcharette ?

**Comment by lcharette** [comment]
> Thoughts on gradually adding strict types to guard against these kind of mistakes in the future @lcharette ?

As far as we maintain compatibility with the lastest PHP version we support, I try to add it as I update code.

**Comment by Silic0nS0ldier** [comment]
@lcharette This has been resolved right?

**Comment by lcharette** [comment]
> @lcharette This has been resolved right?

Yes. Was waiting for Issue to close itself when PR is merged in master, but I guess it makes sense to close it right now.
