### ISSUE TITLE
Dates in Database stored as timestamp (epoch based) might cause issues in 2038 onwards

### ISSUE THREAD

**Issue by anesuc** [userfrosting/UserFrosting#1144]
Hi all,

The title pretty much explains it all. I know that's a bit far away, but coming up pretty soon. I think it's prudent to get around this earlier as some devs might pull this project and rarely update the live version for any given reasons.

**Comment by lcharette** [comment]
Isn't it something we rely on Laravel Eloquent for? That would be on their side ?

**Comment by anesuc** [comment]
> Isn't it something we rely on Laravel Eloquent for? That would be on their side ?

Alright. I haven't looked at the code that handles those, but that makes sense. In that case, they will surely get around this sooner than later. Regardless, I would like to think there would be a way around that with like a Laravel package or equivalent if we don't want to wait for the Laravel dev team.

**Comment by Silic0nS0ldier** [comment]
This would be a database level issue would it not? And at that, likely does not affect all databases.

I don't believe we receive the timestamp as an epoch from the database either (unless that occurs at the driver level, which is well outside of UF's scope and Laravel's for that matter). I've poked around the Laravel query builder source of fair bit last year, so I'm fairly confident that if the issue exists is (1) at a lower level and (2) can be resolved by updates to components at those lower levels.

**Comment by lcharette** [comment]
I agree. Most place we use dates, it's in a [timestamp](https://laravel.com/docs/8.x/migrations#column-method-timestamp) typed columns, defined in Laravel Migration. And those columns are auto filled with Laravel magic methods. Not something in our scope / timeframe yet.
