### ISSUE TITLE
Optimise GitHub Actions - Avoiding Identical Builds

### ISSUE THREAD

**Issue by Silic0nS0ldier** [userfrosting/UserFrosting#1149]
A quick follow-up-later task. Currently PRs have builds run twice as (generally) the PR content is based on a branch with pushed code (there may ways to open a PR without a push, but they are rare). This slows the PR checks, and unnecessary ties up GitHub resources. We should optimise the build triggers.

**Comment by lcharette** [comment]
It _could_ be optimized, but AFAIK this is the "expected" behavior. PR build is required for external contributor, while push is required for internal (non PR) contribution. We could add a branch filter, but then feature branches wouldn't be tested before the PR is created. Plus, push and PR could produce different output if the base branch is not up to date with the target one (unless I'm mistaken). 

See : 
 - https://github.community/t/duplicate-checks-on-push-and-pull-request-simultaneous-event/18012
 - https://github.community/t/duplicate-trigger-on-the-same-commit-push-and-pull-request/18473

On a similar note, IMO we shouldn't create new feature branch on the main repo, but submit all PR from our personal fork (this applies to everyone with push access, me included), **unless** the goal is to push directly to hotfix/develop of course. Then builds would only be executed against the PR target inside the PR itself (eg.: https://github.com/userfrosting/UserFrosting/pull/1142) - push is still executed on the fork. It would also keep the main repo cleaner.


(At least it's not the 3h build from Travis anymore /s )

**Comment by Silic0nS0ldier** [comment]
> (At least it's not the 3h build from Travis anymore /s )
I did notice that.

I'll poke around the GitHub docs and experiment a little when I have the chance. I'm sure there is a way to ensure jobs occur once across multiple different triggers (ideally without requiring some bail-out task in jobs, which wouldn't be worth the effort).

**Comment by lcharette** [comment]
Also note, since we're positioned to get one less supported PHP version in 4.6, build time will be further reduced. I think, for now, this issue is very low priority and should probably be closed.

**Comment by Silic0nS0ldier** [comment]
Fair, build speed has demonstrated itself as being a micro-optimisation on this front.
