### ISSUE TITLE
`asset-bundles.json` may be parsed as YAML instead of JSON when whitespace is inconsistent

### ISSUE THREAD

**Issue by Silic0nS0ldier** [userfrosting/UserFrosting#1158]
https://chat.userfrosting.com/channel/support?msg=8LwJd3GPH5EvKeSiX

To fix this a JSON specific loader should be used instead. As it stands now, parsing is inconsistent causing issues like quotes being seen as part of the string (as opposed to its container).

**Comment by lcharette** [comment]
So... Change `YamlFileLoader` with a `JsonFileLoader` here  https://github.com/userfrosting/assets/blob/bfffb85e75553b4b60332778cad54ed1f6efa079/src/AssetBundles/GulpBundleAssetsBundles.php#L88 ?

**Comment by Silic0nS0ldier** [comment]
Correct

**Comment by lcharette** [comment]
Then I think we should deprecate Json fallback for YAML? The fallback should be done in the end user IMO. @alexweissman though on this? I think you introduced YAML in teh first place?

**Comment by Silic0nS0ldier** [comment]
I'm not even sure the JSON loader ever gets hit, given its supposed to be a superset of JSON. Regardless, deprecation is a must so we don't break things on the next update unintentionally. If it does get hit, then the YAML parser is flawed.

**Comment by lcharette** [comment]
Not relevant in UF5 anymore
