### ISSUE TITLE
UF Blog type system

### ISSUE THREAD

**Issue by lilfade** [userfrosting/UserFrosting#116]
Started on this the other night, still a lot to do but i think it will work great for what i want it to do what do you think should it be a plugin or included in the core package with a toggle setting? 

By toggle setting i mean, setup index.php to redirect to blog.php if the admin wants it rather then the front page with "Login" on it they can show public news and such here rather then the main index. If off it just will show the regular main index. This could then be used on dashboard in a widget to show the logged in posts so to speak that wouldn't be show to guests.

Basic output of each post:

``` php
<?php
                $html = "";

                foreach ($blogPosts as $post)
                {
                    $html .= '
                    <h2>
                        <a href="blog.php?id='.$post->id.'">'.$post->title.'</a>
                    </h2>
                    <p class="lead">
                        by <a href="profile.php?uid='.$post->author['id'].'">'.$post->author['display_name'].'</a>
                    </p>
                    <p><i class="fa fa-clock-o"></i> '.$post->datePosted.'</p>
                    <hr>
                    <img class="img-responsive" src="http://placehold.it/900x300" alt="">
                    <hr>
                    <p>'.$post->post.'</p>
                    <a class="btn btn-primary" href="blog.php?id='.$post->id.'">Read More <i class="fa fa-chevron-right"></i></a>
                    <br /><hr /><br />';
                }

                echo $html;
                ?>
```

The Class, like i said nothing big yet needs alot to be done but not bad so far for being simple.
https://github.com/lilfade/UserFrosting/blob/dev/models/class.blog.php

The look so far may need a bit of css love or a logo or something:
![blog](https://cloud.githubusercontent.com/assets/4168401/4161503/d905f7f4-34ce-11e4-9fb5-76d0e4eb8f31.jpg)

**Comment by alexweissman** [comment]
Would really like to see this as a plugin for the new version.  Hoping to have a drop-in system where all plugin files can be placed in `userfrosting/plugins` and can interact with the core system via hooks.
