### ISSUE TITLE
`sh: shell: command not found` when installing assets

### ISSUE THREAD

**Issue by lcharette** [userfrosting/UserFrosting#1164]
```
$ php bakery build-assets
UserFrosting's Assets Builder
=============================

Installing npm dependencies
---------------------------

> npm install
Skipping as package-lock.json age indicates dependencies are already installed

Installing frontend vendor assets
---------------------------------

> npm run uf-assets-install

> @ uf-assets-install /Users/malou/Desktop/UserFrosting/build
> shell './node_modules/.bin/gulp assetsInstall'

sh: shell: command not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! @ uf-assets-install: `shell './node_modules/.bin/gulp assetsInstall'`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the @ uf-assets-install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

Reproduced locally using PHP 7.4.16 on MacOS (node v12.18.3) and Ubuntu VM (v14.17.3).

Running `./node_modules/.bin/gulp assetsInstall` from `build/` works fine as a workaround. 

I suspect an interference from PHP passthrough.

**Comment by lcharette** [comment]
It's actually the `shell` here that is not found... Not an issue with PHP `passthru`... hum..  https://github.com/userfrosting/UserFrosting/blob/896dd85705e81b16f33c54debfc034e2f85f3bd2/build/package.json?plain=1#L27

I would think it's my Mac that could be the issue, but same problem with Ubuntu VM... @Silic0nS0ldier any idea? Was `shell` a Windows thing ?

**Comment by Silic0nS0ldier** [comment]
Partially. So is `shell` not getting added to `PATH` in the NPM context? Very odd. I'll dust off my Ubuntu machine this afternoon (6 hours away my time) and investigate.

**Comment by lcharette** [comment]
Would it be as simple as adding [`"shell": "^0.8.4",`](https://www.npmjs.com/package/shell) to `build/package.json`? Could be another dependency that dropped Shell as it's own?

**Comment by lcharette** [comment]
I've run a couple of clean installs and issue is gone... Not too sure why it happened in the first place... I'll close for now...

**Comment by Silic0nS0ldier** [comment]
>  I'll dust off my Ubuntu machine this afternoon (6 hours away my time) and investigate.
RIP, I totally forgot. Glad to hear the issue is resolved though.
