### ISSUE TITLE
All of the vendor files seem to be throwing exceptions

### ISSUE THREAD

**Issue by sathrall** [userfrosting/UserFrosting#1185]
### Discussed in https://github.com/userfrosting/UserFrosting/discussions/1184

<div type='discussions-op-text'>

<sup>Originally posted by **sathrall** December  6, 2021</sup>
I noticed that there are missing vendor files because there's an exception thrown for each of them when any template attempts to render.

>An exception has been thrown during the rendering of a template ("No file could be resolved for the stream path 'assets://vendor/fontawesome-iconpicker/dist/css/fontawesome-iconpicker.css'.").</div>

**Comment by lcharette** [comment]
This is a common problem. See doc:  https://learn.userfrosting.com/troubleshooting/common-problems#an-exception-has-been-thrown-during-the-rendering-of-a-template
