### ISSUE TITLE
Create logic out of database schema.

### ISSUE THREAD

**Issue by MegamindAme** [userfrosting/UserFrosting#1210]
Hello Guys,
I thought about this feature while developing a web app for an organization using userfrosting. 
I wondered if there could be a way to create all MVC files needed for a particular database table(s) from just one command.
To put it simply,
#### To create logic(code) out of database schema.
Is it possible?
Yes, I think that it is possible considering that database table records in every web app must be created, updated, deleted, and get queried. And we can create a code to automate that whole process. 
For example, a database record has tables of users, permissions, roles, role_users, and permission_roles. It is quite obvious that our code will be creating a user, editing a user, and adding and editing user roles. We will create a controller file and place a createUser, update User, and delete User functions,  which for every database record there is, will eventually have the similar lines of code for creating, updating, deleting, and querying the database record (in our case, the user). And inside this or another controller, we will have functions that create, update, delete, and query permissions and roles also, Creating role_users and permission_roles record(s). As I stated earlier, you will eventually have similar lines of code for every table schema you have, keeping in mind the table relationships. The only thing that's changing in these create, update, and delete functions is the "table name", "table columns", and "relationship names" in model files mostly. And all of these changing attributes can be fetched from the database using SQL. The same happens in sprunje files, model files, and templates (we have the same table layouts, only the column names change in templates).
Can't we have something that will be that dynamic, having templates for all MVC files needed, and just changing the "above-quoted attributes" in every MVC file? That way sprinkles can be fast generated, and huge systems can be built in a matter of weeks. And all this database schema to logic thing be done by using commands.
We can even generate test files too.

My Huge Thanks to every userfrosting Contributor.

**Comment by lcharette** [comment]
It could be done in a custom sprinkle, but not planed for core UF
