### ISSUE TITLE
Multi-tenant site

### ISSUE THREAD

**Issue by Jeff-P** [userfrosting/UserFrosting#175]
is there any video examples/tutorials online? Just curious if anyone knows as I couldn't find any? Also has anyone tried this with a multi tenant site, I'm curious as I'm currently working on a multi tenant site.

**Comment by wdapp2015** [comment]
Hello - 

I am also looking for a multi-tenant solution for my site. @MapleDash or @UnicornDelight are either of you willing to share your hacks ?   

Thanks in advance!

**Comment by Poolaidman** [comment]
@wdapp2015 there are some at usercake.com

**Comment by alexweissman** [comment]
I'm looking into this, and how it might fit together with the concept of "packages".  Multi-tenant sites might have some equivalency with packages.

**Comment by alexweissman** [comment]
Multi-tenancy is a pretty broad topic.  I'm not sure if there is necessarily one "correct way" to implement multi-tenancy with UF.  Depending on your needs, you might solve this with completely separate installations using Docker.

Alternatively, if you have just a few tenants who need to share a common codebase, this can be achieved by setting up a Sprinkle as a git submodule and including it in multiple instances of UserFrosting.

At any rate, we can revisit this subject with UF4 if someone can give me a better idea of what they're looking for.
