### ISSUE TITLE
SAML Support

### ISSUE THREAD

**Issue by pitbulk** [userfrosting/UserFrosting#202]
@alexweissman Are you interested in adding [SAML](http://en.wikipedia.org/wiki/Security_Assertion_Markup_Language) support?

I already implemented it in my local environment and support SSO and SLO, I can create a PR if interested.

**Comment by alexweissman** [comment]
Whoa, that's cool!  I was hoping that we'd get some kind of SSO down the road.  

I was originally thinking OAuth, but I don't really know what would be the best for UF.  Can you make a good case for SAML over OAuth?

**Comment by pitbulk** [comment]
SAML and OAuth2 are different protocols.

With SAML you will let your users to log in the system using an external Identity Provider (Salesforce, Google, OneLogin, Okta, ...).
Also there is an open source software named simpleSAMLphp that let you deploy an Identity Provider. With this software you can configure a lot of social authentication, so adding SAML support to UserFrosting you will be able to autenticate users using any Social account (Facebook, Twitter, Google, ....), or any external database/ldap.

**Comment by alexweissman** [comment]
Whoa, I didn't realize that it would be such a simple drop-in!  I was just reading [this article](http://www.mutuallyhuman.com/blog/2013/05/09/choosing-an-sso-strategy-saml-vs-oauth2/):
> SAML has one feature that OAuth2 lacks: the SAML token contains the user identity information (because of signing). With OAuth2, you don't get that out of the box, and instead, the Resource Server needs to make an additional round trip to validate the token with the Authorization Server.

> On the other hand, with OAuth2 you can invalidate an access token on the Authorization Server, and disable it from further access to the Resource Server.

I'm not really sure what this would mean for UF, but it seems like something that can easily be turned on/off by developers.  I'll play with it in a little bit and then probably pull it!

Also, send me an email through my website.  I have some ideas for other authorization features in UF, and it looks like you have quite a bit of experience in that domain.  Would be cool to chat!

**Comment by pitbulk** [comment]
I sent you my mail

**Comment by ratkobucic** [comment]
@pitbulk 
> Are you interested in adding SAML support?
> I already implemented it in my local environment and support SSO and SLO

Hi, I'm trying to add some nice user registration form for one project I work on, and SAML support for UserFrosting would be exact what I'm looking for... :)
So, if you don't mind, can you share your setup/patch for UserFrosting SAML integration?
Thanks +1:

**Comment by dudheit314** [comment]
Any news on this one? I'd really like to use it too!

**Comment by Silic0nS0ldier** [comment]
Might be an old issue, but I thought I'd just clear something up. OAuth (and OAuth2) only provide authorization. There is however authentication layers built on top of it via OpenID Connect.

But back onto the topic of SAML, what user information is guaranteed to be available for the context appropriate to a system like UserFrosting? Hopefully the information is nice and standardised. (unlike OpenID Connect which is a mess beyond the issuer and id combo).

**Comment by lenasterg** [comment]
Hi. 
Do you have any news on this one? Or a link on how we can try to make SSO and UF work together?
Thanks in advance

**Comment by pitbulk** [comment]
The SAML integration I did was for a very old version of UserFrosting
Sadly, right now I don't have much spare time to contribute such extension.

**Comment by lenasterg** [comment]
@pitbulk Thanks for your prompt reply.
