### ISSUE TITLE
SCIM support

### ISSUE THREAD

**Issue by pitbulk** [userfrosting/UserFrosting#205]
In order to use UserFrosting as an "Identity Provider" and use its data for using provisioning in 3rd party applications I plan to integrate a [SCIM Server](http://www.simplecloud.info/).

Any suggestion in how start?

**Comment by alexweissman** [comment]
I just tried running the demo server (http://opensourcecoin.org/awesissman) through the compliance tester (http://www.simplecloud.info/#complianceTest), and the first error I got was in trying to access the `ServiceProviderConfigs`.

So, you could start by trying to implement that as an API, according to the specifications they provide: http://www.simplecloud.info/specs/draft-scim-core-schema-01.html#anchor6

It looks interesting.  We are talking about having a JSON User schema in the next version of UF, it might fit in nicely with SCIM.

**Comment by pitbulk** [comment]
@alexweissman I added SCIM support to userFrosting so now I'm able to provision users on 3rd party programs.

Review this demo where I provisioned users on Moodle and Omeka:
https://www.youtube.com/watch?v=G8cQOpGtT_E

**Comment by alexweissman** [comment]
Nice!  Mind if I link to this on the website?  Also, would you consider developing this as a plugin for the next version of UF?

**Comment by pitbulk** [comment]
You can link the video. I implemented this with an older version of userFrosting and still need to improve a lot the code. Let's see how gonna be the next UF release and I will try to adapt the code, and who knows, maybe release the plugin.
