### ISSUE TITLE
Paid Membership Options?

### ISSUE THREAD

**Issue by investordashboards** [userfrosting/UserFrosting#302]
Anyone working on adding an option for paid options? Specifically Paypal one time or recurring?

Rodger

**Comment by zwebmedia** [comment]
Yes, I also am looking for PayPal recurring payments/subscriber management for protected content membership site.

**Comment by alexweissman** [comment]
You should look into [Stripe](http://stripe.com).  Paypal are a bunch of thieves ;-)

**Comment by zwebmedia** [comment]
Thanks Alex, UserFrosting looks perfect for what I need, and sincere thanks guys for all the work, and putting this in the public domain.

Understood about chargebacks, and the infamous "Your account has been limited" (been there, done that). When that happens all your recurring payments get canceled, and yes it's painful, speaking from personal experience. High risk and already torpedoed my business once or twice before. 

But I am in Thailand, and Stripe (as well as almost every major merchant account) is only for US residents. And some people are not selling software, which is susceptable to unscrupulous buyers and chargebacks. And some people have loyal customers. 

Let's compormise and say it's not up to us to decide what the other person needs, and we need both Stripe and PayPal (and ProPay, 2Checkout, Authorize.net, Amazon, etc.)? User management is great, but without the ability to automatically process recurring payments (with a trial period), no good options to monetize.

I currently use OpenCart 2.0 for a web store, and it comes with a long list of payment processors already supported, and extensions for many more can be purchased. So just recommending this as a feature request thanks again guys.

**Comment by alexweissman** [comment]
Ok, no problem.  To be honest, I wouldn't really consider this a candidate as a "core feature" for UserFrosting.  There are just too many possible ways of setting this up (i.e., do you pay on registration, or on a subscription, etc) and it doesn't really have anything to do directly with user account creation and management.

But, it shouldn't be too hard for you to implement, if Paypal provides a suitable API.
