### ISSUE TITLE
External modules/plugin support

### ISSUE THREAD

**Issue by Etuldan** [userfrosting/UserFrosting#305]
I started a fork of UserCake some month ago, adding a plugin system to be able to manage users for external platforms like PhpBB, Owncloud, MediaWiki, and so one (every one can create his plugin)
https://github.com/Etuldan/UserNougat

I just discover your fork, and I wonder how we can merge (if you want to) our forks, and contribute for a single common solution.

**Comment by alexweissman** [comment]
Hi @Etuldan, I would definitely be interested in any help/contributions you could offer!  

You should be aware though, that the current development version (https://github.com/alexweissman/UserFrosting/tree/slim), is going to be pretty different from UserCake and even the current version of UF.  

We are switching over to some modern programming paradigms, and it will be fully OOP, MVC and use popular pre-existing components including Slim, Twig, and RedBean.  If this sounds like something you want to be a part of (go ahead and check out the `slim` branch first), then send me a message through my website and we can talk!

**Comment by alexweissman** [comment]
The plugin system basically works, based on [Slim's hook system](http://docs.slimframework.com/hooks/how-to-use/).  All we need to do is scatter some useful hooks throughout the core code.

**Comment by alexweissman** [comment]
See #472 for a more specific discussion of plugin hooks.
