### ISSUE TITLE
Contributor Guidelines

### ISSUE THREAD

**Issue by r3wt** [userfrosting/UserFrosting#320]
We should develop a set of contributor guidelines for going forward. 

Let's defined the sections:

** Best Practices **
 
** Pull Request Guidelines **

** Labels **

** Security Fixes for Deprecated Branches **

** Branches **

**Comment by alexweissman** [comment]
Welp, I guess this is getting pushed back again...

**Comment by alexweissman** [comment]
Starting in UserFrosting 4, we will have [style guidelines](https://github.com/userfrosting/UserFrosting/blob/dev/STYLE-GUIDE.md).
