### ISSUE TITLE
Array Index for Return Array function fetchAll in MySqlObjectLoader.php

### ISSUE THREAD

**Issue by ssnukala** [userfrosting/UserFrosting#333]
```
UserFrosting/userfrosting/models/mysql/MySqlObjectLoader.php
Line: 76
        // Return an array of arrays
        $results = [];
        while ($row = $stmt->fetch(\PDO::FETCH_ASSOC)) {
            $id = $row['id'];
            $results[$id] = $row;
        }     
```
This will cause issues if used `$results[7]` vs `$results['7']`
I have had issues in the past when using values from variables like $results[$var_id] it will try to use the numeric value to get numeric index rather than the associated text value index. I have had issues with this before. 

I would recommend updating this to a text based index like $id = "ID-".$row['id'];
And the code downstream can strip out the ID- or just use the value from the record

**Comment by alexweissman** [comment]
It looks like Eloquent doesn't index by primary id for their Collections, so this might become a moot issue.

**Comment by alexweissman** [comment]
I believe this is no longer an issue, now that we're using Eloquent.
