### ISSUE TITLE
How to access the REST API?

### ISSUE THREAD

**Issue by axtscz** [userfrosting/UserFrosting#385]
How do I access the REST API? Let us say that I have UF installed at HTTP://mywebsite.com/userfrosting.

**Comment by alexweissman** [comment]
Could you be more specific?  What sort of data do you want to access?

**Comment by axtscz** [comment]
How do I return a list of users or a specific users?

**Comment by alexweissman** [comment]
As structured data?

**Comment by axtscz** [comment]
Yes

**Comment by axtscz** [comment]
Thanks, Alex. Do you have any sort of REST API in the 0.3.0 release?

**Comment by alexweissman** [comment]
Well, the route structure as a whole is more or less RESTful, see http://www.userfrosting.com/components/#url-structure.  It doesn't have a built-in API for structured data, but like I said, that is pretty easy to implement.

**Comment by alexweissman** [comment]
We've been getting a lot of requests for a true REST (so, stateless, sessionless?) API in chat.  So, maybe this is something we should consider implementing in a future version.

**Comment by harding13** [comment]
Could be an answer? https://github.com/entomb/slim-json-api
