### ISSUE TITLE
Separate "groups" from "roles"

### ISSUE THREAD

**Issue by alexweissman** [userfrosting/UserFrosting#401]
I believe the notion of "group" is suffering an identity crisis. 

On the one hand, groups control user authorization by way of the authorization hooks with which they are associated.  Users can belong to multiple groups, thus making it easy to assign/reassign entire sets of permissions at a time.

On the other hand, users only belong to one "primary group".  This association determines the user's theme, icon, default locale, and various other "cosmetic" properties.

I propose that we separate out these two concepts into two different abstractions.  I propose we rename what are currently known as "groups" to "roles".  This would put us in line with the terminology used by the [rest of the auth community](https://en.wikipedia.org/wiki/Role-based_access_control).  Users will still be able to have multiple roles.

I propose that we then change the label of "primary group" to simply "group".  Every user will belong to exactly one group, which will determine their theme, landing page, etc.

It will still be possible for different users in the same group to have different roles.  But it would remove the confusion over "group" vs "primary group".

Thoughts?

**Comment by frostbitten** [comment]
This explanation previously solved my confusion so I recommend this change.

**Comment by alexweissman** [comment]
Alright, here is a more in-depth write-up: http://stackoverflow.com/questions/32937242/does-this-make-sense-as-a-way-to-implement-role-based-access-control

**Comment by alexweissman** [comment]
This has now been implemented in `dev`.  Users can have one or more Roles, and each Role can have one or more Permissions.  Permissions are the same thing as the rules that have been defined in `authorize_user` and `authorize_group` in 0.3.x.

Default Roles:
- User
- Site Admin
- Group Admin

Meanwhile, each user belongs to exactly one group.  Groups are just ways of partitioning users based on some common attribute.  For example, perhaps a site for a company would have a separate Group for each department.  Giving someone the Role of "Group Admin" would allow them to manage users who belong to their same group, for instance.

Default Groups:
- Terran
- Zerg
- Protoss

I still haven't decided if it would be wise to allow groups to map to Roles or Permissions as well, or if that would just create unintended consequences.  Membership in a Group can still be used _indirectly_ to control access, for example using the `in_group` access condition.
