### ISSUE TITLE
Organize client-side code with Bower/Grunt

### ISSUE THREAD

**Issue by alexweissman** [userfrosting/UserFrosting#406]
Over the past few months, we've done a great job bringing the server-side code up to snuff with Slim, Twig, and our object-oriented data model.

The client side code, on the other hand, is another story.  We should at the very minimum take advantage of some of the great tools available for Javascript:
- RequireJS
- Node.js
- Bower
- Grunt

See http://www.slideshare.net/weaverryan/cool-like-frontend-developer-grunt-requirejs-bower-and-other-tools-29177248.

**Comment by r3wt** [comment]
i would like to put in a vote for gulp, uglify, and documentation.js

It's pretty easy:

https://github.com/r3wt/jqMVC/blob/master/gulpfile.js

**Comment by ssnukala** [comment]
I started with bower and use it in my application now. Did not get it to minify and require.js etc but have organized all the js libraries and have a bower package. 
I can share what I have. Still learning requirejs so have not implemented that fully.

**Comment by alexweissman** [comment]
Let us continue this discussion in #560.  I know @ssnukala has been cooking something up for handling and compiling asset bundles in Node.js.
