### ISSUE TITLE
Username silently altered

### ISSUE THREAD

**Issue by Netrilix** [userfrosting/UserFrosting#423]
When registering, the username is silently changed to a lowercase.

The username should stay the way the user entered it, and then be changed to lowercase when being compared (eg. for logins). Any time it's being displayed, it should reflect the user's original capitalization (unless change is needed for site styling, of course).

**Comment by alexweissman** [comment]
What about:
`display_name`: Should we `trim()` it?
`email`: Should we preserve case?  Should we `trim()` it?

**Comment by alexweissman** [comment]
Lemme know, we can do this for 0.3.1.

**Comment by Netrilix** [comment]
My advice is to run trim() on literally every user text input field ever. I run a fairly large project where people were managing to insert tab characters into my database on a regular basis. I have no idea how it got in as input, as I assume they were trying to tab to the next input box, but it definitely happens more often than you'd expect. I think in every single case (even passwords), you can assume they didn't mean to end it in whitespace.

**Comment by r3wt** [comment]
i agree with netrilix. we should probably add an `rmnl` function that removes `\t`'s and `PHP_EOL`'s from target inputs. as an additional note, any email fields should be ran through this function as well, since a common mode of email header injection is to use line feeds to break out of the recipient field.

**Comment by alexweissman** [comment]
email validation already rejects leading/trailing whitespace.  for other fields, I've added the `no_leading_whitespace` and `no_trailing_whitespace` rules.  We can talk more about providing local/global data transformations through fortress.

**Comment by alexweissman** [comment]
Ok, the discussion of arbitrary data transformations is moved to Fortress.
