### ISSUE TITLE
Validation on UF Site Settings

### ISSUE THREAD

**Issue by markfischoff** [userfrosting/UserFrosting#441]
Not a big issue, but i think the site settings should also be validated, at least to make sure the email addres is valid and you don't end up like mine.
![translation](https://cloud.githubusercontent.com/assets/1165587/10802321/f883a9d8-7dc4-11e5-973e-bc35a9b14338.png)

**Comment by Netrilix** [comment]
If you do e-mail validation, be liberal with what you accept as valid. A lot of e-mail providers don't follow the RFC perfectly, so people can have perfectly valid and usable e-mail addresses that are technically "invalid" by the official specifications.

**Comment by alexweissman** [comment]
Well we already do email validation for other forms in UF (registration, account settings, etc), so it would probably be consistent with that.

**Comment by alexweissman** [comment]
We're getting rid of the "site settings" page from the basic UF installation (see #547), but @lcharette might be implementing a DB-driven site settings Sprinkle as an optional add-on.  I believe this will support field validation.

**Comment by lcharette** [comment]
Yes, all setting fields will use Fortress valdiation
