### ISSUE TITLE
Conversion script for 0.3.0 to 0.3.1

### ISSUE THREAD

**Issue by Netrilix** [userfrosting/UserFrosting#443]
Convert the old database format to the new one (user-record based to user-event based).

[Don't think I can assign myself on this one, but I'm working on it.]

**Comment by alexweissman** [comment]
Any updates on this?

**Comment by Netrilix** [comment]
It's functionally complete, but I was a little apprehensive about releasing it without transactional rollbacks so it doesn't leave the database half-converted if a query fails. That's my next step, just haven't had a chance to complete it yet.

**Comment by alexweissman** [comment]
This is ready to use, right?  https://github.com/userfrosting/Upgrade

**Comment by Netrilix** [comment]
Yes, the database conversion itself is ready. I've still got an open issue over on Upgrade to make the instructions more clear, but the functionality is solid.
