### ISSUE TITLE
Split routing code into separate include or autoload files

### ISSUE THREAD

**Issue by Netrilix** [userfrosting/UserFrosting#449]
The routing code is starting to get too large to be contained in a single file (index.php). I'm going to look into these three options:
- Have composer autoload the routes
- Autoload them from predictably-named include files
- Include them manually.

If anyone has any opinion on which of these three methods would work best in the long run, feel free to speak up.

**Comment by alexweissman** [comment]
I have a feeling that using Composer to autoload procedural code is possible, but is an abuse of its functionality.  I don't think it is possible to enforce a loading order with Composer, which could be a problem for some routes.

I like option 2 the best.

**Comment by Netrilix** [comment]
I agree with that. I'm thinking that manual inclusion is the safest way, because auto-loading based on names always has a chance of colliding with a developer's existing code.

**Comment by r3wt** [comment]
how would you possibly autoload routes? there's no benefit. if they all have to be added to the router, then you can't "autoload" which is essentially lazy loading.

what you can do is the same thing you do with the plugin folder. say there is a `routes` folder, you can glob(*) and load the files with require.

**Comment by Netrilix** [comment]
Yeah, that's what I meant by predictably named. All sitting in the same folder would work perfectly, similar to the way WAMP handles Apache aliases.

**Comment by Netrilix** [comment]
So these are the categories I'm looking at now:

  - Main pages (home, dashboard, zerg)
  - Account management
  - User Management
  - Group Management
  - Admin Tools
  - Install
  - Utilities (js, alerts, etc.)

This pretty much mirrors the way they're already split by comments in `index.php`

My current plan is to drop each category into its own file in `userfrosting/routes`. The program will then search there and also in `userfrosting/plugins/*/routes` to find all routes and load them.

From there, the plan is to allow route overrides by plugins, but throw an exception if two plugins try to use the same route (whether it's an override of the base or not).

**Comment by alexweissman** [comment]
Alright, let's do this.  We can also get rid of the anemic `*Controller` classes in this case (merge their work directly into the routes), since they don't really harness any of the useful aspects of OOP anyway.  

Let's also combine this with our plan for an off-the-shelf asset manager (#504).  Then, there will generally be no need to do any work in `public` at all!

**Comment by alexweissman** [comment]
This should also be done in coordination with #486.  If we can't get to the YAML/whatever stuff right away, that's ok.  We can use a PHP array until we figure that out.

**Comment by alexweissman** [comment]
This has been implemented in `dev`.  You can split up routes into as many files as you'd like in each Sprinkle's `/routes` directory.
