### ISSUE TITLE
Adding new template?

### ISSUE THREAD

**Issue by SEOArcade** [userfrosting/UserFrosting#453]
Hi there.
Thanks for your hard work on this amazing tool, it is really handy!

I have been trying to find some references but I couldnt find anything regarding templates. I would like to change default template to AdminLTE open source one.
The problem is that when I add template folder and change it for user, the whole page gets broken. Is there any other way besides manually replacing piece by piece?
Thanks!

**Comment by alexweissman** [comment]
It really depends on the layout of the template you want to include.  UF relies on a lot of different elements in the theme to work together, so you will likely have to adapt the template you found to the UF structure.

**Comment by alexweissman** [comment]
Let us know if you have any more questions.
