### ISSUE TITLE
Consider detection of GD and ImagePNG() in the captcha code

### ISSUE THREAD

**Issue by panchtox** [userfrosting/UserFrosting#456]
Error log gives me:
`[Fri Nov 06 19:20:34.326174 2015] [:error] [pid 59416] [client 127.0.0.1:53020] Fatal error (1) in /Library/WebServer/Documents/miscositas/userfrosting/controllers/BaseController.php on line 158: Call to undefined function UserFrosting\\ImagePng(), referer: http://foo.example.com/######/public/`
I've commented `ImagePng($image);` in that file. It works but image obviously is not loading.

**Comment by Netrilix** [comment]
Could you try changing from `ImagePNG($image)` to `imagepng($image)` and see if that fixes it?

**Comment by panchtox** [comment]
Thanks, that did it.

**Comment by Netrilix** [comment]
Alex, this appears to be a namespace issue, but I'm unsure why the other GD functions work fine within this method.

**Comment by Netrilix** [comment]
It's also server dependent. @panchtox, would you be willing to try it with only changing capitalization and only adding the slash and see which of the two fixes it for you?

**Comment by panchtox** [comment]
Now is working the 3 ways. I've made several changes yet so, it will be difficult to check which change would be responsible. Although I've encountered an issue related with native PHP OSX installation. It appears that in Maverick it has GD enabled but without PNG support.
I found this stackoverflow post that helped me: http://stackoverflow.com/questions/26443242/after-upgrade-php-no-longer-supports-png-operations
After reinstalling php using 1st answer suggestion, it made this and other several issues to disappear.
Thanks anyway for your kind work and help.

**Comment by Netrilix** [comment]
Oh, awesome. Thanks for tracking that down.

**Comment by alexweissman** [comment]
Is this something worth adding to the troubleshooting page?

**Comment by panchtox** [comment]
IMHO: I don't know if this is an issue that persists in Capitan OSX version so, it's difficult to determine if it's an extended problem. Nevertheless, in my opinion, based in the fact that is something originated from an external (to userfrosting) condition and in a configuration that is the default in a version of a popular operating system, it's worth adding it.

**Comment by Netrilix** [comment]
Would it be reasonable to throw an exception that explains the problem for:
* `gd` missing entirely at the top of the method
* `imagepng()` missing before it's called

**Comment by alexweissman** [comment]
Yeah, that is another possibility.  I thought this had come up before, actually...

**Comment by alexweissman** [comment]
Oh!  It came up in chat back in September: https://gitter.im/alexweissman/UserFrosting/archives/2015/09/10

**Comment by Netrilix** [comment]
Marking this as open because it's something we're still considering. Don't want it to get lost in the shuffle.

**Comment by alexweissman** [comment]
Yup, so maybe we can come up with a list of PHP modules to check for in the installer?

**Comment by alexweissman** [comment]
It looks like we check for `gd` on installation: https://github.com/alexweissman/UserFrosting/blob/master/userfrosting/controllers/InstallController.php#L106-L113

What else shall we check for?

**Comment by alexweissman** [comment]
Also, there is this question: http://stackoverflow.com/questions/31153438/what-is-imagepng-and-imagepng?lq=1

**Comment by alexweissman** [comment]
Ok, we now check for `imagepng` as well during installation (as of 0.3.1.8).
