### ISSUE TITLE
.twig file locations

### ISSUE THREAD

**Issue by joshblevins** [userfrosting/UserFrosting#459]
When building a form where does the .twig file go

**Comment by cmy82** [comment]
I think you can put them anywhere as long as you reference it correctly. I put min in the 'userfrosting/templates/themes/default/{myapp}/' folder so that I can use the relative uri properties.

**Comment by Netrilix** [comment]
If you're wanting to pull them using `$app->render`, they'd have to be in one of the paths that's already defined (`userfrosting/templates/themes/default`, for example), unless you also add a new path to the twig variable.

**Comment by Netrilix** [comment]
I'm closing this, but feel free to comment if you need more information and we can reopen it.
