### ISSUE TITLE
Request: Convert jQuery to noConflict mode 

### ISSUE THREAD

**Issue by cmy82** [userfrosting/UserFrosting#460]
Can the jQuery code be converted to use noConflict mode?
 ie. jQuery(document).ready( function($){ ... });
So that other frameworks can be used (ex MooTools).

**Comment by alexweissman** [comment]
I'm not sure - would this just mean replacing `$(...)` with `jQuery(...)` everywhere?  Could this potentially create any new problems?

**Comment by cmy82** [comment]
Yes, that's basically all that would need to be done. From what I see you already have the scripts wrapped in the $(document) tags. All of the standard jQuery plug-ins should already use that format‎, unless you wrote some yourself. I saw a few I didn't recognize, but most of the files I looked at already had that syntax. The only thing that should have to be changed are the .twig files. I can try it out on my own installation and make sure it doesn't create any bugs. I'm just partial to MooTools and can't use any of my already made scripts without noConflict mode.                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone on the Verizon Wireless 4G LTE network.                                                                                                                                                                                                                From: Alex WeissmanSent: Tuesday, November 10, 2015 9:06 AMTo: alexweissman/UserFrostingReply To: alexweissman/UserFrostingCc: Chris MyersSubject: Re: [UserFrosting] Request: Convert jQuery to noConflict mode  (#460)I'm not sure - would this just mean replacing $(...) with jQuery(...) everywhere?  Could this potentially create any new problems?

—Reply to this email directly or view it on GitHub.

**Comment by frostbitten** [comment]
There seems to be a number of ways to [use jquery in no-conflict mode,](https://learn.jquery.com/using-jquery-core/avoid-conflicts-other-libraries/) even retaining [the use of the $](https://learn.jquery.com/using-jquery-core/avoid-conflicts-other-libraries/#use-an-immediately-invoked-function-expression). mootools offers the same noconflict with its ["dollar safe mode"](http://mootools.net/blog/2009/06/22/the-dollar-safe-mode).

this seems to be the most concise and least amount of effort:
```
jQuery(function($){
    // Your jQuery code here, using the $
});
```

**Comment by cmy82** [comment]
I've been using MooTools for years and never knew of that; though I guess I never had reason to as its the only framework I use. I will try that and see how it works, though switching jQuery to no-conflict mode may still be a good idea. I'm working my way through doing that now, but some of the files/functions aren't behaving so nicely.

**Comment by frostbitten** [comment]
That mootools article says it's a very bad idea to use two libraries at once, such as jquery and mootools. Despite this, we should be able to wrap our jquery in that style i posted without much other changes. That is, unless you have mootools interacting with jquery? If that is the case, there are two options I think: Put jquery into something lke $j or put mootools into something like $m. Changing the code for this could be as simple as a search and replace.

**Comment by cmy82** [comment]
Yeah, everywhere I looked said the same thing, so I've stuck with MooTools for a few years. I don't have them interacting and I'm not using MooTools currently because I haven't been able to wrap the code and get it to work with minimal effort, yet. I was just looking for a way to keep from rewriting all of my code as I'm integrating UF into a site I've been working on for almost 2 years, and I didn't want to learn another framework. The non-UF portion of the site already has jQuery and MooTools integrated and I wanted to be able to reuse that code.

**Comment by frostbitten** [comment]
you should be able to keep all your mootools code by putting `
    var $m = document.id;` and change `$(mootools selector)` to `$m(mootools selector)`

**Comment by cmy82** [comment]
Yeah, I will try that next when I go to integrate the next page of the former site into the UF dashboard, and post the results.

**Comment by alexweissman** [comment]
Any update on this?

**Comment by cmy82** [comment]
I went the route of rewriting the code and using the mootools dollar safe mode as it was simpler and I couldn't get JQuery no-conflict mode to work for every function. I'm sure this can be closed.

**Comment by alexweissman** [comment]
Great, thanks for the update!
