### ISSUE TITLE
Site setting idea

### ISSUE THREAD

**Issue by Editandrew** [userfrosting/UserFrosting#466]
Maybe a usefull site setting would be SSL (on/off), allowing the admins to choose between http:// and https://

**Comment by alexweissman** [comment]
You mean, whether to force `http` requests to be redirected to `https`?

I'm not sure if this can be done in PHP.  However, this can be done in `.htaccess`:

```
RewriteCond %{HTTPS} !=on
RewriteRule (.*) https://%{HTTP_HOST}%{REQUEST_URI} [R=301,L]
```

**Comment by Editandrew** [comment]
Yes, I meant forcing `https`
I know it's possible in htaccess, I just thought it would be a cool & usefull setting.

**Comment by Netrilix** [comment]
Perhaps we could put it in the `.htaccess` and just comment it out? That way people can just uncomment it to activate it without having to worry about messing up the existing Rewrite rules with their new one.

**Comment by alexweissman** [comment]
Yup.  Actually, if you have access to the Apache `.conf` file (on a VPS or dedicated server), you can put the rewrite directly in the virtual host block.  Then, no need to keep switching HTTPS on and off when you deploy!

**Comment by r3wt** [comment]
closing since this isn't relevant. if someone disagrees they can reopen.

**Comment by alexweissman** [comment]
Actually, I'm going to mark this as a "todo", since it is trivially easy for us to add the following two lines to `.htaccess` (commented out by default, of course):
```
    # Enable this to forward all HTTP to HTTPS
    #RewriteCond %{HTTPS} !=on
    #RewriteRule (.*) https://%{HTTP_HOST}%{REQUEST_URI} [R=301,L]
```

I personally handle my https redirects in VirtualHost, but I can see how this would help a lot of people

**Comment by Netrilix** [comment]
Could someone just give this a quick test before we push the hotfix live? It's straight off StackOverflow, but I'd feel more comfortable if someone with an https server got a chance to test it, since I don't have one readily available.

**Comment by alexweissman** [comment]
Haha, this looks to be the exact same set of rules I used before I started using my VirtualHost config.  so, this looks great ;-)
