### ISSUE TITLE
jquery validator has different rules than fortress/valitron vaidation

### ISSUE THREAD

**Issue by frostbitten** [userfrosting/UserFrosting#467]
This email address (a@a) is a valid email according to jqueryvalidator but doesn't fit the bill according to fortress/valitron on the server-side (If you try to submit this you will get an email validator error)
![image](https://cloud.githubusercontent.com/assets/593791/11287382/0b0bc59c-8ee9-11e5-8a5d-aaf7f7b481f8.png)

Apparently, it is within standards to have an email with no domain extension (reference to come). So, the server is technically "wrong." This is really a matter of choice, however. Accepting any email address [just because it fits the standard may not be an ideal practce](http://girders.org/blog/2013/01/31/dont-rfc-validate-email-addresses/).

We may just want to modify the rule in jqueryvalidator regarding email addresses.

**Comment by alexweissman** [comment]
This project might be worth checking out: https://github.com/mailcheck/mailcheck

**Comment by alexweissman** [comment]
I agree, we need consistent client- and server-side rules.  I've opened an issue in `fortress`, which is where this needs to be resolved.

**Comment by spurgeonbj** [comment]
Hi, 

Greetings!

I'd like to suggest having an optional mail domain check with a DNS MX record lookup for a given email id, that is being validated.

As numerous are the domains, IMHO, it would be ideal to have MX record lookup, which confirms the availability of the mail domain (of course, confirming the validity of user account in that mail domain is left to response to activation mails) than whitelisting domains in today's growing world of domains.

For your kind consideration please.

Is it possible to have a custom function invoked in fortress? 

Thanks!
warm regards
Spurgeon

**Comment by alexweissman** [comment]
Does jQueryvalidation have a custom rule that lets us perform checks against data from external urls?  Otherwise, this could be tricky to do on the client side.

**Comment by spurgeonbj** [comment]
I think so - https://jqueryvalidation.org/remote-method/

**Comment by alexweissman** [comment]
Do you want to take a crack at this?  Basically, you would first want to implement the MX lookup logic as a new rule (perhaps using `curl`) in [ServerSideValidator](https://github.com/userfrosting/fortress/blob/master/Fortress/ServerSideValidator.php).  You could also ask around on [valitron](https://github.com/vlucas/valitron) if they would want to add it as a rule, or accept a PR from you if you want to implement it there.

Then you'd create a new rule `email_lookup` for Fortress, and then create appropriate transformations for both client- and server-side targets.

Also, we should probably move this to a separate issue, within [fortress](https://github.com/userfrosting/fortress/issues).

**Comment by spurgeonbj** [comment]
Sure! Will try it out this.

had used this chunk of code (from the net) in a project.

function domain_exists($email, $record = 'MX') {
    list($user, $domain) = split('@', $email);
    return checkdnsrr($domain, $record);

fortunately, checkdnssrr is a native php function (
http://php.net/manual/en/function.checkdnsrr.php) so curl is not required.

While i may be able to tweak the php files, am new to github / forking
/commit / PR etc. so might need your help... :-)

Thanks!

**Comment by spurgeonbj** [comment]
Hi.

Have tried this in Valitron\Validator.php validateEmail() and works!

    /**
     * Validate that a field is a valid e-mail address
     *
     * @param  string $field
     * @param  mixed  $value
     * @return bool
     */
    protected function validateEmail($field, $value) {
        // validate email pattern and domain
        list($user, $domain) = split('@', $value);
        return (checkdnsrr($domain, 'MX') && (filter_var($value,
\FILTER_VALIDATE_EMAIL) !== false) );
    }

**Comment by alexweissman** [comment]
Nice!  I would probably break this up into two separate rules: `validateEmail` and `validateEmailDNS`.

It would probably be best to talk about git and Github work flows in [chat](https://chat.userfrosting.com).  If you want to contribute this directly to Valitron, I would first open an issue over there, and mention that you've already successfully implemented it and would like to do a PR.

**Comment by spurgeonbj** [comment]
Hi Alex,

 Thanks a ton!

Kindly feel free to you implement as you deem fit in fortress.

IMHO, considering email as an entity, a validatedEmail  like
'username@blahblahblah.tomdickandharry' (based on regex pattern) would
still be an invalid email in the real world without its valid mail server
domain that is non existant. So, it might be worthwhile to consider
including as the complete validation part of email. May be we can have a
flag to invoke this additional check within  the same rule.

Regarding valitron, I had posted an issue -
https://github.com/vlucas/valitron/issues/159

Thanks for the kind help. Sure, will check out chat for github workflow.

God bless you!

**Comment by alexweissman** [comment]
This issue can be discussed further in the `userfrosting/fortress` issue tracker.
