### ISSUE TITLE
Issue recognising master user using Ubuntu and PHP 5.5.9-1

### ISSUE THREAD

**Issue by padders** [userfrosting/UserFrosting#469]
It looks like there are comparator issues with UserFrosting when using Ubuntu, Apache, MySQL and PHP at the versions below.

Ubuntu - 14.04.3 LTS
Apache - 2.4.7
PHP - 5.5.9-1
MySQL - 5.5.46-0

On first install, the master user account is created but isn't recognised and is logged on as a standard user, without any special access privileges. You can logon as the root user correctly by editing the Users.php file linked below

https://github.com/userfrosting/UserFrosting/blob/8310c13890530f0eb75f13e104fff2fad61315c9/userfrosting/models/database/User.php#L315

change line 315 from 

`else if ($this->id === static::$app->config('user_id_master'))`

to this:

`else if ($this->id == static::$app->config('user_id_master'))`

This allows the user to be logged on correctly as the master user. 

Note that I still can't see all pages I'd expect to after doing this, but I suspect my install may not be working entirely correctly. I'll probably scrub the lot and start again with that fix in place to see what happens.

**Comment by alexweissman** [comment]
Yes, actually that strict comparison happens in a couple pleases.  So, you probably just didn't change it in all places.

The problem is that some environments (Ubuntu) use a PDO driver that casts `int` columns to strings.  So, the `user.id` is getting cast to a string, and then failing the strict comparison.  See

http://stackoverflow.com/questions/5323146/mysql-integer-field-is-returned-as-string-in-php#comment41836471_5323169

**Comment by padders** [comment]
Hi Alex, 

Yeah I can confirm that updating all the instances of `===` to `==` in User.php fixes the issue with the master user.

I can see quite a few instances of `===` in other files in the UserFrosting directory. Should they all be changed or is it specific to just this instance where `user.id` is getting converted to a string?

Thanks again for the help :)

**Comment by alexweissman** [comment]
v0.3.1.9 (pushed last night) switches back all the necessary comparisons.  So, just pull that latest version and you'll be fine.

**Comment by padders** [comment]
Cool, is it best to do a fresh install or can the previous one be overwritten?

**Comment by alexweissman** [comment]
you shouldn't need to re-create the database, if that's what you mean.  If you have already started modifying the code, you can use `git merge`.  Otherwise, just replace the code.
