### ISSUE TITLE
hooks. naming convention and locations

### ISSUE THREAD

**Issue by frostbitten** [userfrosting/UserFrosting#472]
We have the ability to use hooks but there are not so many included by default.

1) How should the naming convention look?
2) Where/what are we going to hook?

Here are some current lists of hooks from other applications for reference:
[wordpress](https://codex.wordpress.org/Plugin_API/Action_Reference)
[drupal](https://api.drupal.org/api/drupal/core%21core.api.php/group/hooks/8)

My 2 cents on naming convention"
`(namespace nickname).(file or class name).(function name).(action)`

so we might see something like:
`UF.AccountController.login.success`
or
`UF.myPlugin.StuffController.justDoIt.init`

As for where to put them: I would suggest places where people are most likely to have modified the base code. For me it would be at the end of the registration function and start of the login function. Possibly best to put an init and a success/complete hook into the core functions.

**Comment by alexweissman** [comment]
Hey, that's actually a really elegant solution!

I would also say that, so we don't have to explicitly apply `before` and `after` hooks in every route, we should use middleware to automatically run hooks that are named according to [route names](http://docs.slimframework.com/routing/names/).

So first, we could just give names to all our routes (which would be useful anyway).  Then, we just make a convention that you can hook into the beginning of a route with `route.<route-name>.before` and the end of a route with `route.<route-name>.after`.

Our custom middleware can then apply these hooks based on the current matched route:
```
$app->applyHook('route.' + $currentRouteName + '.before');
and $app->applyHook('route.' + $currentRouteName + '.after');
```

**Comment by alexweissman** [comment]
Closing this since we're probably not going to be using hooks (event dispatching) as a major feature in v4.  If it is really needed, perhaps we can integrate Laravel's [Event Manager](https://laravel.com/docs/5.2/events).
