### ISSUE TITLE
Status/Action always Active

### ISSUE THREAD

**Issue by fv3rdugo** [userfrosting/UserFrosting#473]
In version 0.3.1 in the user area you see always Active status although status is Disabled or Unactivated. If you change the status this changes are applied in the database but you can't see.
thanks!

**Comment by alexweissman** [comment]
Is this a fresh install of 0.3.1, or are you upgrading from 0.3.0?

**Comment by fv3rdugo** [comment]
Fresh install of 0.3.1

**Comment by alexweissman** [comment]
So, are you talking about in the "Users" page?

![screen shot 2015-12-07 at 1 00 01 pm](https://cloud.githubusercontent.com/assets/5004534/11635095/7c5d0e66-9ce2-11e5-8cc1-77d53b3dfd40.png)

**Comment by fv3rdugo** [comment]
Yes, in this page.

**Comment by alexweissman** [comment]
What happens if you just view the raw JSON data from the user list API?  Go to `/public/api/users` and show me what you see.

**Comment by fv3rdugo** [comment]
Are the same results that I can see in database.

{
    "count": 3,
    "rows": [
        {
            "id": "4",
            "user_name": "admin",
            "display_name": "admin",
            "email": "xxxxx@gmail.com",
            "title": "New User",
            "locale": "en_US",
            "primary_group_id": "1",
            "flag_verified": "1",
            "flag_enabled": "0",
            "flag_password_reset": "1",
            "created_at": "2015-12-07 13:12:16",
            "updated_at": "2015-12-07 13:13:36",
            "last_sign_in_time": 0,
            "sign_up_time": "2015-12-07 19:12:16"
        },
        {
            "id": "2",
            "user_name": "pepe",
            "display_name": "pepe",
            "email": "pepe@xxxxx.com",
            "title": "New User",
            "locale": "en_US",
            "primary_group_id": "1",
            "flag_verified": "0",
            "flag_enabled": "0",
            "flag_password_reset": "0",
            "created_at": "2015-12-06 17:25:06",
            "updated_at": "2015-12-07 12:08:23",
            "last_sign_in_time": 0,
            "sign_up_time": "2015-12-06 23:25:06"
        },
        {
            "id": "1",
            "user_name": "root",
            "display_name": "master",
            "email": "xxxx@gmail.com",
            "title": "New User",
            "locale": "en_US",
            "primary_group_id": "1",
            "flag_verified": "1",
            "flag_enabled": "1",
            "flag_password_reset": "0",
            "created_at": "2015-12-06 17:24:11",
            "updated_at": "2015-12-06 17:24:11",
            "last_sign_in_time": "2015-12-07 18:17:31",
            "sign_up_time": "2015-12-06 23:24:12"
        }
    ],
    "count_filtered": 3
}

**Comment by alexweissman** [comment]
That's a good sign.  So, the buttons in each user row always display as "Active"?  What if you try a "hard refresh" of you browser?

**Comment by fv3rdugo** [comment]
Yes, always "Active". I try with some browsers (Firefox & Chrome) and various fresh installations.

**Comment by alexweissman** [comment]
It could be some quirk of your server, then.  Do you have any special server-side caching set up?  Are you using `mod_pagespeed` or something like that?

**Comment by fv3rdugo** [comment]
Default apache config, only php, mysql, rewrite modules enabled.
For example, when you edit a /user/u/2 and click disable button works properly, you can see then the enable button, but in the /users page there is no changes. Thanks for your help, I will try to solve this, if I do I will post it here.

**Comment by emrecaga** [comment]
I had a similar experience.
The reason for that problem was browser's cache.
You can see the solution here,
http://stackoverflow.com/questions/11082111/prevent-caching-of-pages-in-internet-explorer-8
I hope it will be helpful for your problem too.

**Comment by fv3rdugo** [comment]
I tried this in Firefox and Chrome without any luck. Thanks anyway!

**Comment by fv3rdugo** [comment]
Finally I have the solution. In Ubuntu or Debian server I had installed php5-mysql package, I have changed to php5-mysqlnd (native driver) and boilà it rocks!

**Comment by alexweissman** [comment]
Hmm, interesting - could you elaborate?  Is this a typing (string vs int) issue?

**Comment by fv3rdugo** [comment]
[Here](http://dev.mysql.com/downloads/connector/php-mysqlnd/) more information about MySQL native driver for PHP. See Feature comparison Table [here](http://dev.mysql.com/doc/apis-php/en/apis-php-mysqlinfo.api.choosing.html).
Sorry, maybe I say a nonsense but I see than in *user-info-form.twig* you use **data-id="{{target_user.id}}"** and in *users.twig* you use **data-id="{{user.id}}"**, I don't know, it's better for me to spend more time but for now it's impossible, and it's works definitely!

**Comment by alexweissman** [comment]
Alright, yeah this is a strange issue and even stranger resolution.  The only issue I can see with `data-id="{{user.id}}"` is that `user` refers to the currently logged-in user in the global scope, but to an arbitrary user in the scope of that Twig loop.  

But, I can't possibly see what that would have to do with the chosen MySQL driver.

**Comment by Aterbonus** [comment]
I have the same problem and I think I found something.

Some servers returns json velues (Like flag_enabled) as string and others as int (I know this because I have the same issue in production and not in dev, so debugging time).

The table of users now uses handlebars, in [the template](https://github.com/userfrosting/UserFrosting/blob/master/userfrosting/templates/themes/default/components/common/js-snippets/user-table-columns.twig) of the table we have things like this:

```html
{{#ifCond user.flag_enabled 0 }}
     <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
            Disabled
            <span class="caret"></span>
    </button>
{{ else }}
    {{#ifCond user.flag_verified 0 }}
        <button type="button" class="btn btn-warning dropdown-toggle" data-toggle="dropdown">
            Unactivated
            <span class="caret"></span>
        </button>            
    {{ else }}
        <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
            Active
            <span class="caret"></span>
        </button>            
    {{/ifCond }}
{{/ifCond }}
```

In the [definition of ifCond](https://github.com/userfrosting/UserFrosting/blob/master/public/js/userfrosting.js#L47-L52):
```javascript
Handlebars.registerHelper('ifCond', function(v1, v2, options) {
  if(v1 === v2) {
    return options.fn(this);
  }
  return options.inverse(this);
});
```

So 0 === "0" evaluates to false and the disabled user is active for the template.

**Comment by alexweissman** [comment]
Ah ha!  Thanks for catching this.  I don't remember why I used strict comparison originally - what happens when you change it to `==`?

**Comment by Aterbonus** [comment]
I'm at it. Apparently nothing happens. I will try to find a solution to this issue.

**Comment by alexweissman** [comment]
Thanks!  Feel free to join us in [chat](https://gitter.im/userfrosting/UserFrosting) if you want to discuss more.
