### ISSUE TITLE
Non file public/css/theme.css & public/js/config.js

### ISSUE THREAD

**Issue by 4val0v** [userfrosting/UserFrosting#474]
http://domain.loc/public/css/theme.css?user=1
Failed to load resource: the server responded with a status of 404 (Not Found)

http://domain.loc/public/js/config.js
Failed to load resource: the server responded with a status of 404 (Not Found)

http://domain.loc/public/css/theme.css?user=1
Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by alexweissman** [comment]
So, these aren't actual files - they are dynamically generated responses as seen here: https://github.com/userfrosting/UserFrosting/blob/master/public/index.php#L402-L412

What server/platform are you using?  This is usually a configuration issue.

**Comment by 4val0v** [comment]
@alexweissman Open Server
Apache-2.4+Ngingx-1.9
PHP-5.6
MySQL-5.6

**Comment by fv3rdugo** [comment]
I comment you my problem with php5-mysql vs php5-mysqlnd, maybe is the same issue.

**Comment by alexweissman** [comment]
@4val0v so, are you serving over Apache or nginx?

**Comment by Entrio** [comment]
I have same issue. I am using nginx to server all my files

**Comment by alexweissman** [comment]
@Entrio is it just those URLs, or all URLs?  Have you looked at #373?

**Comment by Entrio** [comment]
@alexweissman Thanks, that did the trick for me. Now to solve the 400 error

**Comment by St1c** [comment]
I have the same problem, but using apache. Does anybody know solution?

**Comment by alexweissman** [comment]
We'll be using a different system for serving dynamically created assets in the next version of UF.  So, this should not be an issue going forward.
@St1c, please join us in chat if you're still having problems.
