### ISSUE TITLE
formUserView and formGroupView are not defined on corresponding controllers

### ISSUE THREAD

**Issue by ianschmitz** [userfrosting/UserFrosting#478]
At endpoints `/forms/groups/g/:group_id/?` and `/forms/users/u/:user_id/?`there appears to be the options to have a 'view' mode for the form. However the call `return $controller->formUserView($user_id);` fails as they are not defined on the `UserController` and `GroupController`.

Example error: 
`Call to undefined method UserFrosting\UserController::formUserView()`

**Comment by alexweissman** [comment]
Hmm, you're right.  I wonder where that came from?  

The static `/forms/users/u/:user_id/` route does indeed correctly render the "view" mode of the form, but I also see that the corresponding `formUserView` method appears to be missing.  So, I wonder why it is still working...

**Comment by alexweissman** [comment]
This appears to be the same situation for groups, where `formGroupView` does not exist.

**Comment by alexweissman** [comment]
Let's just clear these out in the next hotfix.
