### ISSUE TITLE
composer is running but 

### ISSUE THREAD

**Issue by 9tontruck** [userfrosting/UserFrosting#483]
Hi,

I use Wamp in my Win 10 computer and trying to install UserFrosting but I keep having this error:

"Using twig_autoloader is deprecated. Use composer instead" in Autoloader.php line 30.

rewrite mod and opensl are up and running. I don't know why I keep having this error. Would any1 give me soem tips to fix this error?

**Comment by 9tontruck** [comment]
Am I the only one who failed installing UserFrosting? I keep having error:
"Using twig_autoloader is deprecated. Use composer instead" in Autoloader.php line 30.
Please help!

**Comment by frostbitten** [comment]
Did you modify any of the files after downloading besides the config? UF should work right out of the box, once you config it. If you haven't created any new controllers or models, you don't need composer at this stage. Also, are there any other lines to that error?

**Comment by alexweissman** [comment]
It sounds like this is a run-time error being generated by Twig.

**Comment by alexweissman** [comment]
Apparently Twig has its own built-in autoloader for finding templates: http://twig.sensiolabs.org/doc/intro.html#basic-api-usage

**Comment by 9tontruck** [comment]
Thank you Matthew and Alex, it was my fault. I have made some changes on the files and that was the reason. Fresh UserFrosting files solved the problem. Sorry for confusion. Thank you!
