### ISSUE TITLE
Configuration parameters should be separated from the Slim application initialization

### ISSUE THREAD

**Issue by alexweissman** [userfrosting/UserFrosting#486]
Sometimes, we want to use a common set of configuration values across multiple web applications.  For example, you might have a [Grav](http://getgrav.org) blog with a UF backend, and you want them both to be able to access the `config('css.path')` value in the UF config file.

Currently, you'd have to initialize the Slim app before you can access these configuration values.  So, even if you have a component of your website that doesn't actually use Slim, you still waste time initializing it to get at the config.

I propose that we move configuration values to a plain PHP array, then initialize Slim with that array in `initialize.php`.

**Comment by Netrilix** [comment]
So basically what we need is the exact array currently being passed to Slim to be recreated in such a way that it's identical to the existing one, but also easy to parse by non-PHP programs. Since the array is currently multidimensional, we'll probably need to have a plain array in `config-userfrosting.php` that is then translated into the multidimensional one in `initialize.php` (whereas currently it's already multidimensional in `config-userfrosting.php` - very difficult to parse with another language).

**Comment by frostbitten** [comment]
in regards to parsing the multidimensional array in another language, laravel's collections [has the ability to flatten arrays](https://laravel.com/docs/5.0/helpers#arrays) so we could pull that library in if we wanted to keep it multidimensional

```
$array = ['name' => 'Joe', 'languages' => ['PHP', 'Ruby']];

$array = array_flatten($array);

// ['Joe', 'PHP', 'Ruby'];
```

**Comment by r3wt** [comment]
I was here about 2 years ago. if you have the humility to listen to me and skip a step, you should go directly to an array singleton approach. msg me and i will give you the code. an array singelton is a special class that has array access, and is retrievable via `getInstance()`. obviously this can be very advantageous for a config file. you construct once and require it anywhere and it just works.

**Comment by alexweissman** [comment]
I'm not completely satisfied with either of the proposed solutions here, to be honest.  

@r3wt , the problem with introducing a special singleton class is that your configuration now has an extra dependency.  Sure, it's not as bad as having to initialize the Slim instance, but it still means we have to make sure that the class is included throughout the external application.  And actually, in that case we might as well just stick with Slim, which already implements the `getInstance()` method.

@Netrilix, I'm worried that your approach will be difficult to extend.  What if we want to add another sub-array to the configuration parameters?  Like you said, the translation code will have to be changed in that case.

The more I think about it, maybe storing configuration info in a `.yml` file is the way to go.  Major frameworks like [Ruby on Rails](http://edgeguides.rubyonrails.org/configuring.html#configuring-a-mysql-database) and [Symfony](http://symfony.com/legacy/doc/reference/1_3/en/07-Databases) (though not Laravel, strangely) use `.yml`.  We could add a rule to `.htaccess` that explicitly forbids viewing the configuration file (or perhaps the contents of an entire `config` directory).

**Comment by Netrilix** [comment]
In that case, could we generate the config in the installer?

That way, if `.htaccess` isn't working, the `config.yml` never gets created (because the installer route won't work), and there's no data leaking.

If the `.htaccess` is working properly, the `config.yml` will be generated and after that it'll be the same as shipping with the config in place.

**Comment by alexweissman** [comment]
Ooh, that's an idea.  So, kind of the way that Wordpress provides an interface for generating their `wp-config.php` file?

**Comment by Netrilix** [comment]
I haven't used Wordpress in years, but does it basically ask for site title, database details, etc?

**Comment by alexweissman** [comment]
I think the installer just asks for the DB details so it can create the tables, then everything else is handled through their dashboard.

**Comment by Netrilix** [comment]
Yeah, that makes sense. Sounds like a perfect solution to me. I think it fits all of the criteria we had at the beginning (can read with external program, is secure, is easily extendable).

**Comment by alexweissman** [comment]
The only main issue will be getting people to change their permissions correctly for write access.

**Comment by alexweissman** [comment]
We should also make it easy to override/extend different configuration arrays.  Multisite configurations, or just simply development vs production configurations, will become a lot DRYer and easier to handle if we can declare a generic base configuration that can be overridden for various purposes.

**Comment by alexweissman** [comment]
What if we design the [`config` module](https://github.com/userfrosting/config) to read PHP *or* YAML config files?  By default, UF will ship with PHP-based config, but we'll make it easy to load config from a `.yml` instead.  We could consider adding other formats as well, like JSON.

**Comment by alexweissman** [comment]
For now, config files are simple PHP arrays.  We can come back to options for JSON or YAML in future versions.
