### ISSUE TITLE
Adapter to reconcile conflicts between UF and Grav configs

### ISSUE THREAD

**Issue by Netrilix** [userfrosting/UserFrosting#489]
[Note: This likely can't be accomplished until we have the hook from #488 in place]

Because UF and Grav share some Twig global setting names, we need an adapter plugin that can read settings from Grav, decide which settings need to overwrite UF settings, and pass the updated settings to UF.

In the case of `site`, the setting is actually a whole array, so the arrays will probably have to be merged and conflicting values handled in some way.

**Comment by alexweissman** [comment]
I'll be working on this soon, as I have a site that I need to upgrade to UF4 that shares some content with a Grav blog.

**Comment by alexweissman** [comment]
So, one thing that immediately stands out in UF4 is a conflict between UF and Grav's custom stream wrappers.

Basically, both Grav and UF try to declare the same custom stream wrappers for:
- `log://`
- `cache://`

So, this conflict ends up causing a problem if you try to initialize the `SprinkleManager` (which depends on these streams).

Of course, you can still just instantiate the individual UF classes that you need inside Grav without using the SprinkleManager, but I'm not sure if this is always going to be so convenient.

![Don't cross the streams](http://i.giphy.com/1lhBT2cZHJVPq.gif)

**Comment by alexweissman** [comment]
Alright, I think I've solved this.  Check out https://github.com/userfrosting/grav-plugin-uf-adapter.  It's a Grav plugin that imports config settings, templates, and the UF asset manager from a UF installation.
