### ISSUE TITLE
UserFrosting nginx

### ISSUE THREAD

**Issue by crisdany6** [userfrosting/UserFrosting#490]
I installed UserFrosting Version: 0.1 on the server that runs plesk and nginx
does not work !
there the posibility that works?
.......................................................................................................................

sorry I do not speak Inglese (Google translated)
Regards

**Comment by alexweissman** [comment]
Is there a reason you're trying to use 0.1 versions?  At this point, they are very outdated, no longer supported, and just generally bad coding practices.

**Comment by crisdany6** [comment]
in the past I have made some changes, and now and difficult to upgrade

**Comment by alexweissman** [comment]
Can you provide some more details other than "it doesn't work?"  For example, anything in the PHP error log, or server logs, would be helpful.

**Comment by crisdany6** [comment]
I have this message:
Server Error

500

It was an error in the website while getting http://qqqqqq.it/register.php. May not be available for maintenance or configured incorrectly.

**Comment by r3wt** [comment]
@crisdany6 i don't think we're going to fix this, simply for the fact that this has to do with an old and unsupported version of UserFrosting, and in that case the setup for a PHP website on Nginx is remarkably non trivial. I would suggest you read up on configuring NGINX and PHP properly, and then ensuring you have a working database configuration and PHP configuration that supports the required features of that old version of UF.

**Comment by Netrilix** [comment]
As a side note, the version numbering in our changelog was recently discovered to be incorrect. If it does turn out you're actually on 0.3.x and not 0.1, please let us know. The problem is, 0.1 is so old that many of us have never even used it, much less tried to help support it.
