### ISSUE TITLE
Handlebar.js variable documentation?

### ISSUE THREAD

**Issue by Endroe** [userfrosting/UserFrosting#491]
Could someone please make a documention for variables such as `{{user.user_name}}`. I'm happy to help with the list too.

**Update**
_Just a stub for now, I'll finish it later_
Here's a list of the variables I could find:
- `{{user.id}}` - The user ID, e.g. `1`.
- `{{user.user_name}}` - The user name, e.g. `andrew`.
- `{{user.display_name}}` - The user display name, e.g `Andrew`.
- `{{user.email}}` - The user email, e.g. `john@doe.com`.
- `{{user.title}}` - The user title, e.g. `Trancemaster`.

**Comment by r3wt** [comment]
Off topic, but why handlebars instead of Twig.js?


Sent from Outlook Mobile






On Sun, Jan 10, 2016 at 12:55 AM -0800, "Andrew Geddes" <notifications@github.com> wrote:





Could someone please make a documention for variables such as {{useruser_name}} I'm happy to help with the list too

---
Reply to this email directly or view it on GitHub:
https://github.com/userfrosting/UserFrosting/issues/491

**Comment by alexweissman** [comment]
Handlebars is by far more widely used than Twig.js.  @Editandrew , the variables you see in Handlebars templates (for example, this: https://github.com/userfrosting/UserFrosting/blob/master/userfrosting/templates/themes/default/components/common/js-snippets/user-table-columns.twig) are the same variables used in Twig.

So, maybe just in general we need to document the template variables?

**Comment by r3wt** [comment]
Ah ok. I wasn't aware that handlebars offered that degree of compatibility with Twig. I'll add as a note that Twig.js has been recently revived under new leadership and the performance is amazing. I've got a PR that will allow you to overload the XHR implementation, which will resolve the current problem with inline template includes. Its very likely that we will have 100% coverage with Twig very soon. coverage is already very high.

**Comment by Editandrew** [comment]
General template variables sounds great!

**Comment by alexweissman** [comment]
I do have to admit, the limitations of Handlebars is starting to frustrate me.  Let's look into this more for v4.

**Comment by alexweissman** [comment]
I've looked into this, but it seems like Handlebars might still be the best choice.  All the other options that I've looked into are one of:

- Not very popular or well-supported;
- Even less powerful than Handlebars;
- Part of a larger client-side framework that we aren't using.

**Comment by Endroe** [comment]
I would agree that Handlebars is the best option.

**Comment by alexweissman** [comment]
Alright, I think this (finally!) is fairly well-covered in v4 with these documentation sections:

- https://learn.userfrosting.com/client-side-code/exporting-variables
- https://learn.userfrosting.com/client-side-code/client-side-templating
