### ISSUE TITLE
Question about Authentication Control rules

### ISSUE THREAD

**Issue by 9tontruck** [userfrosting/UserFrosting#492]
Hi,

I am quite confused on the grammers of authentication control rules. 
I added 'uri_unpaid_user' / always()  in the group setting for "User" and added nothing in "Administrator" 
I thought this should make accounts in User should pass `checkAccess('uri_unpaid_user')` and administrator does not pass. But administrator still passes the check. 

What is the rule format that makes only User can pass the checkAccess?

And in Administrator group setting page, 
`delete_account` is `!in_group(user.id,2)`
Would you explain what this means? Please let me know if there is any detail tutorials about auth control rules for 0.3.1 

Thanks!

**Comment by Aterbonus** [comment]
Check if the administrator account is not the ROOT account. ROOT account is an special account. It has access to all the things. 

!in_group(user.id,2) checks that the user you want to delete is not in group with id = 2. That group is administrators by default, so it prevents administrators to delete other administrator account.

Check the [**AccessCondition**](https://github.com/userfrosting/UserFrosting/blob/master/userfrosting/models/auth/AccessCondition.php) Class for more info.
>This class contains static methods to be used in conditional clauses for authorization hooks.
>Here you may add your own methods for use in access hook conditional expressions.
>Every method of this class MUST be static and return a boolean value.

Maybe I'm outdated, so correct me if I'm wrong. (And sorry for my bad english, I speak spanish and I try my best).

**Comment by alexweissman** [comment]
yes, @Aterbonus is correct.  the root account is a special account that automatically has permission for everything, no matter what their group-level permissions are.  Are you testing with the root account, or some other Administrator account?

**Comment by Netrilix** [comment]
It should be noted that the root account should only be used when making back-end site changes. A normal administrator account should be used for anything else. You can read more about that here: #464

**Comment by 9tontruck** [comment]
Thank you! :+1:

**Comment by alexweissman** [comment]
Let us know if you still need help with this!
