### ISSUE TITLE
How can I remove fields in registration page?

### ISSUE THREAD

**Issue by 9tontruck** [userfrosting/UserFrosting#495]
Hi,

I tried to find similar questions but only questions I could find is about adding fields. 

I am trying to remove "username" and "display name" and let users login with their email address. If I can't not remove "username", I want to remove "display name" at least. Would you give me some tips for doing it please?

Thanks,

**Comment by alexweissman** [comment]
Any luck yet?  The process should essentially be the same as for adding fields, just done in reverse.
