### ISSUE TITLE
DataTables support?

### ISSUE THREAD

**Issue by malle-pietje** [userfrosting/UserFrosting#496]
Hi,
I'm starting to love UF after having gone through a steep learning curve and some difficult moments;-)
I'm starting off with a project where I have a large table (2M+ records) I need to allow the user to browse through. I've had a brief look at TableSorter but I have a preference for DataTables (https://datatables.net/). Does anybody have experience in combining these two? If so, maybe you have some hints on how to tackle this?
Thx!

**Comment by alexweissman** [comment]
I haven't used it, but it looks pretty nice and thank you for sharing it with us.
It looks like they provide all the necessary methods for interacting with our JSON API: http://datatables.net/reference/api/

So it should just be a matter of accessing the JSON API at the [appropriate URL](https://github.com/userfrosting/UserFrosting/blob/master/public/index.php#L359-L362) and providing the [appropriate parameters](https://github.com/userfrosting/UserFrosting/blob/master/userfrosting/controllers/ApiController.php#L37-L43).  

Hopefully the format that it returns will be compatible with DataTables and you won't need to change any server-side code.  If not, you might need to tinker around a bit in `controllers/ApiController.php`.

**Comment by malle-pietje** [comment]
Thanks for the feedback. Indeed looks as if it should not be too difficult but was hoping somebody had already tackled this;-) I will share some feedback when this works or report back with any questions that may pop up.

**Comment by malle-pietje** [comment]
I've had a better look at the specs on the DataTables side and I'm afraid I don't have the time in this project to implement it so I will go with TableSorter.

Looking at the pageUsers function in the UserController I can't seem to understand what's going on and how the GET vars are being processed; $paginate_server_side is true by default but then I don't see the $user_collection object created anywhere...

In the explanation here (http://www.userfrosting.com/navigating/#structure) I can understand "$users = UserLoader::fetchAll();", but how does the current version of this function work?

**Comment by malle-pietje** [comment]
My bad: I didn't realise you are using the api as ajax "source" for the users table:-/
Should be able to understand this now.

**Comment by alexweissman** [comment]
Ah, looks like there is some outdated code on that page.  Thanks for point it out, I will fix it.

**Comment by ssnukala** [comment]
I have written the datatables plugin, looking to clean up code and upload. Will try and get that uploaded in the next few days.

**Comment by malle-pietje** [comment]
that would be great! :-)
BTW, I've already had a quick look at https://github.com/yajra/laravel-datatables but have no idea how to integrate it into UserFrosting.

**Comment by alexweissman** [comment]
Ok, I have updated the "Navigating the Code" page: http://www.userfrosting.com/navigating/

**Comment by malle-pietje** [comment]
Thanks Alex!

**Comment by thomasspe** [comment]
I need to implement a similar thing and came across (jsGrid)[http://js-grid.com/]. It looks good and might just do what you want it to do. I'm everything but an expert but I hoped to get the data in there with ->toArray().... Once I got my own very basic problems sorted out, that is...

**Comment by malle-pietje** [comment]
Getting the data into single a json object using ajax is quite easy if you have a good look at the ApiController. My problem is I need server-side paging which complicates things; I can't pull 2M records in one go....

**Comment by alexweissman** [comment]
Actually, `ApiController` does server-side paging!  You can test that out with `/api/users?page=0&size=5`, for example.

**Comment by malle-pietje** [comment]
I did notice that, but it follows a different protocol than required by Datatables. And I kind of prefer Datatables implementation, look and feel and plugins over Tablesorter.;-)

**Comment by alexweissman** [comment]
Ah, I see.  It looks fairly similar though, just with different names (`start` and `length` vs `page` and `size`).  Usually, JS plugins like this have a preprocessing option that allow you to modify the ajax request before sending it.  Otherwise, I suppose you could just modify `ApiController` to use the variable names you need.

**Comment by malle-pietje** [comment]
creating a new function in the `ApiController` was also what I was thinking of. But before I do so I'm keen to see what @ssnukala has developed ;-)

**Comment by ssnukala** [comment]
Sorry for the delay. Been slammed. I wrote a separate controller as a plugin. Will clean up and post my code in the next few days

**Comment by malle-pietje** [comment]
no problem! Such support would be much appreciated, not only by me I guess;-)
