### ISSUE TITLE
No memory limit on reading a server's log file.

### ISSUE THREAD

**Issue by Netrilix** [userfrosting/UserFrosting#497]
Currently the log file is read entirely into memory, and then snipped to the last *x* lines before being returned. This results in a fatal error any time the log file is larger than PHP's allowed memory allocation.

A quick fix is to read it line-by-line into an array, and popping off the oldest one once the array has the number of lines we want. I'm not sure if there's a better way to read the last *x* lines.

The fatal line is here: https://github.com/userfrosting/UserFrosting/blob/161292fb9f57616cdadd44e667c12187a8b6f07f/userfrosting/models/database/SiteSettings.php#L410

**Comment by Netrilix** [comment]
As discussed in chat, we're going to use `fseek` to read backwards from the end of the file, just in case this code is still being used after we switch to Monolog. This will have much better performance than reading into an array as I mentioned above.

I'm also going to move the log reader into its own model, creatively called `LogReader`. This way, we can add any Monolog-specific code into this same model later without disrupting anything.

**Comment by alexweissman** [comment]
Sounds great!  I'm hoping we can start using Monolog in 0.3.2.

**Comment by alexweissman** [comment]
I've started integrating Monolog into 4.0, so I guess we'll address this at the same time?

**Comment by Netrilix** [comment]
I wrote a hotfix for it for this branch, since our master is technically broken without it, but yeah, the fix will be irrelevant once we switch to Monolog.

https://github.com/userfrosting/UserFrosting/commit/000b464c0026cc5fd10684c5fee75fe3c97e1e74

**Comment by alexweissman** [comment]
Merged.
