### ISSUE TITLE
Starttls auth

### ISSUE THREAD

**Issue by vetash** [userfrosting/UserFrosting#498]
My mail server is configured to auth with plaintext and starttls, after editing config file i can not send activation email to users.
Error that i see is : `Fatal error attempting mail, contact your server administrator`

**Comment by alexweissman** [comment]
In the config file, did you change `secure` to `tls`?  See https://github.com/userfrosting/UserFrosting/blob/1681374fea9e495c17e9beafca0f7da7cc7461e7/userfrosting/config-userfrosting-example.php#L54

**Comment by vetash** [comment]
Yes, i try to use tls in config file but unfortunately it's not help to me - same error is appears.

**Comment by alexweissman** [comment]
Is that error you're seeing, in the browser or in your PHP error log?

**Comment by vetash** [comment]
In browser, here is php log:
`[18-Jan-2016 01:55:43 Asia/Irkutsk] Mailer Error: <strong>SMTP Error: Could not authenticate.</strong><br />`
uf config:
```'mail' => 'smtp',
            'smtp'  => [
                'host' => '<my host>',
                'port' => 25,
                'auth' => true,
                'secure' => 'tls',
                'user' => '<login>@<my host>',
                'pass' => '<password>'
            ],
```

**Comment by vetash** [comment]
I trying to test with no security set, but find option for this. How to set secure to none?

**Comment by alexweissman** [comment]
Are you sure you're supposed to be using port 25?  Generally, the default port for TLS is 587.

**Comment by vetash** [comment]
Yes,  in thunderbird is set 25 and STARTTLS and all worked fine.

**Comment by alexweissman** [comment]
Oh, one other thing - are you trying to send from a different email address than the user you are authenticated as?  Many SMTP servers have this blocked by default.

**Comment by vetash** [comment]
No, in site setting Account Management Email is set same as in config.
I think my server setting up to use no secutity. Hot to set that option in `'secure' => '',` ?

**Comment by alexweissman** [comment]
`false`

**Comment by alexweissman** [comment]
Also, please note that we use [PHPMailer](https://github.com/PHPMailer/PHPMailer) as our mail package.  So, you might try searching/asking there if you're still stuck.

**Comment by vetash** [comment]
Seem like its problem on my mail server not UF or phpmailer.

**Comment by alexweissman** [comment]
Cool, glad you got it figured out.
