### ISSUE TITLE
How to configure and use Cache::remember method?

### ISSUE THREAD

**Issue by malle-pietje** [userfrosting/UserFrosting#499]
Can anybody provide me some hints on how to configure and use the database cache for using Cache::remember with queries? I'm still learning how to work with the UF namespace which is not so straightforward as I am not traditionally an OO programmer;-) Still learning....
https://laravel.com/docs/5.2/cache

**Comment by alexweissman** [comment]
Whoa, I didn't even know about this feature!  I haven't used it, but it looks cool.

The first thing you'll want to do is figure out which Laravel components you need to have installed to use `Cache`, and then add those to your `composer.json`.  Then it looks like you'll need to create a "store", which could be a database table, file, or memcache.  Unlike the example they provide, we don't use the `Schema` module, so you'll probably just end up creating the table manually.

Then, you'll have to set up Laravel's cache configuration, [which it looks like they provide in the main laravel repo](https://github.com/laravel/laravel/blob/master/config/cache.php).  You can probably use the Laravel DB connection defined in [initialize.php](https://github.com/userfrosting/UserFrosting/blob/master/userfrosting/initialize.php#L42-L51) if you decide to cache with a DB table.

Again, I haven't tried it, but that should get you started.  If you're able to get it working, please let us know, and consider sharing what you've learned on the [wiki](https://github.com/userfrosting/UserFrosting/wiki)!

**Comment by malle-pietje** [comment]
Thanks for the feedback and pointers! I will try to spend some time on this and report back.

**Comment by alexweissman** [comment]
Any news on this?  I've got a `cache` directory set up for v4.0, so it would be nice if we can start caching Eloquent, Twig, etc.

**Comment by lcharette** [comment]
This page contain useful information on how `Illuminate/Cache` can be used as standalone : https://laracasts.com/discuss/channels/general-discussion/illuminatecache-standalone?page=1

Cache will be available in V4 as a service for file and Memcached based caching. Files will be stored in the `cache/` folder Alex mentioned. I'M finishing the implementation in V4 as we speak.

**Comment by alexweissman** [comment]
Thanks!  Looks like the DB Cache is now available through the [`cache` service](https://github.com/userfrosting/UserFrosting/blob/b48f29eae3a62b235a00f982dbf9f80fd1c03c23/app/sprinkles/core/src/ServicesProvider/CoreServicesProvider.php#L100-L127).  It can be configured via the `cache` configuration key:

```
        'cache' => [
            'twig' => false,
            'illuminate' => [
                'default' => 'file',
        	    'prefix' => 'uf4',
        	    'stores' => [
                    'file' => [
                        'driver' => 'file'
                    ],
                    'memcached' => [
                        'driver' => 'memcached',
                        'servers' => [
                            [
                                'host' => '127.0.0.1',
                                'port' => 11211,
                                'weight' => 100
                            ]
                        ]
                    ]
                ]
            ]
        ],
```
