### ISSUE TITLE
Undefined variable: loggedInUser

### ISSUE THREAD

**Issue by chrismcquarrie** [userfrosting/UserFrosting#501]
I know in previous questions it was stated that I can access the current user id by using 
    $loggedInUser->user_id;

So I have created a new controller which works fine. But when I try to use $loggedInUser->user_id; the error log shows Undefined variable: loggedInUser.

I am quite new to PHP so I am wondering what I am missing? Do I need to include another file somehow? I have searched through the code and I don't see loggedInUser defined anywhere.

Any help is appreciated,

Thank you.

**Comment by alexweissman** [comment]
@chrismcquarrie , that is the old syntax.  You can now access the currently logged-in user via:
`$app->user`.

So to get the id, you'd do `$app->user->id`, to get the email you'd do `$app->user->email`, etc.

In Twig, the `user` object is already a global Twig object - so all you need to do in Twig is `{{ user.id }}`.

**Comment by chrismcquarrie** [comment]
Amazing! That worked, thank you for the quick reply!

**Comment by alexweissman** [comment]
Glad we could help!
