### ISSUE TITLE
How can I get the user list to be public?

### ISSUE THREAD

**Issue by AnthonyColduck** [userfrosting/UserFrosting#502]
Hey Everyone,

I have sucessfully created a page called members.twig and editing everything and the page can be viewed but the public (without being logged in).

So then i copied the users table and edit it so it only like user names and full names visable then i refrest the page and the table is visable however non of the users currently in the database are showing is this a matter of editing the controllers ?

**Comment by alexweissman** [comment]
If you're fetching the users via the JSON API, you'll need to make the corresponding API controller public as well: https://github.com/userfrosting/UserFrosting/blob/master/userfrosting/controllers/ApiController.php#L62-L64

**Comment by AnthonyColduck** [comment]
Would it be a simple as just adding an edited extra
      
   if (!$this->_app->user->checkAccess()){
                $this->_app->notFound();
            }
        }

**Comment by malle-pietje** [comment]
or even better, make a new (url) route to the api function in index.php and leave out the checkaccess(). That way you can keep track of your modifications and maybe even make a modified copy of the function being called in the APIController to change the user fields you are exposing through the new api url...

**Comment by alexweissman** [comment]
Please let us know if you're still having trouble with this.
