### ISSUE TITLE
Better asset manager needed

### ISSUE THREAD

**Issue by Netrilix** [userfrosting/UserFrosting#504]
As shown in #503, we need an asset manager to handle `.js` and `.css` files properly.

Since @frostbitten is currently working on researching the asset manager, I'm going to do a temporary hotfix in #503, and then we can solve the deeper issue at a later date.

**Comment by alexweissman** [comment]
Technically, our `PageSchema` class already acts as a very basic asset manager.  What we need is a *better* asset manager, preferably a third-party package that is [already widely used](https://github.com/kriswallsmith/assetic) and actively maintained.

Another option is to manage client-side assets with tools like Bower and Grunt, as discussed in #406.  This seems like the more "correct" way to do things, but this would also introduce a host of new dependencies and technologies.  

I would like to see the code designed such that it is easy to choose either option.

**Comment by alexweissman** [comment]
It seems like pure PHP-based solutions such as Assetic have some issues and are generally being abandoned in favor of Node.js solutions like Grunt or Gulp.  Annoying names aside, maybe this is the way to go after all?

**Comment by alexweissman** [comment]
Something like this might be a good approach: http://knpuniversity.com/screencast/gulp/version-cache-busting

Basically, Gulp can generate "manifest files" (so, now we're kind of heading back to the way I was trying to do things just before we released 0.3.0).  PHP can read these manifest files and use them to determine the `<link>` and `<script>` tags to generate.

I found this nice module that might be able to do the work of the "page groups" that we have currently: https://github.com/dowjones/gulp-bundle-assets

Yes, `dowjones` is *the* Dow Jones...

**Comment by alexweissman** [comment]
OK, we're going with `gulp-bundle-assets`.  I have created a package that can automagically generate asset tags from its input and output schema: https://github.com/userfrosting/assets

This means we can let Node.js/Gulp do the heavy lifting of compiling assets, rewriting relative paths in CSS files, etc.  `UserFrosting/Assets` will just provide a simple interface for including the assets (raw or compiled) in Twig templates.  It will effectively replace `PageSchema`.

**Comment by alexweissman** [comment]
This is mostly implemented in `dev` (see #560 for further discussion).
