### ISSUE TITLE
Multiple AJAX calls executed in parallel?

### ISSUE THREAD

**Issue by malle-pietje** [userfrosting/UserFrosting#508]
For my project where I am using UF, the main page is a dashboard which displays data pulled from muliple AJAX sources/routes. These are being fed from functions in the ApiController and it all works great. What I appear to be seeing though, is that the database queries are being executed sequentially slowing down the results flowing into the page.
Is this caused by the session handler and is there a way to enable execution in parallel of the json feeds?

**Comment by alexweissman** [comment]
How are you structuring the AJAX calls on the client side?  Are you nesting the callbacks or something?

**Comment by malle-pietje** [comment]
on the dashboard page I am making 9 ajax calls like so:
` $.ajax({
            url: "{{site.uri.public}}/api/xxxxxx/" + myStart + "/" + myEnd + "/",
            type: "GET",
            dataType: "json",
            success: onxxxxxxDataReceived
        });`
of which two are "coupled" together with `promise`, as the results from these two need to be combined (also display delta between the two results). The other 7 ajax calls each have their own callback functions (like the example above).
Each ajax call is made to it's own route in index.php with parameters (like above example) or without parameters. Each of these routes call a different function in the ApiController.

My observation is that the order in which the results come into the page is random, so I assume there's no particular order in the sequential loading of data returned by the ajax calls.

**Comment by alexweissman** [comment]
It sounds like you've got the right idea then, using promises when you have dependencies among AJAX calls, and otherwise letting them load asynchronously.  So, they should already be loading "in parallel" - i.e., your browser should be firing off those requests and then moving on to the next one without waiting for the response.

**Comment by r3wt** [comment]
@malle-pietje what type of setup are you running on the server? (PHP Version, Web Server, MySQL Version, etc)

**Comment by malle-pietje** [comment]
PHP is version 5.6.1, apache 2.4.10 and MySQL 5.6.17. Nothing special, I do notice however, that mysql never uses more than 1-2 cores on my octa-core server...

**Comment by r3wt** [comment]
@malle-pietje i can't speak for others, but personally i use Maria DB 10.1 the advantage is that it comes with sane performance tuning out of the box. I also recommend HHVM over PHP5 (or PHP7, i hear its stable now and quite fast) if you have the stomach for making it work. Replacing Apache with NGINX is something i'd also recommend.

**Comment by malle-pietje** [comment]
thanks for the suggestions: assuming each of these choices has limited performance advantages (10's of % in performance improvement) I will dive into this when I have more time available;-)

**Comment by malle-pietje** [comment]
Brief feedback for those interested: instead of running multiple queries against a large table (4M rows and counting) I decided to implement summary tables (also called aggregated tables or materialized views in MySQL) for all slow queries. The summary tables are updated periodically, the interval depends on the nature of the statistics. I created the respective models for each summary table and can now use the normal query builder features against them, making coding easier and better readable code (no complex SQL queries). The overall load time of the dashboard page using these queries has now improved by a factor of more than 25 (from 55 seconds down to approx 2 seconds).

**Comment by alexweissman** [comment]
That's really cool.  Are the summary tables handled automatically by MySQL, or did you need to set up a cron job to have them update periodically?

**Comment by malle-pietje** [comment]
Because there are several other actions that needed to occur periodically besides the summary tables update, I chose to use a PHP script which is called by cron. Later on I might change this, but for now it does the trick;-)

**Comment by alexweissman** [comment]
Ah, ok.  Yeah, summary tables seem like a good approach when you need to access aggregates often (which I actually do in my business' backend).  For simplicity's sake, I'm hesitant to build it into the UF core architecture.  

But...any interest in creating a plugin for this functionality?

**Comment by malle-pietje** [comment]
I'll have a think about that; the challenge could be that, much like in my case, the original stats queries are almost impossible to implement using the query builder. Therefore you need to do complete raw queries using a PDO connection provided by UF. Putting that into structured code might be difficult. I might consider writing a brief summary of my approach and put it on the Wiki, that way others can save themselves some time.

**Comment by alexweissman** [comment]
Actually, Eloquent supports raw queries too!  https://laravel.com/docs/5.1/database#running-queries

**Comment by malle-pietje** [comment]
I saw that but I just ended up doing this:
```php
        $weekDaysQuery = new ProbeRequest;
        $db = $weekDaysQuery->getConnection()->getPdo();
        $thisWeekVisitors = $db->prepare("SOME COMPLEX QUERY HERE");
       etc..
```
