### ISSUE TITLE
Deleted and disabled accounts throw a 500 error with no explanation to user

### ISSUE THREAD

**Issue by Netrilix** [userfrosting/UserFrosting#510]
[This code](https://github.com/userfrosting/UserFrosting/blob/1681374fea9e495c17e9beafca0f7da7cc7461e7/userfrosting/models/UserFrosting.php#L82-L85) needs to be rewritten to throw a nice translated error to the end user.

Proposed fix prototype:
```php
if ($e instanceof AccountInvalidException) {
    $this->alerts->addMessageTranslated('danger','ACCOUNT_INVALID');
    $this->logout(false);
    $this->redirect('/'); // This needs to include bath path in the final version
}
```

New translation messages will need to be added for ACCOUNT_INVALID and ACCOUNT_DISABLED.

**Comment by alexweissman** [comment]
What do they see right now?  WSOD?
