### ISSUE TITLE
Demystifying the CSRF token bug

### ISSUE THREAD

**Issue by alexweissman** [userfrosting/UserFrosting#513]
We see a lot of problems in chat where developers have a problem with form submission due to a CSRF token error.  Sometimes, they get the "Invalid/Missing CSRF token" message, but often they just get a `400` error with no further explanation.

The problem is usually one of the following:

A. They are trying to submit a form the old-fashioned (non-AJAX) way, and aren't including the CSRF token as a hidden field in their form;
B. They are trying to submit a form with AJAX, but they aren't using the `ufFormSubmit` method and are not manually inserting the CSRF token into the request;
C. (This is the most pernicious situation) They are trying to submit a form with AJAX, and they are trying to insert the CSRF token, but the browser is falling back to submitting the form the old-fashioned way without the CSRF token.  This is because they have some kind of Javascript error on their page, or a missing JS resource, which halts execution of the Javascript on the page before the `.submit()` handler gets registered.  Thus, the browser silently falls back to submitting the form without invoking the `.submit` handler, and the CSRF token never gets added to the request.

This, needless to say, is difficult for newcomers to debug, especially if they're not used to using their browser console and checking for JS errors.  Also, it is confusing that a JS error should cause a 400 error on the server - the connection isn't immediately obvious.

So, we need a better way of dealing with this.  I personally like the way we store the CSRF token in the `<head>` tag of every page, since it makes it easy to access without having to explicitly insert into each form.  However, then it needs to be inserted manually into the AJAX request, so it might just be two sides of the same coin.

Any ideas on how we could foolproof this issue?

**Comment by r3wt** [comment]
possible solution for ajax, including file uploads which can only be made over ajax with an instance of `FormData`:

```js
var csrf = 'example';

$.ajaxPrefilter(function (options, originalOptions, jqXHR) {
	//file uploads or form data.
	if(originalOptions.data instanceof FormData){
		options = originalOptions;
		options.data.append('c',csrf);
	}
	else if(typeof originalOptions.data === 'object'){
		options.data = $.param($.extend(originalOptions.data, { c: csrf }));
	}
	else{
		//some other strategy
	}
});

//avoid the cost of having to deserialize to append the csrf token in prefilter.
//usage $('form').serializeObject();
$.fn.serializeObject = function()
{ 
    var b = this.serializeArray();
    var a = {};
    for(var i=0;i<b.length;i++){
        a[b[i].name] = b[i].value;
    }
    return a;
};

```

**Comment by candcguy** [comment]
From personal experience, when attempting to send information from another website to my company's internal UF based site, the csrf bug confounded me for three days. Part of the issue was the fact that the error code was a simple 400, with no information about the csrf token. Since it was an urgent request, for two days I used GET to send the information. Upon finding the bug, I modified the CsrfGuard to exempt certain routes from csrf verification, and instead used [slim basic http authetication](https://github.com/tuupola/slim-basic-auth) to secure those routes. Perhaps something like this could be incorporated into a new UF version?

**Comment by r3wt** [comment]
@candcguy you raise a valid point. 

@alexweissman exposing a csrf token through an api endpoint is not a security risk. so we could possibly expose token from an api endpoint that is "exempt" from CsrfGuard, and periodically poll for the changed csrf token. As an aside, the responce code for `not authorized` is `403`, not sure why it is 400 in CsrfGuard.

**Comment by alexweissman** [comment]
Well the problem isn't so much that the token is changing (usually).  The problem is that it is not obvious when the token is not being sent back to the server.  So, I'd consider this primarily a client-side problem.

One possibility is that we could create some JS earlier on, before any other JS code is attempted to execute, which automatically injects the CSRF token into any `<form>` it sees.  Then, there will be no need to remember to add it to the form submission, AJAX or not.  We could also use a `<noscript>` tag so that, in the rare case where the JS responsible for injecting the token breaks, the developer will get some kind of warning.

**Comment by 9tontruck** [comment]
Sometimes I get 
POST http://localhost/account/login 403 (Forbidden)
when I am loggin in. And after a while, this problem does away. Is this related to the CSRF issue?

**Comment by thomasspe** [comment]
I just posted it in the chat but it might also be an idea to have it here. I think it is somewhat close to what Alex suggested. 

It loops through the `document.forms` and appends the token. Correct me if I'm wrong but I think it is also as secure as `ufFormSubmit` as it obtains the token in the same way.

I also tested what happens when you have this bit of code together with `ufFormSubmit` and couldn't see any negative implications.

```
for (i = 0; i < document.forms.length; i++) {
    var input = document.createElement('input');
    input.type = 'hidden';
    input.name = 'csrf_token';
    input.value = $("meta[name=csrf_token]").attr("content");       
    document.forms[i].appendChild(input);
}
```

**Comment by r3wt** [comment]
I may have found a dependable way to work around this, by hooking into `slim.after` and manually overwriting the cookie on the client with a new expiration date, therefore extending their session. i've only tested with redis as a session handler. if you're using the file based session handler you may need to do some other crap as well to get the session to be extended.

```php
$app->hook('slim.after',function() use($app){
	$p = session_get_cookie_params();
	setcookie(session_name(),session_id(),time()+(15*60),$p['path'],$p['domain'],$p['secure'],$p['httponly']);
});
```

**Comment by alexweissman** [comment]
I believe the most straightforward solution is simply to have developers explicitly insert the code for including a hidden field containing the CSRF token in their forms.  We have a Twig template [`csrf.html.twig`](https://github.com/userfrosting/UserFrosting/blob/b48f29eae3a62b235a00f982dbf9f80fd1c03c23/app/sprinkles/core/templates/components/csrf.html.twig) which can be `include`d in form templates:

```
<form id="set-or-reset-password" role="form" action="{{site.uri.public}}/account/set-password" method="post" class="r-form">
                {% include "components/csrf.html.twig" %}
                {# Prevent browsers from trying to autofill the password field.  See http://stackoverflow.com/a/23234498/2970321 #}
                <input type="text" style="display:none">
                <input type="password" style="display:none">
                
                <div class="form-group">
                    <label class="sr-only" for="form-password">Password</label>
                    <input type="password" name="password" placeholder="Choose a password, 12-100 characters" class="form-control" id="form-password">
                </div>
                <div class="form-group">
                    <label class="sr-only" for="form-passwordc">Re-enter Password</label>
                    <input type="password" name="passwordc" placeholder="Re-enter your password" class="form-control" id="form-passwordc">
                </div>
                <input type="hidden" name="token" value="{{token}}">
                <button type="submit" class="btn">Set Password and Sign In</button>
</form>
```

Auto-injecting the CSRF token via JS was a nice attempt to make things easier, but it seems to have done the opposite for many people.

For non form-based (AJAX) POST requests, I suppose a Javascript configuration variable would be helpful.

For excluding certain routes from CSRF checks, we have two options.  Either we can disable global CSRF middleware, and instead require that each route explicitly declare the CSRF check as route middleware ("whitelist" approach).  Or, we can leave global CSRF middleware enabled, and then provide a means for routes to declare themselves exempt from CSRF checks ("blacklist" approach).  

The "blacklist" approach would require that we modify [Slim-Csrf](https://github.com/slimphp/Slim-Csrf), which does not currently support "exempt" routes.  Would like to hear people's opinions on the best approach for this last point.

**Comment by alexweissman** [comment]
Moved the discussion about whitelisting/blacklisting CSRF guard for specific routes to #665.
