### ISSUE TITLE
Adding data to user table

### ISSUE THREAD

**Issue by Flynntes** [userfrosting/UserFrosting#514]
Hi!
I need to add a little more data about each user. This should be done by the user in the dashboard. How would I go about doing this?

**Comment by alexweissman** [comment]
Hey @Flynntes, welcome to UserFrosting.  These sorts of general "how do I do X in UserFrosting" questions should not be posted in issues.  Instead, please make sure you have read through the documentation and tutorials on the [website](http://www.userfrosting.com/), and the user-contributed [wiki](https://github.com/userfrosting/UserFrosting/wiki).  If you're still having trouble, you can [join us in chat](https://gitter.im/userfrosting/UserFrosting).

Thanks!
