### ISSUE TITLE
When user property is NULL in the DB, UserController.php throws 400 on update

### ISSUE THREAD

**Issue by atechdad** [userfrosting/UserFrosting#520]
https://github.com/userfrosting/UserFrosting/blob/master/userfrosting/controllers/UserController.php#L585

**Comment by alexweissman** [comment]
The problem here is that we have to do an `isset` check on `$target_user->$name` before checking `$post[$name] != $target_user->$name`.  However, `isset` returns false if `$target_user->$name` is set to `null`.  Thus, it is treating null values as invalid columns.

**Comment by Netrilix** [comment]
We've researched this quite a bit, and PHP seemingly doesn't offer a good (or even functional) way of reliably determining whether a variable is failing `isset()` because it's `null` versus it not being set at all.

**Comment by Aterbonus** [comment]
Reading the docs I found this http://php.net/manual/es/function.property-exists.php
Check this example http://ideone.com/sQTBLC

**Comment by alexweissman** [comment]
Hmm, I'm hesitant to override Eloquent's current implementation of `isset`, but on the other hand, this *does* look promising.  Maybe we should just add a new method to `UFModel`, calling it `property_exists`, and call `array_key_exists` inside that:

```
class UFModel extends Illuminate\Database\Eloquent\Model {

    public function property_exists($key) {
        return array_key_exists($key, $this->attributes);
    }

}

echo $objectA->property_exists($property);

```

That way, we don't break anything that depends on Eloquent's own implementation of `_isset`, but we can use `property_exists` when we want to allow the property to be `NULL`.

**Comment by Aterbonus** [comment]
+1 I didn't check for Eloquent's implementation of `__isset()`. My bad.

**Comment by r3wt** [comment]
What's the status of this?

**Comment by alexweissman** [comment]
It should be straightforward to implement `property_exists`, and then make the necessary changes in `UserController` and anywhere else this distinction is needed.  Any volunteers?

**Comment by alexweissman** [comment]
Fixed.  We now have `attributeExists` and `relationExists` methods in `UFModel`.
