### ISSUE TITLE
Getting always 400 status on POST

### ISSUE THREAD

**Issue by harding13** [userfrosting/UserFrosting#524]
I'm trying to create a restful api set.
I haven't problem with GET but when i try to use POST (from remote, i'm using Postman Chrome extension) it returns always 400

ADDENDUM: this isn't a server problem

**Comment by alexweissman** [comment]
It's almost certainly a CSRF token issue.  See https://github.com/userfrosting/UserFrosting/wiki/On-the-matter-of-CSRF-tokens

**Comment by harding13** [comment]
Oh, yes thanks

Disabling CSRF about POST let my test working.
Now i'm trying to insert this security feature in an android app working with userfrosting

**Comment by alexweissman** [comment]
No problem.  Again, you might want to consider implementing a completely RESTful API that your Android app can interact with.  Feel free to continue this conversation in #517.
