### ISSUE TITLE
DATABASE ERROR plz Help !

### ISSUE THREAD

**Issue by GabrielEnraged** [userfrosting/UserFrosting#525]
Hello guys. I really really want to set up Userfrosting on my website www.enragedgamers.net

But i have a little problem...

There is a big database error in the installation. I'm not a php coder so if you want, you can make a little tutorial for me :)

The code of the error : 

`We can't seem to find our way to initialize.php! Please check the require_once statement at the top of index.php, and make sure it contains the correct path to initialize.php.

We can't seem to connect to the database.

Have you tried hacking into the mainframe? Seriously though, check your PHP error log to figure out what's up. You probably just need to enter your database credentials in userfrosting/config-userfrosting.php. If you are sure that your credentials are fine, try simply reloading the page.
© UserFrosting, 2016
Built with UserFrosting.
`
I have placed require_once 'userfrosting/initialize.php';

In the top on my file...
But i have already the error ?
And I have verified all the files and they are correct.

So i don't know how to fix. 

Thanks you, 

Gaby

**Comment by GabrielEnraged** [comment]
:) I have forgettent a item : 

I have placed require_once 'userfrosting/initialize.php';

In the top on my file...
But i have already the error ?

Why ?

**Comment by GabrielEnraged** [comment]
Again once,

I have verified all the files and they are correct.

So i don't know how to fix. 

Ty,

Gaby

**Comment by alexweissman** [comment]
So, you're sure the *relative* path to `initialize.php` is correct?  Maybe it is a permissions issue?

**Comment by GabrielEnraged** [comment]
Yes i think the relative path is correct. I have put that : 

require_once 'userfrosting/initialize.php';

Is it correct ?

Thanks 

Gaby

**Comment by alexweissman** [comment]
Well, it depends on how you have your directory structure set up.  Did you read the [installation guide](http://www.userfrosting.com/installation/#install-userfrosting)?

**Comment by GabrielEnraged** [comment]
My public content is in a folder membres and the folder membres is in the folder public_html
The folder userfrosting is in the folder membres at the some level of the content public.

Is it correct ?

Thanks 

Gabriel.


and yes i have read the installation tutorial before post here

**Comment by Netrilix** [comment]
With that directory structure, you'd want your path to be `../userfrosting/initialize.php`.

**Comment by alexweissman** [comment]
So, like this?
```
public_html/
      |----membres/
                   |----public/
                   |         |----index.php
                   |----userfrosting/
```

That's not really ideal, since now the contents of `userfrosting` are publicly exposed.  You'll note that, although you have disallowed directory listing (which is good), individual files are still accessible: http://www.enragedgamers.net/membres/userfrosting/templates/themes/default/dashboard.twig

**Comment by alexweissman** [comment]
Do you have to serve from `public_html`?  Usually, cPanel accounts (which this smells like to me) have an option to set different directories as the root directory for different domains.  You could do something like:
```
/
|----public_html/    // Don't even bother using this directory
|----membres/
        |----public/     // Make this the root directory for your site
        |         |----index.php
        |----userfrosting/       // This directory doesn't need to be served from
```

**Comment by GabrielEnraged** [comment]
Yes my server is from public_HTML.
I'm icoming to disallow listing of the folder userfrosting. I can tell you this In 7 hours.

Thanks u,

Gabriel

**Comment by GabrielEnraged** [comment]
Ok. Now, i have just the database error. I have put the correct logins  but there is always the error : 


We can't seem to connect to the database.


Have you tried hacking into the mainframe? Seriously though, check your PHP error log to figure out what's up. You probably just need to enter your database credentials in userfrosting/config-userfrosting.php. If you are sure that your credentials are fine, try simply reloading the page.

**Comment by alexweissman** [comment]
Perhaps it is a database user permissions error?  Check your PHP error log (as the error message instructs you to do!) and there should be more details as to why it can't connect to the DB.

**Comment by GabrielEnraged** [comment]
I don"t have acces to logs because it's a shared hosting...

So how can I do ?

**Comment by alexweissman** [comment]
Even shared hosts usually provide some access to error logs.  Are you sure (did you ask the hosting service)?

On another note, do you have a local development environment set up on your computer?  You should try to install UF locally first, and develop locally.  Then you can just push your code to the live server when it's ready.

**Comment by GabrielEnraged** [comment]
I don't have local environment but i think i'm incoming to try it. So can you explain to me how i can setup a local environment ? Thanks for ever,


Gaby

**Comment by GabrielEnraged** [comment]
Just  an question, if it work and if i put the code on my hosting. How the database can work ? Because she's in my PC !? Thanks


Gaby

**Comment by alexweissman** [comment]
You can set up a test database locally as well.  Check out something like [XAMPP](https://www.apachefriends.org/index.html), which will install PHP, Apache, and MySql/MariaDB on your machine.

**Comment by GabrielEnraged** [comment]
How OK thanks men. I test this but one question :  the client who want create an account. I'm obliged to set up m'y database si, if it's not working ?

**Comment by alexweissman** [comment]
Sorry, I don't understand:

> m'y database si,

**Comment by GabrielEnraged** [comment]
How OK thanks men. I test this but one question : the client who want create an account. I'm obliged to set up my database.
if it's not working ?

**Comment by alexweissman** [comment]
So, were you able to get the database and UF working locally?

**Comment by GabrielEnraged** [comment]
Yes it's work fine. I have an idea for the problem. I have modified database logs in the file initialize. Is it possible the error privide by this ?

**Comment by alexweissman** [comment]
> database logs

Do you mean the database configuration?

**Comment by GabrielEnraged** [comment]
Yes it's that

**Comment by GabrielEnraged** [comment]
I have put my database configuration in the slot database connexion in the file initialize.PHP but i think i shouldn't do that.

**Comment by GabrielEnraged** [comment]
Exactly here in the file initialize.php : 
$capsule->addConnection([

**Comment by alexweissman** [comment]
You should probably just put it in your `config-userfrosting.php`.

**Comment by GabrielEnraged** [comment]
OK after modifications in local,  i pût this on the FTP and i show result.

Thanks,

Gaby


An other question : how i can set up the support and the store commands ?

Thanks,

Gaby

**Comment by Netrilix** [comment]
I'm sorry, we're having a little bit of a language barrier here.

Can you give us a little more description about what you mean by "support" and "store"?

**Comment by GabrielEnraged** [comment]
For commands this one :
![orders](https://cloud.githubusercontent.com/assets/18049206/14141134/7d785f90-f67d-11e5-90b1-6507b838cd8b.JPG)
And for support, this one :
![support](https://cloud.githubusercontent.com/assets/18049206/14141135/7d7cf21c-f67d-11e5-855e-f772f1b4e37c.JPG)

I just want that you tell me how to do that :)

Because i'm not php coder :-(

**Comment by Netrilix** [comment]
Those are just placeholders to show how stuff can be added to the dashboard. UserFrosting only handles the actual user management. Anything like product sales or a support system would need to be written by you or added as third-party code (and merging another program into UserFrosting will be difficult if you don't know PHP).

You might be looking more for a shopping application or something rather than a framework like this.

**Comment by GabrielEnraged** [comment]
Ok. Thanks, now you can close this issue.

Thanks for your help. I have found a coder.

:) 


Again thanks for all,


Gaby
