### ISSUE TITLE
404 Not found ?? File install not found ?

### ISSUE THREAD

**Issue by GabrielEnraged** [userfrosting/UserFrosting#527]
Hello guys, after modification of the file config, i have succeded to delete the error database, so there is no error with this. Now, i have an 404 not found ?!

Error :8ball: 

Not Found

The requested URL /membres/public/install/ was not found on this server.

I can't have .htaccess on my webserver.

How i can change this ?

Thanks,

Gaby

**Comment by alexweissman** [comment]
Unfortunately, `mod_rewrite` (and the ability to actually deploy Rewrite rules through `.htaccess` or through a Virtual host file) is a [basic requirement for UserFrosting](http://www.userfrosting.com/installation/#server-requirements).

I find it hard to believe that there is *any* Apache web hosting service that doesn't allow `.htaccess`.  Are you sure that your web host is using Apache?  If they're running something like nginx or IIS, you'll need a [different type of configuration file](https://github.com/userfrosting/UserFrosting/issues/373).  You should contact your web host and find out what type of web server they're running.  

If they're running Apache, ask them if there is another way to configure rewrite rules.
