### ISSUE TITLE
adding stripe into composer 

### ISSUE THREAD

**Issue by 9tontruck** [userfrosting/UserFrosting#528]
Hi,

I am trying to use Stripe's payment feature.

1. I downloaded the lastest version of Stripe in https://github.com/stripe/stripe-php/releases
2. I added stripe folders abd files at /userfrosting/vendor/stripe/stripe-php
3. I added "stripe/stripe-php": "3.*" in vendor/composer.json under "required" key.
4. I added 'UserFrosting\\Stripe' => $vendorDir. '/stripe/stripe-php/lib/Stripe.php', in autoload_classmap.php
5. In SomeController.php I want to use Stripe::setApiKey("private_key"); but PHP cannot find UserFrosting\\Stripe.

And I am stuck here :(
I would like to use the php code in https://stripe.com/docs/charges in a controllers/SomeController.php but I can't use stripe because it's not fully loaded.
What's the next step I sould do?

**Comment by 9tontruck** [comment]
It was \Stripe\Stripe::setApiKey(""); 
Thanks

**Comment by alexweissman** [comment]
You're **not supposed to manually modify anything in `vendor`**.  Don't change anything in `vendor`.  If you change things in `vendor` by hand, terrible horrible things will happen.  **Composer manages `vendor` for you**.  [Seriously, DON'T MANUALLY MODIFY ANYTHING IN VENDOR](http://www.userfrosting.com/navigating/#composer)!

...Just add your dependency to `userfrosting/composer.json` and run `composer update`.  That's all you need to do.  Steps 1, 2, and 4 are completely unnecessary, and a bad idea as well.
