### ISSUE TITLE
Multiple database connections in the same UserFrosting project

### ISSUE THREAD

**Issue by MinhDNguyen** [userfrosting/UserFrosting#529]
I want to connect another database beside default one of UserFrosting system.

Someone give me suggestions, thanks!

**Comment by alexweissman** [comment]
Another MySQL database?  Check out the [Eloquent documentation](https://laravel.com/docs/5.0/database#accessing-connections).  You can initialize your additional connections in [initialize.php](https://github.com/userfrosting/UserFrosting/blob/master/userfrosting/initialize.php#L42-L51) and name it as you desire.

**Comment by alexweissman** [comment]
Let us know if you're still having trouble with this!

**Comment by cpaloukas** [comment]
Hey Alex,

In a my new and second project using Userfrosting I ran into this same problem. The second database in my case is an ms mssql. I added the following to my initialize.php right below the default connection:
`$capsule->addConnection([
    'driver'    => 'sqlsrv',
    'host'      => 'db_2',
    'database'  => 'DB2',
    'username'  => 'user',
    'password'  => 'pass',
    'charset'   => 'utf8',
    'collation' => 'utf8_unicode_ci',
    'prefix'    => ''
],"DB2");`

Having looked over the Eloquent docs you provided a link to above I'm still having a hard time building queries in my controllers using the second connection. Can you steer me in the right direction please?

**Comment by Netrilix** [comment]
`protected $connection = 'DB2';` at the top of your second database's models should accomplish this.

**Comment by cpaloukas** [comment]
That was it! Thank you very much!
