### ISSUE TITLE
How do I add a custom controller class to UF?

### ISSUE THREAD

**Issue by fideltfg** [userfrosting/UserFrosting#530]
I would like to implement my own custom controller classes so I don't have to modify UF's existing controller class files. I have the class file in uf/controllers, and have extended the base controller. Where do I add the include for this new file? Any information in where int he code this is achieved would be a grate help. Thanks and great work btw.

**Comment by malle-pietje** [comment]
Run composer update

**Comment by alexweissman** [comment]
Yup, you can just put your controller class in `/userfrosting/controllers` and run `composer update`, like @malle-pietje suggested, to have it autoloaded with the rest of the classes.

**Comment by fideltfg** [comment]
Ah!! I read that in the docs too, just slipped my mind. thanks guys.
