### ISSUE TITLE
How can I turn on "debug" in Twig?

### ISSUE THREAD

**Issue by 9tontruck** [userfrosting/UserFrosting#531]
Hi,

I would like to use {% debug data %} in my twig file. debug is same as var_dump in php.

Because debug is disabled as default, I need to add

```
$twig = $app->view()->getEnvironment();
$twig->addExtension(new Twig_Extension_Debug());
```

But adding it in index.php does not make any change. Does anyone know where the right location is for adding this code?

**Comment by ltask** [comment]
Hi,

Try adding `$twig->enableDebug();` after your code.

**Comment by 9tontruck** [comment]
Hm.. I still have the same problem

        $twig = $app->view()->getEnvironment();   
        $twig->addExtension(new Twig_Extension_Debug());
        $twig->enableDebug();
        $this->_app->render($twigFile, [
            'data' => $data
        ]);

        {% debug data %}

Error msg is 
    Unexpected "debug" tag (expecting closing tag for the "block" tag defined near line 18)

Can you give me anything else I can try out?

**Comment by taskula** [comment]
Perhaps you are looking for the `dump` function? It works like PHP's var_dump(). http://twig.sensiolabs.org/doc/functions/dump.html

In that case, try using `{{ dump(data) }}`

**Comment by r3wt** [comment]
I'm adding the feature request and use and extension labels to this thread. I tink its a good oppurtunity to add a new configuration setting to enable debugging in twig for developers who use UF.

**Comment by alexweissman** [comment]
Agreed.  There are a number of modules that each have their own debugging feature.  Should we have a single switch that turns on/off all debugging, or should we allow control over each module individually?

**Comment by r3wt** [comment]
@alexweissman we could have a multishaped value for `debug`. if its a boolean, it would be global. if its an md array, then each component is named as k/v pair. i think that could work, and perhaps it would be easiest, but i could go either way on that subject.

**Comment by alexweissman** [comment]
what if we did both?  There could be a global setting, and then an array setting for individual modules to override the global.

**Comment by alexweissman** [comment]
This has been implemented in [dev](https://github.com/userfrosting/UserFrosting/blob/b48f29eae3a62b235a00f982dbf9f80fd1c03c23/app/sprinkles/core/config/default.php#L57-L60) under the `debug` configuration key in the `core` Sprinkle:

```
        'debug' => [
            'twig' => false,
            'smtp' => true
        ],
```

There is also a [debugging option for authorization checks](https://github.com/userfrosting/UserFrosting/blob/b48f29eae3a62b235a00f982dbf9f80fd1c03c23/app/sprinkles/account/config/default.php#L9-L11) in the `account` Sprinkle:

```
        'debug' => [
            'auth' => false
        ],
```

Setting `auth` to `true` will cause detailed information about authorization checks to be dumped to `logs/auth.log`.  Like all configuration settings, you can override these values in your site's Sprinkle.
