### ISSUE TITLE
Colum not found: 1054 Unknown colum

### ISSUE THREAD

**Issue by fideltfg** [userfrosting/UserFrosting#532]
Hi

I've been trying to work through the tutorials and adapt the information there to make a projects page for my site. this will simply list all the projects belonging to the user. I followed the tutorials (changing the variables and table names as I went so as to reflect my database)... but as I just think I'm finished I keep getting this error 

> Column not found: 1054 Unknown column '_project_users.__project_id' in 'field list'

I've been chasing this error all day and have read and re-read the docs and checked and rechecked my code and database. everything looks to be correct. Any help spotting the problem would be awesome and save me from completely wasting my entire days efforts. thanks

I have things set out as follows
added to initialize.php:
```
// projects table
$table_projects = new \UserFrosting\DatabaseTable("_projects", [
        "name"
]);
// project to user link table , tried with and without column names here
$table_project_users = new \UserFrosting\DatabaseTable("_project_users", [
        "user_id",
        "project_id"
]);

\UserFrosting\Database::setSchemaTable("_projects", $table_projects);
\UserFrosting\Database::setSchemaTable("_project_users", $table_project_users);
```

in the controller (_ProjectController) I added the function called from the route in index.php
 
```
namespace UserFrosting;

class _ProjectController extends \UserFrosting\BaseController
{

    public function __construct ($app)
    {
        $this->_app = $app;
    }

    // display a list of all projects for the user
    public function viewProjectList(){
        // Access-controlled resource
        if (! $this->_app->user->checkAccess('uri_projects')) {
            $this->_app->notFound();
        }
        
        $project = _Project::find(1);
        print_r($project) // this displays the project object
        $users = $project->users; // this fails!!
        foreach ($users as $user){
             echo $user->display_name . PHP_EOL;
        }

 
        //$this->_app->render('project/project-list.twig', ["projects" => $projects]);
    }
}
    
```

and this is my data model class

```
namespace UserFrosting;
use \Illuminate\Database\Capsule\Manager as Capsule;

class _Project extends UFModel
{

    protected static $_table_id = "_projects";

    public function __construct ($properties = [])
    {
        parent::__construct($properties);
    }

    public function users ()
    {
        $link_table = Database::getSchemaTable('_project_users')->name;
        return $this->belongsToMany('UserFrosting\User', $link_table);
    }

    public function __isset ($name)
    {
        if (in_array($name, [
                "users"
        ]))
            return true;
        else
            return parent::__isset($name);
    }
}
```

**Comment by alexweissman** [comment]
What's with all the underscore prefixing?  Eloquent does a lot of automatic translation between table names and class names, and `_` is usually a special character used in this translation.  See for example: https://laracasts.com/discuss/channels/eloquent/table-name-convention?page=1

**Comment by fideltfg** [comment]
I do this so I can spot my additions a bit easier, but this should not be an issue..should it? I've never ran in to a problem doing with this.... Also I notice that the column that can not be found in the error is called __project_id I do not use underscores for column names in the DB, and this one has two on it.

I can rework that code without them and see if it solves the problem.

**Comment by fideltfg** [comment]
No difference with or without the underscores

**Comment by alexweissman** [comment]
most likely, Eloquent sees a relationship with a table called `_projects`, and then when you do `return $this->belongsToMany('UserFrosting\User', $link_table);`, it is trying to automatically determine the name of the foreign key based on the name of the table.  Thus `_projects` is interpreted as two words `_` and `project`, and so they get connected with another `_` and suffixed with `_id`.

**Comment by fideltfg** [comment]
I have removed all leading underscores from everything I used them on. the effect is the same. if I try to use the dynamic variable 'users' on the project model it bombs wit that same error

**Comment by alexweissman** [comment]
it's still looking for `__project_id`?

**Comment by fideltfg** [comment]
yes, that is correct.

**Comment by alexweissman** [comment]
And, you don't have any leading underscores anymore?  Not even in the names of the tables themselves (not UF's identifiers)?

**Comment by fideltfg** [comment]
Only place I have them is on the class names _Project and _ProjectController 

in case it helps here is the full error


[11-Apr-2016 16:30:08 America/Edmonton] Error in I:\workspace\thapp\application\vendor\illuminate\database\Connection.php on line 624: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'project_users.__project_id' in 'field list' (SQL: select `uf_user`.*, `project_u
sers`.`__project_id` as `pivot___project_id`, `project_users`.`user_id` as `pivot_user_id` from `uf_user` inner join `project_users` on `uf_user`.`id` = `project_users`.`user_id` where `project_users`.`__project_id` = 1)

[11-Apr-2016 16:30:08 America/Edmonton] #0 I:\workspace\thapp\application\vendor\illuminate\database\Connection.php(580): Illuminate\Database\Connection->runQueryCallback('select `uf_user...', Array, Object(Closure))
#1 I:\workspace\thapp\application\vendor\illuminate\database\Connection.php(297): Illuminate\Database\Connection->run('select `uf_user...', Array, Object(Closure))
#2 I:\workspace\thapp\application\vendor\illuminate\database\Query\Builder.php(1377): Illuminate\Database\Connection->select('select `uf_user...', Array, true)
#3 I:\workspace\thapp\application\vendor\illuminate\database\Query\Builder.php(1367): Illuminate\Database\Query\Builder->runSelect()
#4 I:\workspace\thapp\application\vendor\illuminate\database\Query\Builder.php(1354): Illuminate\Database\Query\Builder->getFresh(Array)
#5 I:\workspace\thapp\application\vendor\illuminate\database\Eloquent\Builder.php(380): Illuminate\Database\Query\Builder->get(Array)
#6 I:\workspace\thapp\application\vendor\illuminate\database\Eloquent\Relations\BelongsToMany.php(170): Illuminate\Database\Eloquent\Builder->getModels()
#7 I:\workspace\thapp\application\vendor\illuminate\database\Eloquent\Relations\BelongsToMany.php(95): Illuminate\Database\Eloquent\Relations\BelongsToMany->get()
#8 I:\workspace\thapp\application\vendor\illuminate\database\Eloquent\Model.php(2646): Illuminate\Database\Eloquent\Relations\BelongsToMany->getResults()
#9 I:\workspace\thapp\application\vendor\illuminate\database\Eloquent\Model.php(2573): Illuminate\Database\Eloquent\Model->getRelationshipFromMethod('users')
#10 I:\workspace\thapp\application\vendor\illuminate\database\Eloquent\Model.php(3263): Illuminate\Database\Eloquent\Model->getAttribute('users')
#11 I:\workspace\thapp\application\_thapp\_ProjectController.php(22): Illuminate\Database\Eloquent\Model->__get('users')
#12 I:\workspace\thapp\public\index.php(82): UserFrosting\_ProjectController->viewProjectList()
#13 [internal function]: {closure}('list')
#14 I:\workspace\thapp\application\vendor\slim\slim\Slim\Route.php(468): call_user_func_array(Object(Closure), Array)
#15 I:\workspace\thapp\application\vendor\slim\slim\Slim\Slim.php(1357): Slim\Route->dispatch()
#16 I:\workspace\thapp\application\vendor\slim\slim\Slim\Middleware\Flash.php(85): Slim\Slim->call()
#17 I:\workspace\thapp\application\vendor\slim\slim\Slim\Middleware\MethodOverride.php(92): Slim\Middleware\Flash->call()
#18 I:\workspace\thapp\application\middleware\CsrfGuard.php(51): Slim\Middleware\MethodOverride->call()
#19 I:\workspace\thapp\application\middleware\usersession\UserSession.php(27): Slim\Extras\Middleware\CsrfGuard->call()
#20 I:\workspace\thapp\application\vendor\slim\slim\Slim\Slim.php(1302): UserFrosting\UserSession->call()
#21 I:\workspace\thapp\public\index.php(500): Slim\Slim->run()
#22 {main}

**Comment by alexweissman** [comment]
Ahh, Eloquent might be getting them from the class names then.  Try removing those underscores as well.

**Comment by fideltfg** [comment]
OK that did it.
Thanks for you help. time to find a new naming convention for myself 
Note to self ..."DON'T USE UNDERSCORES AS PREFIXES IN UF !!!! HAHAHAH!"

**Comment by alexweissman** [comment]
Don't use underscores as prefixes in Eloquent*  ;-)  Glad we could help.

**Comment by alexweissman** [comment]
Also, lucky for you, there is already a widely adopted naming convention for PHP: http://www.php-fig.org/psr/psr-1/

This will make your code easier for others to read as well!
