### ISSUE TITLE
pass parameters to ufFormSubmit call back function on successful form submission

### ISSUE THREAD

**Issue by fideltfg** [userfrosting/UserFrosting#533]
hi all.

I have set up a form to create a new project within my site. I can get ufFormSubmit to redirect back to my project list view. However I would like to redirect to a route that requires parameter to view correctly instead. ( the new project ID just created ) so...How do I pass parameters to ufFormSubmit call back function on successful form submission? or is there an alternative I've missed.

I tried the below code, but this fails as project.name isn't available until after the form is submitted and the new project created. 
```
ufFormSubmit(
                  $("form[name='newProjectForm']"),
                  validators,
                  $("#userfrosting-alerts"),
                  function(data, statusText, jqXHR) {
                      // Reload the page on success
                      window.location="{{site.uri.public}}/project/view/{{ project.name }}";
                  }
                );
```

thanks

**Comment by alexweissman** [comment]
You need to find a way to get the project name after the form is submitted.  You are correct that the template won't have it, because the template was rendered before the project was created.

The recommended way to handle this is:
[Via the `Location` header](https://en.wikipedia.org/wiki/HTTP_location) in the POST response, along with a `201` (resource created) code.  You can access it in the AJAX callback via [`getResponseHeader`](http://stackoverflow.com/a/11224104/2970321).

**Comment by fideltfg** [comment]
I took a look at your recommended method... first not easy for a relative noob like me.  

Second using this..
```
console.log("test = " + jqXHR.getResponseHeader('Location'));
```
he location header returns null...
So I cheated...As the project name is entered on the form and validated, if the project is created I can assume ( i know never good to assume) that the name is valid... so I did this instead. 
```
$(document).ready(function() { 
                // Load the validator rules for this form
                var validators = {{validators | raw}};
                ufFormSubmit(
                  $("form[name='newProjectForm']"),
                  validators,
                  $("#userfrosting-alerts"),
                  function(data, statusText, jqXHR) {
		          var pName = $('#input_name').val();
                	  window.location="{{site.uri.public}}/project/view/" + pName;   
                  }
                );
});
```
I will keep looking at the method you suggested , though I'm unsure how I will get the project name back in to the response headers.

**Comment by alexweissman** [comment]
http://docs.slimframework.com/response/headers/

**Comment by fideltfg** [comment]
Ah much better info there, thanks :)

 so I've get the header set via slim in my submit route 
```
$this->_app->response->headers->set("project_name", $post['name']);
```
and I can see it  in Firebug and Chrome->dev tools as being set and it has the correct value...but its still seen as null when I use.
```
console.log("test = " + jqXHR.getResponseHeader('project_name'))
```

**Comment by alexweissman** [comment]
no no.  The name of the header is `Location`.  `project_name` is probably not a valid header name.

```
$base_url = $this->_app->config('site')['uri']['public'];
$this->_app->response->headers->set('Location', "$base_url/project/view/{$post['name']}");
$this->_app->response->setStatus(201);
```

**Comment by fideltfg** [comment]
Cool, thanks I will give that a try in the morning, I used project name as the slim doc's inferred I could use whatever I wanted. Thanks so much for all the help. Our site is coming along really well and despite my first impression of UF ( being overly complex ) I'm actually starting to understand it enough I think Its going to work well for our plans here.

**Comment by alexweissman** [comment]
No problem, glad it's working out for you!  If you need any more help, feel free to join us in chat.
