### ISSUE TITLE
Question about user access level

### ISSUE THREAD

**Issue by Maxblake** [userfrosting/UserFrosting#534]
First of all, thanks for Userfrosting, it's fantastic, and has saved me lots of time, as I was trying to run registration portal for new employees. However, I'm having some trouble with user access control.
After standard registration process, new user need to add more information about himself, so I've added a few custom fields to the "user-info-form.twig"  and now admin can view user profile with all necessary information. 
To add more information registered user have to click  "EDIT PROFILE" button which I include to dashboard  with link to "user-info-modal.twig".
Now I have problem: this button work correctly and edits "user-info-form" only when I create authorization rule : 
uri_users / always() for group "Users".  

But this rule allow to see the all profiles of another users, if "clever user" just change his url:
 (ie: domain.com/users/u/2) url to ( domain.com/users ). 
I suspect authorization rule must be different, to allow user access his form only . 
Is there anyone who can help me to write the correct authorization rule ?

Thanks you, 
Maximilian

**Comment by alexweissman** [comment]
You are correct, `uri_users` controls access to the listing of *all* users, so you shouldn't add access for that.

The way it's set up right now, is that users are supposed to modify their account/profile settings through the "settings" option in the upper-right menu:

![screen shot 2016-04-13 at 1 30 37 pm](https://cloud.githubusercontent.com/assets/5004534/14502991/fe34955a-017b-11e6-9d59-309b2b6d1dc3.png)

Would you want to just include your custom fields in that interface, or do you truly need a separate "profile" page?

**Comment by Maxblake** [comment]
I added custom fields to the "user-info-form.twig" so I need to setup user access for this form

**Comment by Maxblake** [comment]
I tried : uri_users / equals(self.id) but dosn't work

**Comment by alexweissman** [comment]
It sounds like you are confused as to how UF is laid out.  Maybe you should join us in [chat](https://gitter.im/userfrosting/UserFrosting).
