### ISSUE TITLE
Factor out handling of access control checks in controllers

### ISSUE THREAD

**Issue by fideltfg** [userfrosting/UserFrosting#535]
hi, I'm trying to work out the best way to redirect 'guest' users to the log in page if they arrive via link to a restricted page... so if they use http://mysite/dashboard/ and are not logged in they will see the login form instead of the 404 page. or send them back to the guest landing page. how would I go about this? thanks

**Comment by alexweissman** [comment]
We should refactor the code to make it easier to modify the default behavior when access to a page is denied.  Instead of calling `notFound` after a failed check, they should throw an exception that can be caught with a custom handler.  

Individual calls can still be overridden in the controller of course, but using an exception would make it easy to modify the behavior globally.

**Comment by cmy82** [comment]
Is is possible to add another parameter to the notFound() call where you can use a select statement to redirect to pages of your choosing? Maybe make it where you can setup an associative array of errors and the TWIG page that you want rendered:
```
$app->notFound(function($code) use ($app) {
   if( $app->custom_handlers ){   
      $app->render( $app->custom_handlers[$code] ); 
   } else
      $controller->page404();
   }
});
```

Where custom_handlers can be set in UserFrosting.php and is initially NULL.

**Comment by alexweissman** [comment]
@cmy82 That might be possible, but I'd probably implement it a little differently since we're moving to Slim 3 in the next version.  I'm thinking a parameter for the [`ForbiddenException`](https://github.com/userfrosting/bones/blob/master/app/system/Exception/ForbiddenException.php).

**Comment by alexweissman** [comment]
This is now supported in v4 with the custom error handler system.  Specific error-handling classes [can be mapped](https://github.com/userfrosting/UserFrosting/blob/b48f29eae3a62b235a00f982dbf9f80fd1c03c23/app/sprinkles/core/src/Handler/CoreErrorHandler.php#L82-L97) to different Exception classes, and then are automatically invoked when an uncaught Exception of that type is thrown.
