### ISSUE TITLE
Push notifications with UserFrosting

### ISSUE THREAD

**Issue by harding13** [userfrosting/UserFrosting#538]
Only a suggestion from the community.
UserFrosting is the REST platform for my iOS/Android app.
I'm trying to create push notifications system (one-to-all, one-to-one)

Which is a good point to start? This one?
https://github.com/hoymultimedia/Laravel-Pushwoosh

**Comment by alexweissman** [comment]
What's the advantage of using the Laravel adapter over the [base package](https://github.com/gomoob/php-pushwoosh)?

**Comment by harding13** [comment]
From that day i give a try to QuickBlox.
It has poor documentation but i have my push notifications running.
May i'll write a tutorial on how to implement it in UserFrosting (and in all you want)

**Comment by alexweissman** [comment]
Seems like there is a general demand for a true REST API...perhaps this should be implemented a core feature at some point.
