### ISSUE TITLE
Demo site offline

### ISSUE THREAD

**Issue by FireEmerald** [userfrosting/UserFrosting#539]
The demo site of UserFrosting is hosted here: **[uf-demo.alexanderweissman.com](http://uf-demo.alexanderweissman.com)**

Unfortunately the site seems to be down or unreachable. Would be great to take a look at a working demo.

**Comment by alexweissman** [comment]
Thanks, I'll look into this.

**Comment by alexweissman** [comment]
Should be back up now.  Please note that the demo is still running v0.3.0.  We're hoping to update it to the latest version soon, at the same time when we migrate it to its own VPS.
