### ISSUE TITLE
Unable to register new user

### ISSUE THREAD

**Issue by cmy82** [userfrosting/UserFrosting#542]
I started getting this error in version 3.1.4 and couldn't figure out why, so I migrated to 3.1.13. 

[03-May-2016 20:28:19 America/New_York] Error in /home/cmy/userfrosting/3.1.13/vendor/illuminate/database/Connection.php on line 624: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'user_name' in 'field list' (SQL: insert into `uf_user` (`user_name`, `display_name`, `email`, `password`, `locale`, `flag_verified`, `primary_group_id`, `title`, `updated_at`, `created_at`) values (*********, *********, ************@gmail.com, ****************, en_US, 0, 1, User, 2016-05-03 20:28:19, 2016-05-03 20:28:19)) 

The registration worked fine until I started adding my own code, even though I did not change anything with the registration page/functions. A few posts on stackexchange point to using the back tick instead of single quotes but that is controlled by Eloquent and can't be changed. But why would it only start to error after I added my code into the project? The only changes I made to the DB was to add a trigger to automatically add rows into a table in another DB that will be shared between two projects I'm working on.

![uf-error-registration](https://cloud.githubusercontent.com/assets/3430711/15002934/735c0d7e-1174-11e6-9a50-70cba59a49a5.png)

**Comment by alexweissman** [comment]
> Unknown column 'user_name' in 'field list'

So, this error means exactly what it says.  It can't find that column in your `uf_user` table.  Since you are working with multiple databases, is it possible that it is trying to issue that `insert` query to the other database?

**Comment by cmy82** [comment]
But I haven't changed any of the code and it worked before I started adding features into the app. I don't have Composer installed that I know of because I'm on a shared host, so all of my files are external to UF so to speak. I pass the UF app to a custom PHP script and use that to process the routing to my TWIG files, but I didn't really modify any of the actual UF code itself.

**Comment by alexweissman** [comment]
> don't have Composer installed that I know of because I'm on a shared host

Composer isn't something you need to install on your live hosting server, just your local dev environment.  You *do* have a local dev environment set up, don't you? :angry: 

You might want to join us in [chat](https://gitter.im/userfrosting/UserFrosting) for further discussion.

**Comment by cmy82** [comment]
I develop locally on my Windows PC and then FTP the files to my host, yes. But no, I thought Composer was needed on the host.

**Comment by alexweissman** [comment]
Composer is just a package manager.  It's only purpose is to download packages into your project, and generate autoload files.  It is not invoked during the actual running of your application.

Is it possible that your new code might have modified the `uf_user` table?  Can you confirm that there is indeed a `user_name` column in that table?

**Comment by cmy82** [comment]
Is it easier to reply here or in the chat?
Yes the UF tables haven't been modified except to add a trigger to export new users to a table in my application's DB.

**Comment by alexweissman** [comment]
Let us move to chat.  If we find a solution, we can post it back here.

**Comment by cmy82** [comment]
I resolved the issue. It wasn't with the initial trigger that I had but with a secondary trigger on the second table that was updating a table where column names matched and they weren't qualified. Thanks for the help.

**Comment by alexweissman** [comment]
No problem, glad you got it figured out!
