### ISSUE TITLE
Tutorials should include a guide to inspecting requests with the browser console

### ISSUE THREAD

**Issue by alexweissman** [userfrosting/UserFrosting#543]
Apparently, a lot of people don't know how to use their browser console to inspect requests and responses.  

Actually, I wouldn't be surprised if many of them don't even know what requests and responses *are*.  It's frighteningly common for people to learn "black-box" coding, and be able to achieve results (i.e., making a "form work") without understanding the underlying processes.

We should create a tutorial that guides people through inspecting different types of requests (GET, POST) achieved via different means (typing a URL into your browser's address bar, submitting a form, including a CSS or JS file, etc).

**Comment by nockieboy** [comment]
Sounds like a great idea - I know I'd benefit from such information (though I'd hate to think I'm the reason for this idea!) ;)

Perhaps it's easy for those in the industry to assume that everyone using UF is a web dev expert or has formal qualifications in the field, but I don't think that's necessarily the case, so there'd be a benefit to this sort of information being added to the tutorials.

**Comment by alexweissman** [comment]
> I'd hate to think I'm the reason for this idea!

Nope, there is a looooong history of people before you who have the same confusion ;-)

Actually, one of the core missions of UF is education - specifically, giving new developers a stepping stone from "coding a script" to developing full-blown, professional web applications.  So something like this, even though it's not directly related to the UF codebase itself, would definitely be appropriate for our community.

**Comment by alexweissman** [comment]
This is now available at https://learn.userfrosting.com/background/client-side.
