### ISSUE TITLE
Site settings in the database - is it worth it?

### ISSUE THREAD

**Issue by alexweissman** [userfrosting/UserFrosting#547]
One of the first things that UF does on each request, is [load some basic settings from the database](https://github.com/userfrosting/UserFrosting/blob/master/userfrosting/initialize.php#L178).  This includes:
- Site title
- Site author
- a bunch of boolean config options
- a whole bunch of other crap

The idea behind loading it from the database, is to make it easy to configure via the "Site settings" page.  But, is this really worth the extra DB query on each and every request?  How often do people really need to change these values, anyway?

**Comment by frostbitten** [comment]
I personally deplore having to deal with these settings in the database. One area of user experience concern, if the db connection fails then whatever error handling may happen won't be able to customize the message to the site without hardcoding such details.

**Comment by alexweissman** [comment]
So, one possibility is to move all of this to a config file (either *the* config file, or a separate one).  We could still have a frontend interface for the values, for example if they're stored in YAML format (assuming the web server has write permissions for this file).

**Comment by Netrilix** [comment]
I'm in favor of moving the stuff mentioned out of the database.

As far as where we should put it, I'm thinking maybe we have one config that's site-specific (site name, author, etc) and one that's server specific (mail settings, database settings, etc). This will make it easier for people to move a site to a new server without needing to dig through settings about the site itself.

Separating database and mail into distinct files would probably be fine too, but they're both server-related, so I'd probably lean toward leaving them together.

**Comment by alexweissman** [comment]
Cool, I like that.  with our fancy new config module, we could store them in separate files but still load them into a single config object in the code.

**Comment by cmy82** [comment]
Would it be possible/better to make that setting configurable by the user?

**Comment by alexweissman** [comment]
@cmy82 what do you mean?  Configure where the settings are stored?

**Comment by cmy82** [comment]
Yeah, like on install decide whether you want DB settings or a file based approach

**Comment by alexweissman** [comment]
We might be able to use something like [this package](https://github.com/anlutro/laravel-settings), which supports both JSON and database storage.  We would be adding an extra layer of complexity though, and if we make the decision part of the installer, we'll have to check whether we're using file- or db-based storage on each request.  This could be done with a simple `file_exists`, I guess.

**Comment by alexweissman** [comment]
After a conversation with @lcharette, it seems like most of the current site settings can be handled via the config files alone - after all, how often does one need to change the title of their site or the various timeouts?

What we can do is have "default" values defined in config files, and then for other types of settings that really do need to be changed on a day-to-day basis through the web interface, we can have a DB-driven Sprinkle that overrides values in the configuration files with values from a "settings" table.

**Comment by lcharette** [comment]
I'll add to @alexweissman comment that both file and db config will be integrated together in the `config` service and will also be cached using the new cache service.

**Comment by lcharette** [comment]
You can check out my Config Manager Sprinkle for V4.0 if you're interested in a UI for config settings: https://github.com/lcharette/UF_ConfigManager
