### ISSUE TITLE
includeJSBottom always include common?

### ISSUE THREAD

**Issue by TakeMeNL** [userfrosting/UserFrosting#549]
So i'm just curious.
If i only want the includeJSBottom a defined group it also returns the common group schem

So lets say i defined 
`$app->schema->registerJS("simple", "jquery-2.1.1.js");`
and i'm calling
`{% for item in includeJSBottom(page_group|default("simple")) %}`
in my layout-simple.twig

Why does it return the common and the simple?
Is that intentional?

**Comment by alexweissman** [comment]
The idea behind the "common" includes is that they would be included in every group.  In retrospect, it may not have been the best strategy.  

If you're feeling brave, you can try to integrate https://github.com/userfrosting/assets directly into your project.  This will become our default asset management system for the next version of UF.

**Comment by TakeMeNL** [comment]
If have made my own temp fix for now. Next version of UF i will change it to the assets.
I'm using UF for 4 days now and so far love it! It's kinda new to me with the whole composer and namespaces. But i'm leaning so jeej!

**Comment by alexweissman** [comment]
Awesome, glad that UF is working out for you and welcome to our community!
