### ISSUE TITLE
Possible to route to dev/prod configurations instead of making a setting?

### ISSUE THREAD

**Issue by cmy82** [userfrosting/UserFrosting#550]
Just wondering since using TWIG/Slim routing if it would be possible to configure a dev route instead of having to change the setting back and forth between dev and prod?

**Comment by alexweissman** [comment]
Do you mean a route that is only available in dev mode?  You could always just wrap it in an `if ($app->getMode() == "dev")` statement.

**Comment by alexweissman** [comment]
Kind of an interesting idea.  I wonder if this could be implemented as middleware.  Basically, a very simple middleware that checks whether the current environment mode matches a certain value, and allows the route to proceed or not:

```
$this->get('/debug', 'UserFrosting\Sprinkle\Site\Controller\TestController:debug')
        ->add('checkMode', 'dev');
```

Could be useful.

**Comment by cmy82** [comment]
Never noticed you responded last time. Kind of but what I was really getting at is having the settings for the dev/prod environments accessed via a route instead of having to edit the settings file each time. Kind of like lazy loading some of the configuration data.

**Comment by lcharette** [comment]
Actually, it could become a "db settings" as discussed in #547 and so accessible in the interface. Being able to go in "dev mode" could also be restricted using permissions system.

**Comment by alexweissman** [comment]
Oh, interesting.  My thinking has always been that the root account itself is a form of "dev mode".  See #464.

**Comment by lcharette** [comment]
I used a `get` tag once, something like `?debug=true`. Or a `debug.php?ff=normal/url/page.php` which basically enabled dev mode and alias the `ff` argument ( `include($_GET['ff']);`)

**Comment by cmy82** [comment]
Yes, but to keep from having two separate instances and having some features only available in development that can be promoted to prod by the changing of a route could be very convenient. I have two sites I'm creating based off UF and one relies on the other, and being able to 'link' the sites with the change of a route while it's still being developed would be very cool and time saving.

**Comment by cmy82** [comment]
Using the get tag would work but for multiple pages a route would be more convenient and less error prone than manually changing the page links

**Comment by alexweissman** [comment]
Ohh, so you're talking about having different _versions_ of the same route depending on which mode you're in?

**Comment by cmy82** [comment]
Yes, and different environment variables, etc as well as routes available

**Comment by lcharette** [comment]
Your issue is more of a dev/prod environment. Regardless of state of your app, you should have a dev setup locally for *both* sites and prod for both site. You test against both dev and then promote everything to prod?

The setting idea was more to help debug something that can't be reproduced in dev environment.

**Comment by cmy82** [comment]
Yes, but making both accessible by just changing the route and not having to change the settings file is the goal

**Comment by cmy82** [comment]
Basically wanting mysite.com/dev/route to be able to load different settings and have different routes available than mysite.com/route so that you could access both and have your prod and dev enviroments off of the same codebase/directory. that way you could say, have a link that you click the automatically takes you between enviroments by use of a cookie, etc without having to log in and out or run two separate sessions. Basically just a way to make me lazier, lol.

**Comment by alexweissman** [comment]
Why not just use access control, then?  Just limit the `dev/` routes so that only the root user can access them.

**Comment by cmy82** [comment]
That wouldn't allow for a different configuration (ie database, variables, etc) so as not to populate the production database, etc with test data.

**Comment by alexweissman** [comment]
Oh, I see.  I'm not sure, but perhaps v4's [environment modes](https://learn.userfrosting.com/sprinkles/contents#config) would solve part of the problem?

It seems like there might be a couple of different issues encapsulated by your suggestion.

**Comment by cmy82** [comment]
yes, there are a few caveats to the question. Sounds interesting, hopefully I won't have too much of a headache upgrading when time.

**Comment by alexweissman** [comment]
Ok, perhaps we can revisit this question once v4 is released and you get a chance to upgrade.

**Comment by alexweissman** [comment]
Let us know if this is still an issue for you in V4.
