### ISSUE TITLE
Not receiving new activation email after new user registration

### ISSUE THREAD

**Issue by picitelli** [userfrosting/UserFrosting#553]
After completing registration as a new user successfully, I'm prompted with the message: "You have successfully registered. You will soon receive an activation email. You must activate your account before logging in." The email never gets sent. If I go to resend activation email, enter username and email address that I just registered and hit "Resent Activation Email" button, I receive the resend activation email. The initial activate new email never gets sent out. I can confirm that the other email for resending the activation email is working.

Upon further investigation, the "mail/activate-new.twig" template reference on line 432 of controllers/AccountController.php won't get sent.

If I change line 432:
$template = $twig->loadTemplate("mail/activate-new.twig");

to 

$template = $twig->loadTemplate("mail/resend-activation.twig");

The email is sent out after completing registration as a new user. Replacing the markup of the activate-new.twig template with the markup from the resend-activation.twig template fixed my issue.

**Comment by alexweissman** [comment]
Hmm...I can't seem to replicate the problem.

How do you know that the email is not being sent out?  Does your mail server have a log that you can check?

**Comment by alexweissman** [comment]
Please let us know if you still need help with this.
