### ISSUE TITLE
RESTful API with Userfrosting?

### ISSUE THREAD

**Issue by guerriky** [userfrosting/UserFrosting#558]
Hello,
While developing on a UF fork for our embedded systems, a new request came from our customers.

They'd like me to expose a couple of functions that interact with the Userfrosting database in order to return some data.

I read this article to get started:
[http://coenraets.org/blog/2011/12/restful-services-with-jquery-php-and-the-slim-framework/](http://coenraets.org/blog/2011/12/restful-services-with-jquery-php-and-the-slim-framework/)

I tried a couple things, and ended up stuck on a problem with file userfrosting/middleware/CsrfGuard.php check() function.

Under normal conditions, this function would generate a csrf_token which it would store in the $_SESSION for later use.
It then gives out the token to the page, which will HAVE to pass it on following requests if it hopes to ever get some data.

On my conditions, I'm running a couple lines with a Python library to simulate the login request.

The order with which I do it is this:

GET .../public/account
(returns me a valid csrf_token)
POST .../public/account/login 
    with data:
    {
        "user_name" : "admin",
        "password" : "whatever",
        "rememberme" : "0",
        "csrf_token" : "f76ea98832018173f97e186e0bb4c20b42ca42a9ae9f35b2b018200146b60fc63cf5c356c906a6ca2fc44b3200fa7b12ccea2a951ce59f81aafa531261243942"
    }

What I get, however, is a 400 halt response, generated here:
[https://github.com/userfrosting/UserFrosting/blob/master/userfrosting/middleware/CsrfGuard.php#L102](https://github.com/userfrosting/UserFrosting/blob/master/userfrosting/middleware/CsrfGuard.php#L102)

What it does is it loses the stored $_SESSION value, and thus he sees this as me passing a non valid token.

I'm pretty sure I made a silly mistake somewhere, but in my head, this should be working fine.

Can you help me out on this one?

Thank you,
Riccardo

**Comment by guerriky** [comment]
Hi again,
figured it out in the end...

If anyone crashes into this problem, here's how it has to be fixed:

GET .../public/account
(returns me a valid csrf_token, as well as a valid session cookie)

POST .../public/account/login
with data:
{
"user_name" : "admin",
"password" : "whatever",
"rememberme" : "0",
"csrf_token" : "f76ea98832018173f97e186e0bb4c20b42ca42a9ae9f35b2b018200146b60fc63cf5c356c906a6ca2fc44b3200fa7b12ccea2a951ce59f81aafa531261243942"
}
and the cookie is the one I have in the previous request.

Here is my complete Python code (client, of course):

import requests
r= requests.get("http://localhost:8888/acontrol/user-frosting/public/")
# Scan r.text to get the csrf token
r= requests.post("http://localhost:8888/acontrol/user-frosting/public/account/login",data={"user_name" : "admin","password" : "whatever","rememberme" : "0","csrf_token" : "token_that_i_got_from_r_dot_text"},cookies=r.cookies);

Bye,
Riccardo

**Comment by spurgeonbj** [comment]
Thanks Alex & Guerriky!
