### ISSUE TITLE
Move website and demo site to a VPS

### ISSUE THREAD

**Issue by alexweissman** [userfrosting/UserFrosting#559]
Currently, we host our website on [Github pages](https://pages.github.com/), and our demo site on an embarrassing, legacy shared hosting server.

Github pages is nice because it offloads the bandwidth to Github, but it comes at a price - we can't have any real interactive content.  The best that Pages can do is some basic templating with [Jekyll](https://help.github.com/articles/using-jekyll-as-a-static-site-generator-with-github-pages/) - if we want user accounts or a forum, we'd need to self-host.  This would also be a nice way to more tightly integrate the demo site into the website.

We've gotten some [donations](https://pledgie.com/campaigns/29583) over the past year, so we have enough of a runway to pay for a basic [droplet with Digital Ocean](https://www.digitalocean.com/pricing/) for some time.  If donations scale with site traffic, then additional droplets could be added as needed ;-)

**Comment by spurgeonbj** [comment]
Hi Alex,

Greetings!

Thanks for the awesome product!

Just a suggestion, you can save an year's cost trying an EC2 instance on
AWS..

Thanks!
Warm regards
Spurgeon

**Comment by alexweissman** [comment]
This is partially done!  https://demo.userfrosting.com

**Comment by alexweissman** [comment]
Repo for new website: https://github.com/userfrosting/userfrosting-web
