### ISSUE TITLE
Localisation of core pages

### ISSUE THREAD

**Issue by lcharette** [userfrosting/UserFrosting#563]
Sites settings, user settings and login should be fully localized to be run on different languages out of the box. 

Dashboard and other non working / demo features are ok since they'll get deleted anyway...

**Comment by Netrilix** [comment]
What you're asking for was mentioned as a goal in #360, but we'll consider #563 to be the official issue regarding the switch from only translating messages to translating the core pages themselves.

**Comment by alexweissman** [comment]
You mean for all text used throughout the site?

**Comment by Netrilix** [comment]
Yeah, you mentioned it [here](https://github.com/userfrosting/UserFrosting/issues/360#issuecomment-170659505) as kind of an afterthought. It's a good goal, but definitely a long-term one.

**Comment by lcharette** [comment]
You do locale all the way or not at all lol. At least for all the pages that are going to stay on a full website (aka the login screen, the dashboard is just demo). But yeah, one page at a time.

**Comment by alexweissman** [comment]
gotcha.  Yes, let's try to take this into consideration for v4.  I still the like the "localized template" approach.

**Comment by lcharette** [comment]
This is 90% done on the current V4.0 Alpha release. French and English is available where possible. The remaining translation will need more work and I'll open separate issue for them.

**Comment by alexweissman** [comment]
So, are we giving up on translating entire templates?

> we'll consider #563 to be the official issue regarding the switch from only translating messages to translating the core pages themselves

**Comment by lcharette** [comment]
Well, not really. The parts left to translate are related to the Handlebar table ( `verbatim` problem) and email. We just need to open new issues for them.

**Comment by alexweissman** [comment]
makeitso.gif
