### ISSUE TITLE
AJAX API for creating username / password programmatically

### ISSUE THREAD

**Issue by spurgeonbj** [userfrosting/UserFrosting#568]
Hi,

Greetings!

I'm not sure whether this is the right place to post this query, kindly forgive if it isnt.

Thanks for the great stuff. UF has for sure reduced our work dramatically in developing a user based system.

In our use case, we wish to generate username through code depending on conditions like (availability of unique email id, unique mobile no or concatenated string of username and random characters, in that order) and also generate a random password, instead of using form fields to let the user choose his username / password interactively.

Are there any APIs existing to do this through AJAX as of now? 

I noticed that the username availability is done after post in the present product. Wouldnt it be nice to have that too checked through AJAX on field change event?

ditto for email id.

If APIs are not available, could you kindly help in pointing me to some sample code within UF, which can be modified to implement this?

Thanks once again!

Warm regards and gratitude,
Spurgeon

**Comment by alexweissman** [comment]
Ref #385, #558.

**Comment by spurgeonbj** [comment]
Dear Alex,

Greetings!

Thanks a ton for your lightning response!
