### ISSUE TITLE
Can't load stylesheets and javascript

### ISSUE THREAD

**Issue by Louis-Ca** [userfrosting/UserFrosting#571]
I'm getting the error:
`Mixed Content: The page at '[url]' was loaded over HTTPS, but requested an insecure stylesheet '[url]/public/css/font-awesome-4.3.0.css'. This request has been blocked; the content must be served over HTTPS.`
for every single stylesheet and javascript file.

I have no idea how to make these files load over HTTPS, or even find where the pages link to these stylesheets!

**Comment by Netrilix** [comment]
There's a commented line in `.htaccess` that'll switch the entire site over to SSL. That should fix your issue.

**Comment by Louis-Ca** [comment]
Thanks for the quick response.

I uncommented these lines
`  RewriteCond %{HTTPS} !=on
   RewriteRule (.*) https://%{HTTP_HOST}%{REQUEST_URI} [R=301,L]`

under the section
`    # Uncomment the next two lines to forward all HTTP to HTTPS
`

but chrome now gives the error: [url] redirected you too many times.

**Comment by alexweissman** [comment]
Perhaps you have some rules in a virtualhost file that are causing a redirect loop?

**Comment by Louis-Ca** [comment]
Any idea what these rules could cause this? I have no idea what I'm looking for.

**Comment by alexweissman** [comment]
Well, a good place to start would be to use your browser console to see the actual series of requests that are being made.  So, you can see what the server is trying to redirect you to.

**Comment by Louis-Ca** [comment]
Unfortunately, my chrome console tells me nothing. However, I can show you what is appearing in access.log although I'm not sure how helpful it is.

[Pastebin of access.log](http://pastebin.com/0hfjtw3x)

**Comment by Louis-Ca** [comment]
Unfortunately, my chrome console tells me nothing. However, I can show you what is appearing in access.log although I'm not sure how helpful it is.

[Pastebin of access.log](http://pastebin.com/0hfjtw3x)

**Comment by Louis-Ca** [comment]
Unforunately, Chrome's console doesn't tell me anything. I'm not sure if it's useful, but access.log shows this:

`10.240.0.196 - - [12/Jul/2016:15:47:10 +0000] "GET /public/index.php HTTP/1.1" 301 671 "https://ide.c9.io/[removed]/[removed]" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36"`

`10.240.0.188 - - [12/Jul/2016:15:47:11 +0000] "GET /public/index.php HTTP/1.1" 301 671 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36"`

on and on... there are about 30 lines of that.

**Comment by Netrilix** [comment]
Are you able to sign into [chat](https://chat.userfrosting.com)?

**Comment by Louis-Ca** [comment]
Sorry, I know it isn't ideal but in the end I just had to stop using HTTPS.

**Comment by alexweissman** [comment]
You should really figure this out.  It's not just "not ideal" - you're putting all your users at risk by potentially exposing their passwords over any unsecured network.  Where are you hosting your site?

**Comment by Louis-Ca** [comment]
By "not ideal" I meant it isn't ideal just to close the issue without solving it; I won't make my site public until I have it sorted. At the moment, I just need to get on with development.

**Comment by alexweissman** [comment]
Ah, gotcha.  Btw, just gonna cross-reference your SO question here: http://stackoverflow.com/questions/38289958/userfrosting-installation-pages-showing-with-no-css.  We should move our discussion to [chat](https://chat.userfrosting.com), and then update your SO question when we find an answer.
