### ISSUE TITLE
Add sanitizers to register.json

### ISSUE THREAD

**Issue by lcharette** [userfrosting/UserFrosting#574]
As discussed on chat, `"sanitizers" : { "raw" : {}}` needs to be added to `register.json` scheme to match `user-create.json` scheme. Will fix weird behavior when a `'` is used in user_name.

(I can't create pull request right now as I already have one open in the master branch of my fork)

**Comment by alexweissman** [comment]
Yes, sounds good as a hotfix.  For others finding this issue, please note that `sanitizers` as a whole are deprecated in Fortress v2.  Instead, we will support optional [data transformations](https://github.com/userfrosting/fortress#data-transformation).

**Comment by Netrilix** [comment]
This also covers `login.json`. As it stands, `register.json` and `login.json` match eachother, so logins are possible. Users created by the admin control panel, however, will not be able to log in if they have HTML entities in their username. Any fix should include an upgrade of previous usernames to the proper format.

**Comment by Netrilix** [comment]
As discussed in chat, there are two options:

- Upgrade users as they log in
- Upgrade all users if their database version is less than the version this fix is added in

**Comment by alexweissman** [comment]
Any update on fixing this in 0.3.1?

**Comment by alexweissman** [comment]
If someone runs into this problem and wants to do a PR for a fix, feel free to re-open this issue.  Otherwise, I suggest we concentrate our efforts on V4.
