### ISSUE TITLE
No way to access the PHPMailer object in Notification

### ISSUE THREAD

**Issue by pengimo** [userfrosting/UserFrosting#575]
Failing to send email when using PHP V5.6 or above due to an invalid SSL certificate. This occurs when a locally generated SSL certificate (unsigned) is used for ssl or tls access to the mail server.

See here...

http://stackoverflow.com/questions/32694103/phpmailer-openssl-error

The fix is documented but I can't work out how to implement it.

**Comment by alexweissman** [comment]
Oh, we don't have the `PHPMailer` instance exposed in [`Notification`](https://github.com/userfrosting/UserFrosting/blob/master/userfrosting/models/notify/Notification.php) so yeah, that would make it difficult.  Yeah, we should probably figure out a way to do this.

**Comment by odoell** [comment]
I also stumbled over this feature... ;-)

I solved it for now with following code in the Notification class send function.
Insert it in the send function right after the Phpmailer instance is created...

This solves the local development proplem of invalid SSL certificates.

$mail->CharSet = 'UTF-8';

        $mode = static::$app->getMode();
        if ($mode == 'dev') {
          $mail->SMTPOptions = array(
            'ssl' => array(
              'verify_peer' => false,
              'verify_peer_name' => false,
              'allow_self_signed' => true
            )
          );
          $mail->SMTPDebug = 2;
        }

**Comment by alexweissman** [comment]
This is handled very nicely in v4 with the `mail` service, but someone should probably fix this in 0.3.1 as well...

**Comment by alexweissman** [comment]
If someone is still having problems with this and wants to do a PR for a fix, feel free to re-open this issue.  Otherwise, I suggest we concentrate our efforts on V4.
