### ISSUE TITLE
Translate Doc to pt_BR

### ISSUE THREAD

**Issue by selique** [userfrosting/UserFrosting#582]
I propose translate the documentation of site and call other developers for translate docs in other language (not only portuguese) 

https://pontoon.mozilla.org/ thats great tool for translate!

**Comment by lcharette** [comment]
See #563. For me at least, it's more urgent to translate UF itself.

(As with UF, I can provide French translation when needed)

**Comment by alexweissman** [comment]
This is definitely a good idea.  We're hosting the site on Github Pages right now, so we'd have to figure out a good way to do this with Jekyll.  Or, we can wait until we migrate the site over to our own hosting.

**Comment by alexweissman** [comment]
learn.userfrosting.com is built with Grav, which does support multi-language sites.  See https://learn.getgrav.org/content/multi-language#multi-language-basics

So, I think this is easily doable.
