### ISSUE TITLE
Can't register master account and websites stop responding

### ISSUE THREAD

**Issue by waratoco** [userfrosting/UserFrosting#584]
Hi,

Having a major issue when creating the initial master account. I'm having the same issue as I have seen others encounter with the registration "spinning wheel" working for a second and then not registering. However, I can't find out what the issue is because whenever I attempt to register, I lose access to the entire server (the domain of my hosting provider/my two domains/my various subdomains where one has UF). What on earth is going on? I can't access anything for another 4-5 hours and then the same issue occurs because my connection simply "times out"

Thanks

edit: added more clarity

**Comment by alexweissman** [comment]
You might want to talk to your hosting provider about this.  *No* web error should take an entire server down.

Once you get this sorted out, we can try to track down your error.  I should also take this opportunity to remind you to set up a local development environment, if you haven't already done so.  Then you can perform the installation on your own computer, and export the database schema from your computer to your host's database when you are ready to deploy.

**Comment by waratoco** [comment]
Hi, thank you for the response. I have just realised that it only applies to me, others can access the site. I'll set up a local environment and report back.

Sent by MailWise<http://www.mail-wise.com/installation/2> – See your emails as clean, short chats.


-------- Original Message --------

**Comment by alexweissman** [comment]
Ah.  In that case, it could be your browser caching some bad redirects.

**Comment by alexweissman** [comment]
Please join us in [chat](https://chat.userfrosting.com) if you are still having problems.
