### ISSUE TITLE
Mass sending password reset email to all of user

### ISSUE THREAD

**Issue by baoc75** [userfrosting/UserFrosting#592]
I am migrating from a old user management system to Userfrosting, because they are using different password hashing so it required to reset password. 
Now, how can I resend password reset email to all of user? I couldn't found any documents about it on Userfrosting's homepage or on Github.

**Comment by lcharette** [comment]
Hi! 

Come see us on the chat for general question : http://chat.userfrosting.com

I think you might have this problem backward. No need to sent an email to every user at once. When a user wants to sign in (with whatever password they enter), shown them an error explaining they need to reset their password (And why) and send them a new one or a link to create a new one to their original email. If you blast an email and people don't go to your site right away, they'll forget about that email. 

Same goes if the email is no longer valid. At least, when they try to login, they'll see the error and (hopefully) contact you if they don't get any email.

In any case, you'll need to write your own code to do it.

**Comment by baoc75** [comment]
@lcharette Thank you, yeah I guess I should do that way. People will mostly forgot about it :smile:

**Comment by alexweissman** [comment]
This is funny, I've been getting a lot of emails from various websites recently telling me to update my password.  Seems like everyone is trying to strengthen their hashes lately.
