### ISSUE TITLE
Remove display_name from form ?

### ISSUE THREAD

**Issue by reubenrodrigues24** [userfrosting/UserFrosting#593]
How can I remove the display name from the form?

**Comment by reubenrodrigues24** [comment]
Tried following the steps in reverse for adding the fields. No luck. The field is still there in the form.

**Comment by alexweissman** [comment]
Hi @reubenrodrigues24,

We try to reserve the Github issue tracker for bugs and feature requests.  Please join us in [chat](https://chat.userfrosting.com) to discuss the details of what you are trying to do.
