### ISSUE TITLE
Declaration of UserFrosting\User::fresh() should be compatible with

### ISSUE THREAD

**Issue by harding13** [userfrosting/UserFrosting#594]
This isn't my first UF installation but now i got this strange error

`PHP Strict Standards:  Declaration of UserFrosting\User::fresh() should be compatible with Illuminate\Database\Eloquent\Model::fresh(array $with = Array) in /home/vpblysfv/public_html/userfrosting/models/database/User.php on line 0`

in the error_log i got many of these.

**Comment by Jinkers** [comment]
Oh thank goodness so I'm not the only one (thought I was going insane). Only difference is mine occurs on line 598 (some custom Data Model functions are added to User.php that I need).

**Comment by harding13** [comment]
If i turn on "display_errors" in the config, that error stops the login. Is this so for you?

**Comment by Netrilix** [comment]
This error was fixed on version 0.3.1.20.

If you're just getting started, the easiest way to fix it might just be to reinstall with a fresh download of the new version. If you've already got a project going, you can either sync your repository with this one to get the update, or just change the line with the error to match this one:

https://github.com/userfrosting/UserFrosting/blob/master/userfrosting/models/database/User.php#L94
