### ISSUE TITLE
Class 'UserFrosting\\MyController' not found

### ISSUE THREAD

**Issue by vigiman** [userfrosting/UserFrosting#595]
Hi,
great job with this system, really liked it
Im having a problem with running a new controller error log shown something like:
Class 'UserFrosting\\MyController' not found
i figured out a composer is might be missng, i use a linux private server, so i thought i should get an ssh connection as the admin and I typed as shown in:
https://getcomposer.org/download/
php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
php -r "if (hash_file('SHA384', 'composer-setup.php') === 'e115a8dc7871f15d853148a7fbac7da27d6c0030b848d9b3dc09e2a0388afed865e6a3d6b3c0fad45c48e2b5fc1196ae') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
php composer-setup.php
php -r "unlink('composer-setup.php');"

still the same output to error log
should i put it in a special directory? maybe i'm doing something wrong?

**Comment by lcharette** [comment]
We try to reserve the Github issue tracker for bug reports and feature requests.  Please join us in [chat](https://chat.userfrosting.com) to discuss the details of what you are trying to do.

That being said, once composer installed, you actually have to run the command to update everything `composer update` or `php composer.phar update`

**Comment by alexweissman** [comment]
Join us in chat if you're still having trouble!
