### ISSUE TITLE
Not sure if it's possible to install UserFrosting on a shared server...?

### ISSUE THREAD

**Issue by yousies** [userfrosting/UserFrosting#596]
Hi!  I've always re-invent the wheel when I do the login stuff and, this time, I thought it would be good to try an existing UM system.  UserFrosting looks really cool so I figure I'd give it a try.  The installation instructions advises an installation on the localhost, which is sensible.  However, at some point, I would like to migrate over to the shared hosting service I am using, which is Dreamhost.  Dreamhost meets all the requirements for UserFrosting but I am not sure how to adapt the instructions provided, where sudo is available, to the hosting service, where I do not have root access.  Is it possible to install UserFrosting on such shared hosting services?

**Comment by Netrilix** [comment]
Without command line access, you won't be able to run Composer to update your class autoloaders, but that's actually fine. When you develop locally, you'll generate those files and then just upload them to the server when they're ready.

You'll also need to rename `public` to whatever your shared hosting uses as its public folder (`public_html`, `www`, etc), or just copy the contents of `public` into your web root directory.

People have also run into issues with `mod_rewrite` not being enabled or configured correctly. UserFrosting's URL routing system is run on Slim, which uses `mod_rewrite` heavily. If you run into trouble there, hopefully your host will be able to make any changes needed.

**Comment by yousies** [comment]
Thanks for the pointers.  I checked that mod_rewrite is working on Dreamhost.  However, the UserFrosting installation instructions needs the httpd.conf file to be edited.  Editing this file requires root access.  I am on a shared hosting service and so I do not have root access, which is why it seems to me that one cannot use UserFrosting on a shared hosting service.  But, is there a way to use it without having to edit the httpd.conf file?

**Comment by Netrilix** [comment]
That step is to ensure that the `.htaccess` file will be read properly. If your host is configured to allow all of the options used in the `.htaccess`, you don't need to edit the `httpd.conf`.

Here's the `.htaccess` so you can see which parameters are used:
https://github.com/userfrosting/UserFrosting/blob/master/public/.htaccess

**Comment by yousies** [comment]
Got it working - thanks for all your help!!

**Comment by alexweissman** [comment]
Feel free to join us in [chat](https://chat.userfrosting.com) if you run into any more problems!
