### ISSUE TITLE
Double modal window

### ISSUE THREAD

**Issue by pszemco** [userfrosting/UserFrosting#598]
How in the window modal delete (eg users) to call another modal window with the database table (eg group list)?

**Comment by JoshNorris** [comment]
@pszemco Best asking questions in the UserFrosting Chat (use the support room). https://chat.userfrosting.com/

**Comment by alexweissman** [comment]
We might actually want to pay attention to this in UF4, especially if we start relying on modals to do more - like for example, a login modal.  It might have a "register" button that should either launch a new modal, or completely replace the contents of the current modal.

**Comment by ryan-nash** [comment]
"Bootstrap only supports one modal window at a time. Nested modals aren’t supported as we believe them to be poor user experiences." - http://v4-alpha.getbootstrap.com/components/modal/ 

Personally I replace the contents of the modal with HTML hidden on the page, but AJAX is fine too.

**Comment by alexweissman** [comment]
@ryan-nash I think what @pszemco meant is something that makes it easy to support a series of modal panels, hiding or replacing the first modal with a new modal.  For example, this could be useful in a click-through wizard of some sort.
