### ISSUE TITLE
How to mkae it an admin-only website?

### ISSUE THREAD

**Issue by leecollings** [userfrosting/UserFrosting#604]
I plan to use UserFrosting as part of an admin-only management portal, so I have a seperate website on the main domain, and UF on a subdomain called my.*

Is it possible to re-configure to always redirect to the Dashboard when visiting the URL? By doing so, will this always perform the isGuest check, and redirect to a login page if true?

**Comment by JoshNorris** [comment]
Questions are best asked on the [userfrosting chat](https://chat.userfrosting.com/) in the #support channel.

**Comment by lcharette** [comment]
> Is it possible to re-configure to always redirect to the Dashboard when visiting the URL? By doing so, will this always perform the isGuest check, and redirect to a login page if true?

Yup! Using the new V4, you can just overwrite the routes and/or controller for the pages you don't want and make them redirect to the dashboard.  Like Josh said, come chat with us if you need assistance doing so.
