### ISSUE TITLE
Error initializing on MySQL 5.7

### ISSUE THREAD

**Issue by inghamn** [userfrosting/UserFrosting#605]
It would be nice to have this work using MySQL 5.7 and above, so we do not need to downgrade our servers.

The allowed defult values for datetime and timestamps changed going from MySQL 5.6 to 5.7.
Setting timestamps (or datetimes) to the current time now needs to be declared explicitly:

```sql
update table user_event add occurred_at timestamp not null default CURRENT_TIMESTAMP;
```
Error in /sites/userfrosting/userfrosting/vendor/illuminate/database/Connection.php on line 624: SQLSTATE[42000]: Syntax error or access violation: 1067 Invalid default value for 'occurred_at' (SQL: create table `user_event` (`id` int unsigned not null auto_increment primary key, `user_id` int unsigned not null, `event_type` varchar(255) not null comment "An identifier used to track the type of event.", `occurred_at` timestamp default 0 not null, `description` text not null) default character set utf8 collate utf8_unicode_ci engine = InnoDB)

```
#0 /sites/userfrosting/userfrosting/vendor/illuminate/database/Connection.php(580): Illuminate\\Database\\Connection->runQueryCallback('create table `u...', Array, Object(Closure))
#1 /sites/userfrosting/userfrosting/vendor/illuminate/database/Connection.php(363): Illuminate\\Database\\Connection->run('create table `u...', Array, Object(Closure))
#2 /sites/userfrosting/userfrosting/vendor/illuminate/database/Schema/Blueprint.php(63): Illuminate\\Database\\Connection->statement('create table `u...')
#3 /sites/userfrosting/userfrosting/vendor/illuminate/database/Schema/Builder.php(188): Illuminate\\Database\\Schema\\Blueprint->build(Object(Illuminate\\Database\\MySqlConnection), Object(Illuminate\\Database\\Schema\\Grammars\\MySqlGrammar))
#4 /sites/userfrosting/userfrosting/vendor/illuminate/database/Schema/Builder.php(131): Illuminate\\Database\\Schema\\Builder->build(Object(Illuminate\\Database\\Schema\\Blueprint))
#5 /sites/userfrosting/userfrosting/models/database/Database.php(282): Illuminate\\Database\\Schema\\Builder->create('user_event', Object(Closure))
#6 /sites/userfrosting/userfrosting/controllers/InstallController.php(79): UserFrosting\\Database::install()
#7 /sites/userfrosting/public/index.php(328): UserFrosting\\InstallController->pageSetupDB()
#8 [internal function]: {closure}()
#9 /sites/userfrosting/userfrosting/vendor/slim/slim/Slim/Route.php(468): call_user_func_array(Object(Closure), Array)
#10 /sites/userfrosting/userfrosting/vendor/slim/slim/Slim/Slim.php(1357): Slim\\Route->dispatch()
#11 /sites/userfrosting/userfrosting/vendor/slim/slim/Slim/Middleware/Flash.php(85): Slim\\Slim->call()
#12 /sites/userfrosting/userfrosting/vendor/slim/slim/Slim/Middleware/MethodOverride.php(92): Slim\\Middleware\\Flash->call()
#13 /sites/userfrosting/userfrosting/middleware/CsrfGuard.php(51): Slim\\Middleware\\MethodOverride->call()
#14 /sites/userfrosting/userfrosting/middleware/usersession/UserSession.php(27): Slim\\Extras\\Middleware\\CsrfGuard->call()
#15 /sites/userfrosting/userfrosting/vendor/slim/slim/Slim/Slim.php(1302): UserFrosting\\UserSession->call()
#16 /sites/userfrosting/public/index.php(416): Slim\\Slim->run()
#17 {main}
```

**Comment by lcharette** [comment]
Check your version. This should be fixed in #603 .

**Comment by inghamn** [comment]
I just cloned from the master branch, and am up to date.  the initialize still has the error

**Comment by inghamn** [comment]
#603 only dealt with the timestamp in the user table, but missed the problem in the user_event table.

**Comment by lcharette** [comment]
Yup. That What I just saw. this one here : https://github.com/userfrosting/UserFrosting/blob/89101e4e96670ae305dd85be0ba9c6c462dedb2e/userfrosting/models/database/Database.php#L277

**Comment by alexweissman** [comment]
So, if I understand correctly, every timestamp needs to either be explicitly declared as a `nullableTimestamp`, or it needs to have a default value?

**Comment by Netrilix** [comment]
Non-zero default, yes.

**Comment by lcharette** [comment]
Doesn't `nullableTimestamp` create the `created_at` and `updated_at` fields? So the dafult would be required.

See this reference : https://github.com/laravel/framework/issues/3602

**Comment by alexweissman** [comment]
It's really strange - the documentation for the `nullableTimestamps` field says: 

> `$table->nullableTimestamps();` 	Same as `timestamps()`.

**Comment by lcharette** [comment]
`timestamps` and `timestamp` is not the same ;)

So `$table->timestamp('occurred_at')->nullable();` should do the trick.  Can you test it @inghamn ?

**Comment by inghamn** [comment]
Success:
```php
<?php
# This worked
$table->timestamp('occurred_at')->nullable();
```

**Comment by alexweissman** [comment]
Ah, good catch.  So, I propose that we use:

```
$table->timestamp('foo')->useCurrent();
```

Is this going to cause a problem for older versions of MySQL, or other databases?  Maybe @Silic0nS0ldier can weigh in on this.

**Comment by inghamn** [comment]
Is it desired, though, that occured_at actually be allowed null?  It seems the original intent was to have the database generate timestamps for you, instead of needing to do it in PHP

**Comment by Netrilix** [comment]
`useCurrent()` should only cause problems with older versions of MySQL if there are multiple uses of it in the same table. On the `user_event` table, we're only using it once, so it should be fine.

**Comment by inghamn** [comment]
If it is a timestamp, then it is safe, in all version of MySQL to use CURRENT_TIMESTAMP as the default value.  Older versions of MySQL only allowed a single timestamp field per table.

**Comment by lcharette** [comment]
> It's really strange - the documentation for the nullableTimestamps field says:

FYI, apparently it changed from Laravel 4.x and 5.x. Which version is UFV3 using ?

**Comment by inghamn** [comment]
MySQL 5.7 unified the datetime, and timestamp data types to be the same, and allowed multiple timestamps to be autoinitialized.

In prior versions, the datetime type could not use CURRENT_TIMESTAMP as the default value

**Comment by Netrilix** [comment]
@lcharette It's on `5.0.33`, which was the last version that supported `PHP 5.4`.

**Comment by inghamn** [comment]
userCurrent(); results in the db library attempting to use 0, instead of CURRENT_TIMESTAMP.  0 is not valid in newer version of MySQL

**Comment by alexweissman** [comment]
Well crap.  So I guess `nullable` it is, then?  UF4 uses newer versions of `illuminate/database`, so hopefully we can use `useCurrent()` with UF4.

**Comment by Silic0nS0ldier** [comment]
I don't know how `useCurrent` works with SQL Server (should support it as internally `GETDATE()` has been around since SQL Server 2008).

I've already tested `nullable` on `timestamp('occurred_at')` with SQL Server from the previous MySQL bugfix, so it shouldn't cause any issues with it. (only reason didn't make the cut is `timestamp('occurred_at')` didn't trigger the zero-date conflict, oddly enough unlike `timestamps()`).

**Comment by alexweissman** [comment]
Ok, I've pushed the fix to `hotfix-development`.  If that works for everyone, we can do another release.  I also kind of wonder if this is related to #601.
