### ISSUE TITLE
UserFrosting-Dev error

### ISSUE THREAD

**Issue by X-Anonymous-Y** [userfrosting/UserFrosting#608]
UF-4 Dev:

fortress-jqueryvalidation-methods.js:1 Uncaught TypeError: Cannot read property 'addMethod' of undefined
    at fortress-jqueryvalidation-methods.js:1
uf-jqueryvalidation-config.js:4 Uncaught TypeError: Cannot read property 'setDefaults' of undefined
    at uf-jqueryvalidation-config.js:4
localhost/:329 Uncaught TypeError: $(...).carousel is not a function
    at localhost/:329

I have not changed, or modified.

I thought first I made a mistake. Then I loaded a new copy and tested.

Same error message

**Comment by alexweissman** [comment]
Did you [install the Bower dependencies](https://learn.userfrosting.com/basics/installation#userfrosting-assets)?

**Comment by X-Anonymous-Y** [comment]
After I have run "composer install"
All necessary files are loaded. Or is that wrong?

When I look in:
"C: \ ...... \ app \ vendor \ userfrosting \ assets \ src \ assets"
Then all files are there.

**Comment by Silic0nS0ldier** [comment]
In the latest dev version we've introduced Bower for frontend package management, and as such there is now an extra step. Head over to https://learn.userfrosting.com/basics/installation and follow the steps related to installing node.js (if its not installed), installing the npm dependencies, and finally installing the UserFrosting assets.

**Comment by X-Anonymous-Y** [comment]
Ok Thanks...

Now its Work!

Forgot Npm install
