### ISSUE TITLE
Simple question about rest api

### ISSUE THREAD

**Issue by smail2133** [userfrosting/UserFrosting#613]
Hello guys. I'm happy using this "framework". So, I have little bit question. I'm new php developer. So, after review code I found 1 rest api call method. How I can execute get method ???
`curl -X GET http://localhost/userfrosting/public/api/users?csrf_token=sejdlfjegemp16uvif0fbfj9l3`
is not work for me. Also I want read guide to add another methods to api. Thanks.

**Comment by alexweissman** [comment]
It would be best to ask this in [chat](https://chat.userfrosting.com).  The issue tracker is reserved for bug reports and feature requests.
