### ISSUE TITLE
Improve Build Process

### ISSUE THREAD

**Issue by Silic0nS0ldier** [userfrosting/UserFrosting#615]
The process of building asset bundles, and copying files is currently unreliable, and over complicated. While the majority works, and there are workarounds for what doesn't, this needs to be addressed. There is also opportunity to reduce the number of required steps for building overall.

- [x] Fix copy task.
- [x] Simplify bundling process.
- [x] Attempt to improve bower reliability.
- [x] String build related tasks together.
- [x] Implement CSS import rewriting

**Comment by alexweissman** [comment]
We should also look into webpack :-D

**Comment by Silic0nS0ldier** [comment]
Fixes related to being release ready have been rolled out as of bc81a84a24e83a65f0938df955a72b8140ffbae8.

Further improvements will require an overhaul of the bundler, which will take time. As such, milestone is being moved back to 4.1.

**Comment by Silic0nS0ldier** [comment]
Gulp v4 has been officially published on npm. Latest version is significantly better at orchestrating time sensitive tasks, so we should be able to drastically the manual building processes.

Quite a few dependencies were dropped too, which should speed up setups. Catch though, is that `gulp-uf-bundle-assets` is tied down to v3, so we'll have to address that to get any real benefit (thanks to it using gulp internally, against recommendations. _shakes fist_).

My current plans for getting this done are looking like:

1. I find an object validator that meets the requirements for (2), or make a brand new one.
2. Create a asset bundler that is independent of gulp, and integrate and adapt it for UF and gulp via separate libraries. (modularity ✨)
3. Integrate the new bundler with UF, updating to gulp v4 and simplifying bundling process, in the process.
4. Test everything.

**Comment by Silic0nS0ldier** [comment]
Decided to have a poke at the dependencies used in the JS side of things. There are approx 79 packages that are having duplicates downloaded (frequently 3+) to address the needs of all components. This is nuts. Its also extremely risky having incompatible versions of objects thrown around. The planned improvements should ease most of this insanity, but putting some work into working out the conflicts where possible should be a goal as well. Particular since it'll improve build process stability, and greatly reduce the amount of space needed (57.2MB+ across 634+ packages).

**Comment by Silic0nS0ldier** [comment]
One major thing I want to address before this work gets released. Improving the reporting of non-flat dependency trees.

As part of achieving this I want to:
- [ ] Generate a `package.json` with locked down versions (catching what issues we can)
- [ ] Use npm instead of yarn (since `--flat` doesn't look to be getting a non-interactive mode for a long time yet)
- [ ] Check `package-lock.json` for duplicates afterwards (easy to do, harder to report on)

**Comment by Silic0nS0ldier** [comment]
The flat constraint has been addressed with the application of browserify against compatible dependencies.

All relevant work for the build improvements has been committed. There is room for improvement (always is) however the remaining big ticket items like userfrosting/gulp-uf-bundle-assets#11 are as demonstrated being tracked independently.
