### ISSUE TITLE
Automatically load sprinkle's Middleware

### ISSUE THREAD

**Issue by lcharette** [userfrosting/UserFrosting#617]
Currently, the only way for a Sprinkle to add a global middleware is to edit `public/index.php`. A Sprinkle should be able to register it's own middleware to avoid editing a core UF file.

This currently have an impact on this Sprinkle : https://github.com/lcharette/UF_ConfigManager#edit-indexphp

**Comment by alexweissman** [comment]
version 4.1 will remodel Sprinkle bootstrap classes as [Event subscribers](http://symfony.com/doc/current/components/event_dispatcher.html), which means that Sprinkles can subscribe to the new `onAddGlobalMiddleware` event to add middleware.

**Comment by alexweissman** [comment]
Implemented in `develop`.
