### ISSUE TITLE
npm error

### ISSUE THREAD

**Issue by isaacdunyo** [userfrosting/UserFrosting#618]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\IV\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install' ]
2 info using npm@1.3.26
3 info using node@v7.4.0
4 error install Couldn't read dependencies
5 error Error: Invalid name: "@userfrosting/userfrosting"
5 error     at ensureValidName (C:\Users\IV\AppData\Roaming\npm\node_modules\npm\node_modules\read-package-json\node_modules\normalize-package-data\lib\fixer.js:297:15)
5 error     at Object.fixNameField (C:\Users\IV\AppData\Roaming\npm\node_modules\npm\node_modules\read-package-json\node_modules\normalize-package-data\lib\fixer.js:201:5)
5 error     at C:\Users\IV\AppData\Roaming\npm\node_modules\npm\node_modules\read-package-json\node_modules\normalize-package-data\lib\normalize.js:29:38
5 error     at Array.forEach (native)
5 error     at normalize (C:\Users\IV\AppData\Roaming\npm\node_modules\npm\node_modules\read-package-json\node_modules\normalize-package-data\lib\normalize.js:28:15)
5 error     at final (C:\Users\IV\AppData\Roaming\npm\node_modules\npm\node_modules\read-package-json\read-json.js:328:33)
5 error     at then (C:\Users\IV\AppData\Roaming\npm\node_modules\npm\node_modules\read-package-json\read-json.js:126:33)
5 error     at ReadFileContext.callback (C:\Users\IV\AppData\Roaming\npm\node_modules\npm\node_modules\read-package-json\read-json.js:302:48)
5 error     at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:336:13)
6 error If you need help, you may report this *entire* log,
6 error including the npm and node versions, at:
6 error     <http://github.com/isaacs/npm/issues>
7 error System Windows_NT 10.0.10586
8 error command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\IV\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
9 error cwd C:\xampp2\htdocs\mymelody\build
10 error node -v v7.4.0
11 error npm -v 1.3.26
12 verbose exit [ 1, true ]

**Comment by Silic0nS0ldier** [comment]
Looking at the log, what stands out to me is your old version of npm.
Run `npm install npm@latest -g`, then try `npm install` again.

In the meantime, I'll see if I can replicate the issue.

**Comment by Silic0nS0ldier** [comment]
I've successfully replicated the issue on my end.
Also confirmed on my end that updating to latest version of npm with `npm install npm@latest -g` fixed the issue.

Let us know if it worked on your end.

**Comment by lcharette** [comment]
So what would be the version requirement for npm? Is it listed on the learn website? Could the script check the version and fail with a nice error message is the version requirement is not met?

**Comment by Silic0nS0ldier** [comment]
No version requirement listed at learn website, nor there be a known minimum.

As for scripts that check version, giving a pretty error message, that'll be a no. Only way to check versions before running is with `npm -v`. Adding a script to check versions (which would add more dependencies), would most likely increase the number of potential failure points. Best solution to this would be figuring out minimum requirements, and mentioning them in the installation page, which people seem to be jumping to first.

**Comment by isaacdunyo** [comment]
Thanks Silic0n...however I have come across another issue...

2 info using npm@4.1.1
3 info using node@v7.4.0
4 verbose run-script [ 'preuf-assets-install',
4 verbose run-script   'uf-assets-install',
4 verbose run-script   'postuf-assets-install' ]
5 info lifecycle @userfrosting/userfrosting@4.0.0~preuf-assets-install: @userfrosting/userfrosting@4.0.0
6 silly lifecycle @userfrosting/userfrosting@4.0.0~preuf-assets-install: no script for preuf-assets-install, continuing
7 info lifecycle @userfrosting/userfrosting@4.0.0~uf-assets-install: @userfrosting/userfrosting@4.0.0
8 verbose lifecycle @userfrosting/userfrosting@4.0.0~uf-assets-install: unsafe-perm in lifecycle true
9 verbose lifecycle @userfrosting/userfrosting@4.0.0~uf-assets-install: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\xampps\htdocs\melnest\build\node_modules\.bin;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\ActiveState Komodo Edit 8\;C:\Program Files\Broadcom\Broadcom 802.11\Driver;C:\Program Files (x86)\HP SimplePass\x64;C:\Program Files (x86)\HP SimplePass\;C:\Program Files (x86)\AMD APP\bin\x86_64;C:\Program Files (x86)\AMD APP\bin\x86;C:\Program Files\Common Files\Microsoft Shared\Windows Live;C:\Program Files (x86)\Common Files\Microsoft Shared\Windows Live;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Windows Live\Shared;C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;C:\Program Files\WIDCOMM\Bluetooth Software\;C:\Program Files\WIDCOMM\Bluetooth Software\syswow64;C:\Program Files (x86)\Quest Software\vWorkspace Client\pntsc.exe;C:\Program Files (x86)\nodejs\;C:\Users\IV\AppData\Local\Android\android-sdk\platform-tools;C:\Program Files (x86)\Git\cmd;C:\Program Files (x86)\Git\bin;C:\Program Files (x86)\Skype\Phone\;C:\xampp2\php;C:\Program Files\nodejs\;C:\Program Files\Git\cmd;C:\ProgramData\ComposerSetup\bin;C:\xampps\php;C:\apache-ant-1.9.4-bin;C:\Program Files (x86)\WinAnt\bin;C:\Users\IV\AppData\Roaming\npm;C:\Users\IV\AppData\Roaming\Composer\vendor\bin
10 verbose lifecycle @userfrosting/userfrosting@4.0.0~uf-assets-install: CWD: C:\xampps\htdocs\melnest\build
11 silly lifecycle @userfrosting/userfrosting@4.0.0~uf-assets-install: Args: [ '/d /s /c', 'gulp bower-install' ]
12 silly lifecycle @userfrosting/userfrosting@4.0.0~uf-assets-install: Returned: code: 1  signal: null
13 info lifecycle @userfrosting/userfrosting@4.0.0~uf-assets-install: Failed to exec uf-assets-install script
14 verbose stack Error: @userfrosting/userfrosting@4.0.0 uf-assets-install: `gulp bower-install`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:885:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid @userfrosting/userfrosting@4.0.0
16 verbose cwd C:\xampps\htdocs\melnest\build
17 error Windows_NT 10.0.10586
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "uf-assets-install"
19 error node v7.4.0
20 error npm  v4.1.1
21 error code ELIFECYCLE
22 error @userfrosting/userfrosting@4.0.0 uf-assets-install: `gulp bower-install`
22 error Exit status 1
23 error Failed at the @userfrosting/userfrosting@4.0.0 uf-assets-install script 'gulp bower-install'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the @userfrosting/userfrosting package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     gulp bower-install
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs @userfrosting/userfrosting
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls @userfrosting/userfrosting
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by isaacdunyo** [comment]
And I get this when trying to access the site:

UserFrosting Application Error
Unable to start site. Contact owner.

Version: UserFrosting 4 Pre-Alpha
Error: Unable to determine Sprinkle load order.

**Comment by alexweissman** [comment]
Did you create your `sprinkles.json` file?

**Comment by isaacdunyo** [comment]
Yes, sprinkles.json has been created. I've gone back in to update and install npm and its taking ages to install npm...been 3 hours now.

**Comment by alexweissman** [comment]
It might be best to continue this discussion in [chat](https://chat.userfrosting.com).

**Comment by alexweissman** [comment]
Some people might need to [uninstall/reinstall gulp](https://github.com/gulpjs/gulp/issues/1291) if the problem persists:

```
npm uninstall -g gulp
npm install -g gulp
```

**Comment by alexweissman** [comment]
Please join us in chat if you are still having problems with npm and/or gulp.
