### ISSUE TITLE
Message stream should support raw placeholder interpolation

### ISSUE THREAD

**Issue by alexweissman** [userfrosting/UserFrosting#621]
Currently, placeholders for messages in the alert stream are interpolated when the message is translated on the server side.  When they get sent back to the client, this creates a problem because the `ufAlerts` plugin uses Handlebars to safely escape the message before displaying it to the client.  

This is good because it mitigates against XSS attacks if the message contains untrusted user data.  However when the placeholder values contain (trusted) HTML, this can lead to problems like:

![screen shot 2017-01-22 at 4 39 39 pm](https://cloud.githubusercontent.com/assets/5004534/22186325/edf2076a-e0c1-11e6-9324-e28d13866c36.png)

I think what we need to do, instead of assembling the messages on the server, is to pass the message string and placeholder values separately back to the client.  Then, `ufAlerts` would be responsible for performing the interpolation and escaping untrusted input.  The message string could support a `raw` filter to allow certain placeholders to accept raw input from trusted sources.

**Comment by lcharette** [comment]
So a `translate` function in javascript ? As long as the key/string is returned by the server, it should be easy to do. Otherwise we would need to ajax the key from the php translation table...

**Comment by alexweissman** [comment]
Yeah, I was thinking about this.  Would it be possible for the translator to assemble everything except the final interpolation of values supplied in the last parameter to `translate`?  Not sure how this would work out with pluralization and all that jazz.

**Comment by lcharette** [comment]
With the plan set in #634, I guess this is still a valid issue.

I think if you omit one placeholder, the translate function will just leave it there. So it would simply be a question of adding a placeholder replacement in JavaScript. Should this function be available globally or just for alerts ?

**Comment by lcharette** [comment]
This is fixed in the above commit. Instead of escaping client side in ufAlerts, the placeholder are escaped server side as discussed on the chat. A new argument has been added to `addMessageTranslated` so escaped and non escaped placeholder can be passed to the same string / translation key.

Example:
```
$ms->addMessageTranslated("success", "Project {{name}} successfully deleted <strong>(or not)</strong> at {{url}}", ['name' => "my <em>evil</em> cat", 'url' => "<a href='http://myVirusSite.ca'>MyVirusSite</a>"], ['url' => "<a href='http://google.ca'>Google.ca</a>"]);
```

Would now be displayed as « Project my &lt;em&gt;evil&lt;/em&gt; cat successfully deleted **(or not)** at [Google.ca](http://google.ca/) »

The only issue is if a dev pass untrusted user data to the second argument directly, for example: 
```
$userContent = "<a href='http://myVirusSite.ca'>MyVirusSite</a>";
$ms->addMessageTranslated("danger", "Project $userContent successfully deleted <strong>(or not)</strong>");
```

The documentation needs to be updated to add the new argument of the `addMessageTranslated` function and warn about untrusted data.

**Comment by lcharette** [comment]
As discussed on the chat, previous commit have been reverted and a new solution based on Twig [template from a
string](http://twig.sensiolabs.org/doc/2.x/recipes.html#loading-a-template-from-a-string) have been implanted in [i18n](https://github.com/userfrosting/i18n). Translation placeholder are now escaped by default globally and Twig filters can now be applied to placeholder names inside translation files.
