### ISSUE TITLE
Social login as a core feature

### ISSUE THREAD

**Issue by alexweissman** [userfrosting/UserFrosting#623]
I think this would be a good candidate for a built-in UF feature.

**Comment by samburdge** [comment]
I agree. Tried the plugin here: https://github.com/userfrosting/UserFrosting-OAuth but got 500 error immediately after installing. No way of knowing whether the plugin is still compatible, so would be amazing to have this as a core feature.

**Comment by alexweissman** [comment]
That plugin is not compatible with UF4.

**Comment by samburdge** [comment]
Thanks for clarifying that Alex. Is there any alternative plugin you are aware of?

**Comment by alexweissman** [comment]
We're looking into using https://github.com/thephpleague/oauth2-client to implement social login.  If you want to fork the `develop` branch and take a crack at it, it would be a great start!

**Comment by samburdge** [comment]
Thanks Alex. Now I know it doesn't already exist as a plugin, and is not currently in development, I will consider it.

**Comment by Silic0nS0ldier** [comment]
@sagudev mentioned https://github.com/hybridauth/hybridauth over at #845. Seems to have good out-of-box coverage, and for what isn't supported, the OpenID adapter it comes with seems to simplify things a fair amount. No idea how it compares with PHP League for OpenID though.

**Comment by sagudev** [comment]
I am waiting for hybridauth 3 stable and then i will write hybridauth 3 plugin for UserFrosting. If i will have time.

**Comment by archey347** [comment]
Is there anybody working on this at the moment?

**Comment by cookieman768** [comment]
I’d be interested in seeing Hybridauth 3 implemented. I will look into how hard it would be for me to do.

**Comment by sagudev** [comment]
Still waiting for hybridauth 3.0.0 stable.

**Comment by JMCA2** [comment]
hybridauth 3.0 was already released stable back in May.

Any ETA on when this might get implemented? Thanks

**Comment by archey347** [comment]
It's going to be a while yet... we have started work on it but there's still a lot to be done. I'm sorry I can't give you any exact timescales at the moment.

It's currently in a branch [in my fork](https://github.com/archey347/UserFrosting/tree/feature-authentication)

**Comment by archey347** [comment]
The thought was to add support for hybridauth. LinkedIn is on their list of compatible providers (https://hybridauth.github.io/providers.html), so it should work.

Unfortunately I've been inundated with other work at the moment so I haven't been able to do much with it recently, but hopefully I'll have some more free time after June.

**Comment by ktecho** [comment]
Ok, thanks. I guess I'll try to support LinkedIn login in some way. Thanks!
