### ISSUE TITLE
Missing translation inside Handlebar tables

### ISSUE THREAD

**Issue by lcharette** [userfrosting/UserFrosting#624]
One of the last missing translations are in the Handlebar tables. See for example : [app/sprinkles/admin/templates/components/tables/groups.html.twig](https://github.com/userfrosting/UserFrosting/blob/master/app/sprinkles/admin/templates/components/tables/groups.html.twig#L56).

The problem is the Twig `translate` function is not available inside the `verbatim` block.

**Comment by alexweissman** [comment]
Not sure if this is helpful or not: http://twig.sensiolabs.org/doc/2.x/recipes.html#using-twig-and-angularjs-in-the-same-templates

**Comment by lcharette** [comment]
Escaping the `{{` doesn't work :(

**Comment by lcharette** [comment]
Turns out the solution is even easier : `{% endverbatim %}{{translate("DESCRIPTION")}}{% verbatim %}`

**Comment by alexweissman** [comment]
Lol, that will do it I guess.
