### ISSUE TITLE
Middleware to distinguish between "unauthenticated" and "unauthorized" requests

### ISSUE THREAD

**Issue by alexweissman** [userfrosting/UserFrosting#626]
Right now, access control is entirely handled by the `Authorizer` class.  For example:

```
if (!$authorizer->checkAccess($currentUser, 'uri_account_settings')) {
    throw new ForbiddenException();
}
```

The problem is, this does not allow us to distinguish between "unauthorized" and "unauthenticated" requests in the way we handle the response.  For example if the user merely needs to log in, you might want to redirect them to the login page rather than showing them a 403 or 404 error page.

To do this, I propose we create a simple middleware for "protected" routes, that first checks that a user is authenticated using `Authenticator::check()`.  If it fails, it can throw a `AuthExpiredException`, which can be distinguished from the `ForbiddenException` that we usually throw when an _authenticated_ user is unauthorized to perform an action.

The `AuthExpiredException` can then be mapped to a custom handler that, for example, redirects to the login page.

**Comment by lcharette** [comment]
There's one thing I'm not sure I understand. What would be the difference between using that Middleware and something like this:
```
if (!Authenticator::check()) {
    // Redirect to login
} else if (!$authorizer->checkAccess($currentUser, 'uri_account_settings')) {
    throw new ForbiddenException();
}
```
Could one method (or the other) be better at handling different permission applied to the guest user? I guess there could also be a situation where `foo id#1` is accessible by a guest, but not `foo id#2`. Not sure which method will make it work better.

(Don't forget we need to implement where the user is redirected after login)

**Comment by alexweissman** [comment]
They're equivalent.  Route middleware would just help to encapsulate that functionality.  And, unlike more complex authorization checks, this is something that would be exactly the same for every protected route.

**Comment by alexweissman** [comment]
Ok, I've gone ahead and implemented the `authGuard` middleware in the `develop` branch.  So, now a `AuthExpiredException` is thrown when a user is not logged in (but expected to be for a given route).

The next thing to do is write a custom handler for this type of exception, that will take the user to the login page.  After that, we'll need to figure out how to have the login page redirect to the original URL after a successful login.

From what I can tell, the most popular way to do this is by putting the target URL in the query string for the redirect page: http://stackoverflow.com/a/14523719/2970321

**Comment by lcharette** [comment]
Query string might be the easiest to implement even if the URL domain needs to be checked to not redirect to a foreign domain.

**Comment by alexweissman** [comment]
Yep.  Or, we could just pass in the URL path, rather than the full URL, and have the server add the necessary scheme, host, and port:

```
// Would redirect to https://example.com/admin after logging in
https://example.com/login?redirect=/admin
```

**Comment by lcharette** [comment]
That's what I was thinking too

**Comment by alexweissman** [comment]
Ok, the redirect has been implemented in `develop`.  Please note that it requires a new JS dependency, URI.js, so you will need to re-run `npm uf-assets-install`.
