### ISSUE TITLE
Admin panel link style in main dropdown menu

### ISSUE THREAD

**Issue by SarahBaghdadi** [userfrosting/UserFrosting#627]
The "Admin panel" link looks like plain text compared to the other buttons around it.  I like how it looks, but I wonder if its not clear enough to a new user. When I first logged in, I felt like "how do I get to the admin panel".

![screen shot 2017-01-26 at 1 41 09 am](https://cloud.githubusercontent.com/assets/8106569/22322240/8b2c5186-e368-11e6-9f07-01006ddcec7a.png)

**Comment by lcharette** [comment]
It's actually the default [AdminLTE](https://almsaeedstudio.com/themes/AdminLTE/index2.html) look:

![capture d ecran 2017-01-26 a 06 38 20](https://cloud.githubusercontent.com/assets/2566513/22330112/842bb4e2-e392-11e6-9bd5-efb0e4465203.png)

I do agree it look weird, but it doesn't fit between "my account" and "logout" without resizing the box awkwardly. It's even worst when in french locale since all the strings are longer.

Not sure how to it could be fixed. If you have any suggestions it could be merged.

**Comment by alexweissman** [comment]
Yeah we need to make it more prominent.  Also, we should probably redirect people directly to the dashboard by default when they log in, if they have access.

**Comment by lcharette** [comment]
> Also, we should probably redirect people directly to the dashboard by default when they log in, if they have access.

This goes back to the "dev being able to define where a user can go after login" feature...

**Comment by alexweissman** [comment]
Ok, I've implemented this in `develop`.  See [`c82c28`](https://github.com/userfrosting/UserFrosting/commit/c82c288327bc99ce00817856af46a570b878ac64).  You can define a `determineRedirectOnLogin` service in your Sprinkle, which returns a callback that adds a custom `UF-Redirect` header to the response.  This callback is automatically invoked by `AccountController::login()` after the user successfully logs in.  I've already defined this callback in both the `account` and `admin` sprinkles (admin tries to forward to dashboard, account tries to forward to account settings).  So, all a dev needs to do to change the behavior, is override this callback in their own sprinkle.

Meanwhile, on the client side of things, the `pages/sign-in-or-register.js` code will check for the `UF-Redirect` header in the response and forward to that page on success (unless a redirect was specified in the URL for the login page, in which case it will redirect to that instead).

**Comment by alexweissman** [comment]
Still need to fix dat button tho

**Comment by lcharette** [comment]
Done !
