### ISSUE TITLE
Reorganize assets

### ISSUE THREAD

**Issue by alexweissman** [userfrosting/UserFrosting#629]
We should go through the Bower dependencies and bundle definitions for each sprinkle.  I think they could use some tidying up.

**Comment by SarahBaghdadi** [comment]
Also, `assets/local` would be more semantic if we named it `assets/userfrosting`.

**Comment by alexweissman** [comment]
I propose something like this:

```
assets/
  site/
    ... (developer content goes here)
  userfrosting/
    js/
      pages/
      widgets/
      ...
    css/
      pages/
      widgets/
      ...
    favicons/
    fonts/
    images/
    ...
  vendor/
```

**Comment by lcharette** [comment]
Sounds great. As discussed in chat, cleaner structure means less chances of accidental collision between assets. If two sprinkles defines `assets/local/app.css`, theres more chance of incompatibility between sprinkle than if they both uses the `assets/{sprinkle name}/app.css` convention. Makes it clear also when you *do* want to overwrite something from another sprinkle.

**Comment by alexweissman** [comment]
Alright, this is done.  I have also removed some extraneous Bower dependencies.
