### ISSUE TITLE
Format for updates

### ISSUE THREAD

**Issue by lilfade** [userfrosting/UserFrosting#63]
We should start including a update script in the dev branch for changes that way people dont have to do updates manually or start from scratch.

The question is how do we do this? do we setup a mini installer to make the changes and if code changes are made include them in a seperate folder maybe 

>zip_root/
/api/
/account/
/update/
/update/{installer_files_here}
/update/code_changes/
/update/code_changes/models/db_functions.php <-- changed file

then just drop and replace the old file with the new one and good to go?

**Comment by r3wt** [comment]
i'm assuming this can be closed since its a stale branch.

**Comment by alexweissman** [comment]
Agreed.  We might still want to have an autoupdater later on down the road, especially if we can find a way to implement a clean separation between the "core" UF code and developer-added code.  We're already at a point where templates and data models can be overridden - if we can implement overriding/extending routes, schema, and language files, we might be able to do this.
