### ISSUE TITLE
Sprinkle Migrations History

### ISSUE THREAD

**Issue by Silic0nS0ldier** [userfrosting/UserFrosting#631]
Having a historical record of Sprinkle migrations/updates is something worth considering. This could be helpful in the event an issue occurs that can be tracked down to a specific Sprinkle migration/update.

**Comment by lcharette** [comment]
Could be moved to the `activity` thing. Can we add global (not attached to any user) activity @alexweissman ?

**Comment by alexweissman** [comment]
The user activity log is really meant to be used for user activities.  How about just creating a new Logger service that writes to a file by default?  `migrations.log` or something?

**Comment by lcharette** [comment]
I guess it could work.

**Comment by lcharette** [comment]
This is probably linked to #683. Laravel migrations keeps tracks of all migrations in a db table.

**Comment by lcharette** [comment]
This is done in `develop`. There's no UI for this, but you can find the info manually in the new `migration` table.
