### ISSUE TITLE
Automatically invoke Sprinkle service provider

### ISSUE THREAD

**Issue by lcharette** [userfrosting/UserFrosting#636]
As discussed on the [chat](https://chat.userfrosting.com/channel/support?msg=Tici5BkcKhmhXwXsA).

**Comment by alexweissman** [comment]
I wonder...can we sneak this into v4?  Would it be BC?  What happens if you call `register` twice on a service provider class?

**Comment by Silic0nS0ldier** [comment]
@alexweissman Calling register twice was happening in the migrations before. Made core act a little... odd.

**Comment by lcharette** [comment]
Could be something else than registering twice? My middleware was loaded along side it's service provider no problem?

**Comment by alexweissman** [comment]
Ok, this will be implemented in the upcoming version 4.1.

**Comment by alexweissman** [comment]
Implemented in `develop`.
