### ISSUE TITLE
Change require_once path in index.php

### ISSUE THREAD

**Issue by RomeroMsk** [userfrosting/UserFrosting#643]
I have a suggestion to change https://github.com/userfrosting/UserFrosting/blob/master/public/index.php#L18 from
```php
require_once '../app/vendor/autoload.php';
```
to
```php
require_once __DIR__ . '/../app/vendor/autoload.php';
```
It will allow to include/require `index.php` from any other file at any directory level and will not break the default usage way.

**Comment by Silic0nS0ldier** [comment]
The line referred to is for the composer autoload. I'm personally against this idea, as it'll create a extra fail point, and break the MVC convention.

If you can provide a use case, it'll be up for consideration, but as is, everything that could possibly need to be done could be done within a Sprinkles autload functionality.

**Comment by RomeroMsk** [comment]
What extra fail point? It is just a correction to use absolute path instead of relative.

The use case is using UF as module/component in project with entry script located outside the UF directory:
```
project
  modules
    uf
      app
      ...
      public
        index.php
  public
    index.php // Project entry script with require_once() for UF index.php for appropriate cases/routes
```

**Comment by JoshNorris** [comment]
All I have to say is I'm on @Silic0nS0ldier side here. 99% of people using UF will be using the UF entry point.

**Comment by Silic0nS0ldier** [comment]
Ah, now I see. Misinterpreted your original post.

Still, in terms of using this inside another project, I don't see that as a use case. UserFrosting has its own routing system (Slim), and as such some UserFrosting routes may be blocked by the hosting application. Further more, by using it this way, behaviour will be unpredictable, as further inside UserFrosting there is likely to be relative references (I'm sure there is a list of other reasons too).

Needless to say, there is a reason that people don't use these sorts of projects as a submodule, they simply aren't designed to work this way.

**Comment by RomeroMsk** [comment]
> Needless to say, there is a reason that people don't use these sorts of projects as a submodule, they simply aren't designed to work this way.

I am using. And it works this way :)

This change will not break anything for "that people" (`require_once` will work as before), but can help others. If you are not considering this as enough argument, I will close the issue.

**Comment by alexweissman** [comment]
I don't see any reason not to use `__DIR__` to build an absolute path instead of the current relative one.  Actually, this is what Composer does to build paths for dependencies.  For example, see `autoload_static.php`.
