### ISSUE TITLE
Add built in Sprunjes to Class Mapper

### ISSUE THREAD

**Issue by Silic0nS0ldier** [userfrosting/UserFrosting#645]
The built in table Models are already accessed through class mapper to enable easy modification of behaviour my users. Since data Sprunjes are closely related to Models, it would make sense to have them mapped via the class mapper as well.

Implementation shouldn't cause any breaking changes either.

**Comment by Silic0nS0ldier** [comment]
Resolved by 1cb0f801011e0d6ecd397eb7ff07821dccb03eba

**Comment by alexweissman** [comment]
Open another issue if you come across any other classes that should be dynamically mapped.

**Comment by Silic0nS0ldier** [comment]
Will do!
