### ISSUE TITLE
Fix bugged jQuery integration for UF plugins

### ISSUE THREAD

**Issue by Silic0nS0ldier** [userfrosting/UserFrosting#646]
UserFrosting plugins are based on [jQuery Plugin Design Pattern/Template Improved!](https://gist.github.com/Air-Craft/1300890) which calls `indexOf` (a string function) on an object in 2 places. This causes an error to propagate that may cause the script to behave erratically.

However, standing in the way of a fix is the purpose of the checks that use this. There may be a good reason for this check to exist. Its possible that to maintain expected functionality, a complete rewrite of the jQuery plugin integration may be required.

**Comment by alexweissman** [comment]
I'm all in favor of improving our system for creating jQuery plugins.  Actually, it might be more efficient if we could eliminate some of the duplicate code that comes from having every single widget copy-paste that giant "jquery hook" block.

What if we could put `ufAlerts`, `ufModal`, `ufForm`, `ufCollection`, etc all into a single package, like Bootstrap or FuelUX?

**Comment by Silic0nS0ldier** [comment]
Don't think it will be possible to merge them, but I'll explore the possibility.
Goal will definitely be to reduce the amount of boilerplate though.

Hmm... though it wouldn't make much sense for some of the plugins to be available on every page. Could end up just adding overhead. Especially since JS is loaded using the blocking approach.

**Comment by alexweissman** [comment]
True.  Actually, looking at Bootstrap, it does seem like they have a fair amount of boilerplate from component to component: https://github.com/twbs/bootstrap/tree/master/js

At the very least, would be good if we could cut back a bit.

**Comment by lcharette** [comment]
For form, it's possible to merge multiple forms JS into a common one, with some HTML data attributes magic. See my form generator sprinkle

**Comment by lcharette** [comment]
If this can be useful, I used a different plugin template for my own plugin. I can't find the source of it, but you check out an example here : https://github.com/lcharette/UF_FormGenerator/blob/master/assets/js/widget-formGenerator.js

**Comment by Silic0nS0ldier** [comment]
Cheers. I've already found a template that should resolve the issue with the minimum amount of boiler plate though. Only reason it hasn't been worked on yet is due to me being extremely busy. I will get around to this. Eventually.
________________________________

**Comment by Silic0nS0ldier** [comment]
Been having a crack at getting this resolved. I've rebuilt `ufAlerts` using [jQuery Boilerplate](https://jqueryboilerplate.com/) as a starting point.

[New ufAlerts.js](https://gist.github.com/Silic0nS0ldier/a0edc5ee7f60dcf1fb78928cbbd0a590)

Feedback is appreciated. (oh, and if it isn't obvious in the gist, I'm taking advantage of the opportunity to improve performance and readability where I can)

**Comment by alexweissman** [comment]
I don't really understand it, but it looks great!  As long as the API is the same and it fixes the issue, I'm happy :-)

**Comment by Silic0nS0ldier** [comment]
API is identical. And every method now permits chaining (which is recommended by jQuery).

I'll give the code some cross browser testing, and convert the rest over if it all works out.

**Comment by Silic0nS0ldier** [comment]
`ufAlerts` has been covered as of 3eda0d739328c528eb8d6edaa4d0268e70c0dafe.
Other plugins will be ported based it. Should be nice and quick now that I know what needs to be done.

**Comment by Silic0nS0ldier** [comment]
Progress
- [x] ufAlerts
- [ ] ufCollection
- [ ] ufForm
- [ ] ufModal
- [ ] ufTable

**Comment by Silic0nS0ldier** [comment]
Currently at an impasse with this.
Are there any parts of UF that use ufModel?

ufTable could also take a little longer to do, as the massive codebase means much more testing is required.

**Comment by alexweissman** [comment]
`ufModal` is used in any of the "widgets" for users, groups, and roles.  See https://github.com/userfrosting/UserFrosting/tree/master/app/sprinkles/admin/assets/local/widgets/js

**Comment by Silic0nS0ldier** [comment]
All 4.0 plugins have been ported. All that remains is porting the recently fixed 4.1 version. (fun times...)

**Comment by alexweissman** [comment]
😊

**Comment by Silic0nS0ldier** [comment]
Everything is done. Fix will be available in 4.0.21-alpha and 4.1.
