### ISSUE TITLE
OR'ed filter in the Sprunje implementation. 

### ISSUE THREAD

**Issue by kevinrombach** [userfrosting/UserFrosting#647]
c/p from the chat ^^ 
How can i define my Model/Sprunje that i can sort with OR in an Table? When i have `customer.name` and `customer.number` and i have a table with a column which has both in the cells. When i type in the search field i can only search the one i defined in the table header for now. Do you have a solution for that?

**Comment by alexweissman** [comment]
The way to do this would be to define a custom filter, and give it a more generic name in your table.  Like, for example, `info`.  Then you can define your custom filter:

```
    /**
     * Filter LIKE the customer name OR number.
     *
     * @param Builder $query
     * @param mixed $value
     * @return Builder
     */
    protected function filterInfo($query, $value)
    {
        return $query->orLike('customer.name', $value)
                     ->orLike('customer.number', $value);
    }
```

But, we still need to implement a way to filter on multiple _values_.  For example, a way to match customers with name "David" OR "Alex".

**Comment by alexweissman** [comment]
This has been done in 4.0.12-Alpha.
