### ISSUE TITLE
Fonts are not copying to public/assets with uf-assets-copy command

### ISSUE THREAD

**Issue by RomeroMsk** [userfrosting/UserFrosting#650]
After running `npm run uf-assets-copy` I don't see the `public/assets/fonts` dir and of course fonts are not displaying correctly on interface in production mode.

**Comment by Silic0nS0ldier** [comment]
Fonts are being copied. Issue is with the bundler not rewriting urls in the css, breaking links. I got a fix for this ready, so expect a fix to be released within 24 hours.

**Comment by RomeroMsk** [comment]
Ok, will wait.

**Comment by Silic0nS0ldier** [comment]
This has been resolved as of bc81a84a24e83a65f0938df955a72b8140ffbae8.

Fix will be in master as of next alpha release. If its urgent, you can make the necessary changes to your code, or merge in the develop branch.

**Comment by RomeroMsk** [comment]
Thanks.

**Comment by RomeroMsk** [comment]
Just checked it on my production environment and everything works.
Please actualize the documentation on asset commands and deployment to production guide. I just had to guess what commands should I use for dev and production environments.

**Comment by Silic0nS0ldier** [comment]
Good to hear. As for the docs, they are written to match the master, as the develop branch is always subject to change.

Rest assured, it'll all be documented (once the "going live" section is finished).
Got to remember, this is all alpha atm. 😉

**Comment by RomeroMsk** [comment]
Yes, I felt the alpha taste already 😉

**Comment by alexweissman** [comment]
Feel free to join us in [chat](https://chat.userfrosting.com) too!
