### ISSUE TITLE
Introduce 'debug' as an option for UF_MODE

### ISSUE THREAD

**Issue by Silic0nS0ldier** [userfrosting/UserFrosting#653]
Currently there is a `dev` `UF_MODE` that favours itself to development. While this works good, sometimes we need more verbosity to track down the source of an error.

I suggest we introduce a third `UF_MODE` called `debug` that puts everything in debug mode.

It may also be of benefit to make it such that this mode can be used alongside other modes, such as `production`, to help isolate issues specific to that mode (since there are performance related differences).

**Comment by lcharette** [comment]
Can't it be set in dev/production specific config files?

**Comment by alexweissman** [comment]
I think that's @Silic0nS0ldier's point.  We have a `debug.php` config file that just opens up the floodgates, turning on all debug settings.

**Comment by glen7** [comment]
Nemesis, we meet again

**Comment by lcharette** [comment]
`testing` is used to disable stuff like cache and `displayErrorDetails` when running PHP Unit tests

**Comment by Silic0nS0ldier** [comment]
Ah. That clears things up.

**Comment by alexweissman** [comment]
There's also a [`dev.php`](https://github.com/userfrosting/UserFrosting/tree/master/app/sprinkles/core/config).  Can we rename this to `debug.php` instead?  So-called "dev" mode is really just the default mode.

**Comment by lcharette** [comment]
Note that  when Bakery creates `app/.env`, it set `UF_MODE` to `""`.

To make dev truly the default mode, bakery needs to be updated

**Comment by alexweissman** [comment]
Well, right now `""` is equivalent to `default`: https://github.com/userfrosting/config/blob/master/src/ConfigPathBuilder.php#L35-L39

**Comment by lcharette** [comment]
> So-called "dev" mode is really just the default mode.

dev == default? 

On a side note, It could be clearer for new dev if _something_ was defined in `.env` instead of `""`...

**Comment by alexweissman** [comment]
default == default

My point is, there is no explicit "dev" mode right now.  That `dev.php` should really be called `debug.php`.

**Comment by lcharette** [comment]
Done in ec508e0 for 4.2
