### ISSUE TITLE
Database independent PDO checks

### ISSUE THREAD

**Issue by Silic0nS0ldier** [userfrosting/UserFrosting#655]
Currently there is code intended to trigger a `PDOException` on database connection failure, due to built in library throwing a useless exception that makes debugging next to impossible.

However this check is specific to MySQL (and by extension MariaDB) as PDO expects different keywords for different database systems.

This check should be refactored into a class that mimics the behaviour of Laravels library, or a fix should be made to their code so that a more debugable exception is thrown. (assuming their latest version isn't above our minimum PHP requirement, it shouldn't be from memory)

**Comment by alexweissman** [comment]
So, I just discovered this commit to `illuminate/database` 5.3: https://github.com/laravel/framework/pull/16666

Which references this issue: https://github.com/laravel/framework/issues/16661

Notice that this fix happened only [two days after I implemented our own check!](https://github.com/userfrosting/UserFrosting/commit/a1a96fab1cb418f9d3f68b66587fd98171556fb3).

So, if I'm understanding this correctly, I think we can completely remove our database check, and just let Laravel throw the actual PDOException now if the connection fails.

**Comment by lcharette** [comment]
I guess it's fixed too in 5.4 ?

**Comment by alexweissman** [comment]
So, I think we can just remove the check from `Authenticator` completely, and use `getPdo()` to test the connection in the installer now.

**Comment by alexweissman** [comment]
Alright, implemented in https://github.com/userfrosting/UserFrosting/commit/9c9316b7db6d9b5f9a7c74eba909c2624cbafd5a.
