### ISSUE TITLE
Throttling problems

### ISSUE THREAD

**Issue by RomeroMsk** [userfrosting/UserFrosting#656]
1. If you set `type` to `data` for throttle rule, it will not work correctly (checked for login). Please check the events filtering in `Throttler::getDelay()`.
2. If you set the specific event key in `throttles` config to `null` (as it advised in docs to turn off the throttling), it will make the `Throttler` throw `ThrottlerException`s.

**Comment by alexweissman** [comment]
Have you merged the latest version of `master`?  A recent commit should have fixed (2).  As for (1), I'll look into it.

**Comment by RomeroMsk** [comment]
Thanks.
