### ISSUE TITLE
'merge' rule for bundle config files doesn't respect Sprinkle order

### ISSUE THREAD

**Issue by alexweissman** [userfrosting/UserFrosting#660]
When using the `merge` option for `onCollision` as documented in https://learn.userfrosting.com/building-pages/assets/asset-bundles#extending-and-overriding-bundles, the order of the assets should reflect the order of loaded Sprinkles.  For example, if I have the `js/form-widgets` bundle in `core` defined as:

```
        "js/form-widgets": {
            "scripts": [
                "vendor/speakingurl/speakingurl.min.js",
                "local/core/js/uf-collection.js"
            ],
            "options": {
                "result": {
                    "type": {
                        "scripts": "plain"
                    }
                }
            }
        }
```

and then I later load a Sprinkle `site` with the following definition:

```
    "js/form-widgets" : {
        "scripts": [
            "vendor/MathJax/MathJax.js"
        ],
        "options": {
            "result": {
                "type": {
                  "scripts": "plain"
                }
            },
            "sprinkle": {
                "onCollision": "merge"
            }
        }
    }
```

The result is:

```
        "js/form-widgets": {
            "scripts": [
                "vendor/MathJax/MathJax.js",
                "vendor/speakingurl/speakingurl.min.js",
                "local/core/js/uf-collection.js"
            ],
            "options": {
                "result": {
                    "type": {
                        "scripts": "plain"
                    }
                }
            }
        }
```

So, the `bundle-build` task is putting the assets from `site` ahead of the assets from `core`.  The problem only seems to happen with compiled assets - raw assets are loaded in the correct order.

**Comment by Silic0nS0ldier** [comment]
Based purely on observation, I'd say its sorting the array in alphabetical order. Presumably the plugin used is doing this to improve performance. A fix would entail finding a plugin that does what we want (will take awhile), or creating our own (better put off for the planned asset overhaul).

**Comment by alexweissman** [comment]
If it were sorting alphabetically, though, why would the `vendor/` paths come first?

**Comment by Silic0nS0ldier** [comment]
Right...

**Comment by Silic0nS0ldier** [comment]
Replicated the issue. I know whats happening. Instead of appending, its prepending.
...and looking at the code, this is really obvious. Really should have named that rule `append`...

`dev` was unaffected as the PHP side handles that, and does the merging in a drastically different way.

**Comment by lcharette** [comment]
I can confirm that solved the issue with my Sprinkle 👍
