### ISSUE TITLE
Autofill problems on the account-settings page.

### ISSUE THREAD

**Issue by kevinrombach** [userfrosting/UserFrosting#664]
When i open the account settings page safari (macOS) autofills the `username` in the field where the email belongs to. The current password will be autofilled in the "new password field".

**Comment by alexweissman** [comment]
Possibly related to http://stackoverflow.com/a/23234498/2970321

**Comment by alexweissman** [comment]
I'm running a very old version of Safari (6!) and can't seem to replicate this issue.  Can someone else take a stab at it?

**Comment by kevinrombach** [comment]
Works now with splitted register/login pages.

**Comment by alexweissman** [comment]
Great!
