### ISSUE TITLE
authGuard throwing 500 error when user not authenticated

### ISSUE THREAD

**Issue by grubbychicken** [userfrosting/UserFrosting#668]
Forgive me for my lack of knowledge.  I have been out of practice for a number of years when it comes to writing web apps.
Although the UserFrosting framework has really helped me learn the new technologies and methodologies. So thanks for all of your efforts here!  It's much appreciated.

It is my understanding that the authGuard should throw a 302 exception and redirect the user to the homepage if they are not authenticated when trying to access an authGuard protected page.  However, in my case I am receiving a 500 error with little helpful info on where the problem is occurring.  

I'm not quite sure if it something I have done to cause the issue, or something not quite right within the UF framework.  Any help would be much appreciated!

**Comment by malle-pietje** [comment]
Have you checked your PHP error logs (in case of apache2 this often is the apache error_log file). For support questions such as this one, I suggest you join the chat here:
https://chat.userfrosting.com/channel/support

**Comment by grubbychicken** [comment]
I have yes, but nothing useful.  I'll take my query to the Chat.  Thanks
