### ISSUE TITLE
Tool for creating/updating language files

### ISSUE THREAD

**Issue by alexweissman** [userfrosting/UserFrosting#671]
I think it would make it a lot easier for translators, if we had some kind of interactive tool for creating language files, as well as updating them when changes are made to `en_US`.

We also have quite a few languages in UF3 that still need to be ported over to UF4, and I think this would be easier to get done if we had a tool:

- Spanish
- Dutch
- Italian
- Turkish
- Romanian

**Comment by amosfolz** [comment]
Is the idea for the bakery to be used as the _interactive tool?_.

**Comment by lcharette** [comment]
I think that was Alex initial idea. 

I think the first thing we need is a way to generate a list of keys available in English, but not in X language. #850 & #868 might be need first.

**Comment by lcharette** [comment]
A new Bakery command, `locale:compare`, has been added for UF 4.4.0. This will makes it easier to detect values that needs to be translated. Not a fully interactive tool, but I think it's enough for now. See other comment here about future commands we could add : https://github.com/userfrosting/UserFrosting/pull/992#issuecomment-578563058
