### ISSUE TITLE
Config can't remove unwanted available locales

### ISSUE THREAD

**Issue by lcharette** [userfrosting/UserFrosting#672]
Setting the available locale in a sprinkle config file to remove the unwanted locale won't work. This only replace the locale displayed name.

```
            'locales' => [
                'available' => [
                    'fr_FR' => 'Français'
                ],
            ]
```

To solve this issue, available locale should only be an array of locale code (`'available' => ['fr_FR', 'en_US']`) and the locale name should be define elsewhere (locale metadata for example).

(Related to #671)

**Comment by alexweissman** [comment]
As a short-term solution, what if `userfrosting/config` had a `getDefined` method that did the same thing as `get`, but then removed any keys from the sub-array that are assigned to `null`?

So then you could do:
```
            'locales' => [
                'available' => [
                    'fr_FR' => 'Français',
                    'en_US' => null,
                    'de_DE' => null,
                    ...
                ],
            ]
```

Then you could call `$config->getDefined('site.locales.available')` and it would strip out those null-valued keys.

**Comment by lcharette** [comment]
I guess it could work. Any reason it couldn't be done in normal `get`? db/laravel settings?

**Comment by alexweissman** [comment]
I mean, we could always do an `array_walk` or something to filter them out in the `config` service.

**Comment by lcharette** [comment]
See #682 for a temp fix.

**Comment by alexweissman** [comment]
The more general problem here is the ability for a schema/config/whatever file loaded in a later Sprinkle, to _remove_ (rather than simply overwrite) content from a previously loaded Sprinkle.

The question is, do we want to have something in the syntax of the files themselves that can do this?  Otherwise, I think my `getDefined` approach might be the best.

**Comment by alexweissman** [comment]
I'm going to close this because it's _technically_ been fixed with the `Repository::getDefined` method.

The broader discussion about the correct way to store and load locale metadata can be continued in this issue: https://github.com/userfrosting/i18n/issues/4
