### ISSUE TITLE
User Frosting 4.0.1

### ISSUE THREAD

**Issue by Gosintary** [userfrosting/UserFrosting#675]
Hello! When I try to install UF 4.0.1 alpha, I download it from GitHub, and then I upload it to my website via Filezilla, but I can figure out what to do from here. When I click the public folder, it just takes me to my home page, and when I click the install.php file I get HTTP ERROR 500(page can't be loaded) Plz Help me

**Comment by alexweissman** [comment]
Hi @Gosintary, the issue tracker is for bug reports and feature requests.  Please join us in [chat](https://chat.userfrosting.com) for troubleshooting support.  Thanks!
