### ISSUE TITLE
Ignored directories causing problems

### ISSUE THREAD

**Issue by GorioB** [userfrosting/UserFrosting#678]
If `app/sessions/ `, ` app/logs/ `, and `app/cache/ ` are missing, it creates this somewhat cryptic error: 
![error](https://cloud.githubusercontent.com/assets/4759591/24548850/3d5ea6fc-1649-11e7-803c-7cbb82387165.png)

This isn't a problem when cloning directly from the repo since those folders are already committed with their respective gitkeeps, but since their contents are ignored it creates a bit of an issue:

When the framework is used in a project with a different git repository (e.g. just copying the files), and if using the same gitignore, the three directories are never committed to the new repo and we get our confusing error.

I think the easiest fix would just be to manually add the gitkeeps back into the ignore file, i.e.:
```
app/cache/*
app/logs/*
app/sessions/*

!app/cache/.gitkeep
!app/logs/.gitkeep
!app/sessions/.gitkeep
```

**Comment by lcharette** [comment]
+1 For gitigore. Could be an easy fix. Can you send a PR for that?

The error is not right too. Soudn't display `0`, but the list of directories.
