### ISSUE TITLE
AuthExpired Status code

### ISSUE THREAD

**Issue by kevinrombach** [userfrosting/UserFrosting#681]
Status code after an AuthExpired redirection should be something other than 302. 
Maybe:  401 Unauthorized

**Comment by Silic0nS0ldier** [comment]
Perhaps. Can a redirection take place with a 401 response?

**Comment by alexweissman** [comment]
> Only 3xx response codes support redirection.

Could someone figure out whether this is a limitation of Slim, or part of the HTTP spec?

**Comment by Silic0nS0ldier** [comment]
Limitation appears to be part of the HTTP spec. Browsers are only guaranteed to respect the `location` header if there is a `3xx` response code.

**Comment by alexweissman** [comment]
Ah, ok.  So maybe for AJAX requests it can return the 401 code, but for "standard" requests it can return a 302?

**Comment by Silic0nS0ldier** [comment]
AJAX should be exempt (for obvious reasons), so yeah, 401.

**Comment by alexweissman** [comment]
Actually, if you look at the `AuthExpiredHandler`, it already does this ;-)

The trick is to submit your API requests with the header `X-Requested-With: XMLHttpRequest`.  This will cause `AuthExpiredHandler` to invoke its `ajaxHandler` instead of its `standardHandler`.
