### ISSUE TITLE
ufTable pagination issue with tablesorter 2.28.6+

### ISSUE THREAD

**Issue by alexweissman** [userfrosting/UserFrosting#688]
[This commit](https://github.com/userfrosting/UserFrosting/commit/4121785ebc3908cddf360d60fb71695f656525d9#diff-19d9df33b2122305161b93b95e836baeR293) fires an additional `update` event on the Tablesorter object.  

However, this seems to break pagination as of Tablesorter 2.28.6+.  If you try to advance to the next page, it advances but then quickly flips back to the first page.  I believe `update` is now being fired twice, and that is causing the reset.

**Comment by alexweissman** [comment]
Seems like each new version of Tablesorter introduces some new breaking changes.  We need to either lock in a specific version, or keep up with the changes.

**Comment by lcharette** [comment]
Got the bug too. Tables doesn't works at all now.  +1 for locking version `2.28.6` for now, until we figured out if it's us or them. I can push my change to `hotfix` for now

**Comment by alexweissman** [comment]
Wait, shouldn't we lock at 2.28.5?  2.28.6+ is an inclusive interval ;-)

**Comment by lcharette** [comment]
I had no issue with .6? Did you?

**Comment by lcharette** [comment]
Ok, just experienced the issue with `2.28.6`... Changing the commit to `2.28.5`

**Comment by alexweissman** [comment]
It looks like v2.28.8 fixes this problem, but then it introduces a new problem: https://github.com/Mottie/tablesorter/issues/1389
😞 

So it would seem that we are still stuck with 2.28.5 for now.

**Comment by Mottie** [comment]
Sorry! :( I need to reproduce the issue on my end before I can fix it.

**Comment by alexweissman** [comment]
No need to apologize!  We're all huge fans of tablesorter and appreciate all the time you put into it 👍

**Comment by alexweissman** [comment]
In v4.0, this has been addressed by locking TS to version 2.28.5.  

In v4.1, we switch to the widget and rework our system for populating column select menus to eliminate the need for manually triggering a table update.  This allows us to upgrade to 2.28.6+.

See https://github.com/userfrosting/UserFrosting/commit/092b7d26b4ae55946295eeb161770d6fda58425d.

**Comment by alexweissman** [comment]
This problem appears to have re-emerged in 4.1.  This time, it only seems to happen while there is a filter applied to a column.

**Comment by lcharette** [comment]
Note commit 5b77d54 will solve this issue, but it create a new one where the `filter-select` active option might not be set properly when initially loading the page (reload should still work).
