### ISSUE TITLE
After timeout, accessing account/settings shows Error

### ISSUE THREAD

**Issue by alani1** [userfrosting/UserFrosting#694]
After login timeout, accessing account/settings should rather redirect to login page than showing a not so pretty Error Message to users.

<img width="1101" alt="2017-04-16 21_28_14-userfrosting application error" src="https://cloud.githubusercontent.com/assets/3892818/25073706/3c2ef520-22ec-11e7-92e1-634db3698974.png">

**Comment by alexweissman** [comment]
It does.  You just need to turn off the debugging mode (which is turned on by default in development mode).  See https://learn.userfrosting.com/error-handling/overview#settingsdisplayerrordetails

**Comment by alexweissman** [comment]
Feel free to [join us in chat](https://chat.userfrosting.com) if you have any specific questions about this feature.
