### ISSUE TITLE
getModalEdit missing translator in RoleController.php and GroupController.php

### ISSUE THREAD

**Issue by jian118** [userfrosting/UserFrosting#695]
Undefined variable: translator in \\app\\sprinkles\\admin\\src\\Controller\\RoleController.php on line 398
Undefined variable: translator in \\app\\sprinkles\\admin\\src\\Controller\\GroupController.php on line 391

The error comes when editing role and group.

In getModalEdit functions, add the following line before the translator fixed the problem
$translator = $this->ci->translator;

**Comment by alexweissman** [comment]
Is this the problem that is fixed in #692?

**Comment by splitt3r** [comment]
yes

**Comment by alexweissman** [comment]
Fixed in https://github.com/userfrosting/UserFrosting/commit/4091beb02aebdd9a011ddc05686f42033313d828
