### ISSUE TITLE
Twig Runtime Error

### ISSUE THREAD

**Issue by gracedigital** [userfrosting/UserFrosting#699]
Just cloned the latest code and tried to load the site.  Getting a UserFrosting Application Error

Type: Twig_Error_Runtime
Message: An exception has been thrown during the rendering of a template ("The asset 'vendor/font-awesome/css/font-awesome.css' could not be found. Referenced in '/Users/bitworks/Development/uf/app/sprinkles/core/bundle.config.json [css/main]'.").
File: /Users/bitworks/Development/uf/app/sprinkles/core/templates/layouts/basic.html.twig
Line: 27
[UserFrosting Application Error.pdf](https://github.com/userfrosting/UserFrosting/files/969029/UserFrosting.Application.Error.pdf)

**Comment by lcharette** [comment]
Probably missed a step in the installation process. The assets are not built : https://learn.userfrosting.com/basics/installation#npm-dependencies

Join us on the [chat](http://chat.userfrosting.com) if you need further assistance with this.
