### ISSUE TITLE
Create New User Dialog: Only partially visible

### ISSUE THREAD

**Issue by gracedigital** [userfrosting/UserFrosting#701]
On v4.0.16-Alpha, clicking only shows part of the dialog (see attachment)
![screen shot 2017-05-03 at 9 04 24 am](https://cloud.githubusercontent.com/assets/13338159/25669999/39527876-2fe0-11e7-9c7f-04c729693e99.png)

Behaves the same in FF 53.0 (64-bit) and Chrome 57.0.2987.133 (64-bit) on MacOs

**Comment by lcharette** [comment]
Can't replicate. Chrome 58.0.3029.96 on MacOS Sierra

Did you installed any custom packages or custom code?

**Comment by gracedigital** [comment]
Have some extensions added in chrome but none are active and only 2 are active in FF and there are no common extensions/plugins between them.
![screen shot 2017-05-03 at 10 08 32 am](https://cloud.githubusercontent.com/assets/13338159/25679692/03e21e3a-3003-11e7-9e28-7022dd3b8aa3.png)
![screen shot 2017-05-03 at 10 06 38 am](https://cloud.githubusercontent.com/assets/13338159/25679697/06301822-3003-11e7-9362-59405c04e145.png)

**Comment by gracedigital** [comment]
Did not install any custom code or packages.  Its a vanilla install with some additions through following the tutorial.  

I also found the same behavior happens in Safari 10.1.1.
I also found the same behavior happens when trying to edit the user.

![screen shot 2017-05-04 at 1 19 28 am](https://cloud.githubusercontent.com/assets/13338159/25695496/34dcef8c-3068-11e7-997c-0219ff3459b0.png)

Safari is reporting that the error is occurring in the attachUserForm function.
![screen shot 2017-05-04 at 1 23 54 am](https://cloud.githubusercontent.com/assets/13338159/25695580/928db242-3068-11e7-83a6-4a9007fe503a.png)

**Comment by lcharette** [comment]
> Did not install any custom code or packages. Its a vanilla install with some additions through following the tutorial.

It does sounds like something you changed broke this. I still can't replicate on vanilla install with no edits. If you made all of your changes in a `sprinkle`, you can try disabling that Sprinkle in the `sprinkles.json`  file and see if this works again. 

Again, meet us on the chat about this issue, it'll be easier to debug.

**Comment by gracedigital** [comment]
Confirmed.  Removed the sprinkle I built via the tutorial from the sprinkles.json and it resolved the problem.

**Comment by lcharette** [comment]
I'll close the issue then, we can continue this on the chat.
