### ISSUE TITLE
Edit user buttons in  settings needs top or bottom margins

### ISSUE THREAD

**Issue by abdullahseba** [userfrosting/UserFrosting#703]
![image](https://cloud.githubusercontent.com/assets/25548754/25835365/091f10b6-3476-11e7-87ca-194ecfb743c1.png)
Should be:
![image](https://cloud.githubusercontent.com/assets/25548754/25835411/78a47cbe-3476-11e7-8320-712a449e46fd.png)
also would be nice if they had there own row.

**Comment by alexweissman** [comment]
Addressed by https://github.com/userfrosting/UserFrosting/commit/4fc4ef93b2bb450a9cc16a839dc946b43e981b14.
