### ISSUE TITLE
Support non-standard CSRF sources

### ISSUE THREAD

**Issue by Silic0nS0ldier** [userfrosting/UserFrosting#706]
Standards such as OAuth provide a means to implement CSRF protection, but currently UserFrosting can't be easily adapted (and by easily, I mean via Sprinkles) to provide protection in these scenarios.

My idea for this, is a series of callbacks that are executed before the Slim CSRF middleware kicks in, which inspect the request for CSRF protection values wherever they may be stored, returning true if the CSRF is found. If true is returned, some code would inject the CSRF values, ready for Slim CSRF to take over.

**Comment by alexweissman** [comment]
Possibly related to #665.

**Comment by Silic0nS0ldier** [comment]
Not quite. Same area, but different issue. Could influence implementation of the other though.

**Comment by alexweissman** [comment]
Are OAuth routes actually susceptible to CSRF attacks?  What's the difference between your proposal, and just outright [blacklisting the route from CSRF protection](https://learn.userfrosting.com/routes-and-controllers/client-input/csrf-guard#BlacklistingRoutes)?

It seems a little odd to have CSRF middleware solely for transforming the request for the benefit of another CSRF middleware.  Shouldn't we just fork Slim-Csrf and adapt it for our own needs instead?

**Comment by Silic0nS0ldier** [comment]
Yes. OAuth is susceptible to all the same CSRF attacks. http://spring.io/blog/2011/11/30/cross-site-request-forgery-and-oauth2
