### ISSUE TITLE
Landing page hard-coded

### ISSUE THREAD

**Issue by jian118** [userfrosting/UserFrosting#707]
Creating new user sends an email to the new user. After setting new password, they are being brought to dashboard. If default users' permission to dashboard is being removed, error would occur. 

the redirect should use $this->ci->determineRedirectOnLogin service instead of hard-coded redirect so that it's easier to overwrite. The best would be loading "default landing location" from config file instead.

**Comment by lcharette** [comment]
Duplicate #680
