### ISSUE TITLE
Intelligent tracebacks in loggers/error reports

### ISSUE THREAD

**Issue by alexweissman** [userfrosting/UserFrosting#710]
Typical error traces contain a lot of "fluff" in the stack trace - tracing to Slim's stack, or Eloquent's stack, or other third-party components which the dev has no control over.  It might be a cool feature if we had the option to filter stack traces to only show the portion relevant to the developer's code.

**Comment by alexweissman** [comment]
Not sure how to actually do this, but it's still an issue for me. I spend far too much time scanning through stack traces for `vendor` classes to find the bugs in my own code.

**Comment by Silic0nS0ldier** [comment]
Where is the stacktrace you are thinking of being shown? Its not too much trouble to filter a stacktrace (it'll have file paths in it which can be used to aid filtering), but where and what is responsible for showing it determines practicality and the sort of challenges that might be faced.

**Comment by alexweissman** [comment]
It's anywhere a full stack trace is rendered, usually from an exception being thrown. Honestly this is kind of outside the scope of UF, but if there is another package that addresses this it might be worth integrating as a core feature.

**Comment by alexweissman** [comment]
Looks like xdebug can be configured to filter out `vendor` paths, but I haven't tried it: https://stackoverflow.com/questions/60068158/xdebug-trace-function-how-to-exclude-vendor-dir

**Comment by Silic0nS0ldier** [comment]
Error handling is handled by https://github.com/userfrosting/UserFrosting/blob/fb1b72148d23654315f849d7188fab306211b227/app/sprinkles/core/src/Error/Renderer/WhoopsRenderer.php in debug/dev mode. It should be possible to [filter](https://github.com/filp/whoops/blob/master/docs/API%20Documentation.md#-whoopsexceptionframecollection) the shown stack frames, though I'm wary of hiding vendor frames entirely (making it access to them hard would arguably be worse then having to scan over a stack trace full of vendor frames).
