### ISSUE TITLE
Function declaration typehinting for all classes and functions

### ISSUE THREAD

**Issue by alexweissman** [userfrosting/UserFrosting#711]
PHP has [function declaration typehinting](http://php.net/manual/en/functions.arguments.php#functions.arguments.type-declaration) for classes, arrays, and callables.  Why aren't we using that consistently everywhere?

**Comment by Silic0nS0ldier** [comment]
Should definitely be used. It's an effective way to improve quality of code (in the worst cases) and can eliminate entire misguided debugging cycles. 

Just keep in mind that string, int, float and bool are PHP 7 only.

**Comment by lcharette** [comment]
> Just keep in mind that string, int, float and bool are PHP 7 only.

I knew there was something special regarding this and PHP 7...

I guess it's something that can either be changed once, or as we go. If we want to drop 4.1 soon, it could be done as we go further, or at least moved to a 4.1.x version (shouldn't be any breaking change...)

**Comment by lcharette** [comment]
I think I got most of it... I went thought all classes as pictured in 36affb0. Fixed the comments, classes and misc styling. Checked with [Serenata](https://serenata.gitlab.io) in Atom and php-cs-fixer. 

Two issues remains : 
1. Some non existing classes in [WhoopsRenderer](https://github.com/userfrosting/UserFrosting/blob/590a1748158d0875c624d9892c10914df338ef2b/app/sprinkles/core/src/Error/Renderer/WhoopsRenderer.php#L143)
2. Serenata not being happy with [this variable argument in ClassMapper](https://github.com/userfrosting/UserFrosting/blob/590a1748158d0875c624d9892c10914df338ef2b/app/sprinkles/core/src/Util/ClassMapper.php#L84)

...but that's for another issue. 

For now, we (and by we I mean @alexweissman) should probably setup StyleCI on this repo ❤️
