### ISSUE TITLE
Browser history handling in ufTable / tablesorter

### ISSUE THREAD

**Issue by alani1** [userfrosting/UserFrosting#712]
In the admin panel ufTable adds parameters for sorting / filtering / pagination  to the url. This adds additional entries in the browser history and affects usability when navigating with "Back"-Button.

**Example:**
Original URL: `http://localhost/admin/users`
is rewritten to 
`http://localhost/admin/users#&sort[table-users][name]=asc&page[table-users]=1&size[table-users]=10
`

When using two seprate ufTables on one page, the situation becomes worse as suddenly not two but 6 entries are created in the Browser History. the correct behaviour would probably be to remove / delete the original entry from the History.

**Comment by alexweissman** [comment]
@alani1 This appears to be an interaction between the [`sort2Hash`](https://mottie.github.io/tablesorter/docs/example-widget-sort-to-hash.html) and [`saveSort`](https://mottie.github.io/tablesorter/docs/example-widget-savesort.html) Tablesorter widgets].  

`sort2Hash` stores the current sort/filter state in the URL hash, adding a new entry to the browser history for each change.  Meanwhile `saveSort` rebuilds the hash when you visit a page, effectively creating the two history entries (one for the original, and one with the hash).

One option is to simply disable either the `sort2Hash` or `saveSort` widget on your tables.  It would be good, though, if `saveSort` did not create another browser history entry.

**Comment by alexweissman** [comment]
Fixed as of v4.1.9; see https://github.com/userfrosting/UserFrosting/commit/65384c45c8f4f99b9d893edb7034e993402c944e

I've submitted a PR to the main Tablesorter repo as well, so hopefully we won't need this temporary patch once the PR gets approved and released.
