### ISSUE TITLE
Invalid options for Tablesorter is triggering warnings

### ISSUE THREAD

**Issue by Silic0nS0ldier** [userfrosting/UserFrosting#715]
I'd guess another plugin that interacts with Tablesorter is triggering this. Technically doesn't cause any issues, but ideally there should be no out-of-the-box warnings.
![image](https://cloud.githubusercontent.com/assets/17376090/26397037/561afaa8-40b8-11e7-8fea-3a9cf53167ad.png)

**Comment by alexweissman** [comment]
Yeah, I brought this up with Mottie and he has fixed it.  Unfortunately, newer versions of Tablesorter which fix this problem, also introduce other problems [#688](https://github.com/userfrosting/UserFrosting/issues/688).  So we have resolve that first.

**Comment by alexweissman** [comment]
Fixed in https://github.com/userfrosting/UserFrosting/commit/092b7d26b4ae55946295eeb161770d6fda58425d.  Will be rolled out in v4.1.
