### ISSUE TITLE
Invalid date formats for records from MSSQL

### ISSUE THREAD

**Issue by naeazach** [userfrosting/UserFrosting#719]
Any records created via MSSQL throws the following error:  

"The format separator does not match"

It appears the date formats coming back into the app mismatch what is expected due to the way MSSQL formats dates.  I added these to UFModel and it seems to have fixed it:

    public function getDateFormat()
    {
        return 'Y-m-d H:i:s.u';
    }

    public function fromDateTime($value)
    {
        return substr(parent::fromDateTime($value), 0, -3);
    }

REF:  https://github.com/laravel/framework/issues/14247

**Comment by luz291014** [comment]
la solucion que me hizo desesperar tanto es ir a la ruta si es en atom:ctrl+p iluminate\database\query\grammars\sqlservergrammar

y en el metodo public function getDateFormat()
{
/borrar los guiones y ponerlos todo junto para que en mi caso MsSQL lo pueda filtrar como Datetime
    return 'Ymd H:i:s.u';
}


aplicable tambien cuando marca el error 22077 , los tipos de datos estan fuera del intervalo.

**Comment by hexonthebeach** [comment]
SqlServer returns datetimes formatted based on the locale settings of the host server.
In my case the language is set to 'English' and it outputs datetime values as : 2018-05-02 14:26:39 +00:00
Setting the protected $dateFormat string in your own model to match that format works for me.
in my case : protected $dateFormat = 'Y-m-d H:i:s P';
