### ISSUE TITLE
deploy instructions for v4

### ISSUE THREAD

**Issue by naeazach** [userfrosting/UserFrosting#720]
are there any deploy instructions laying around?  Or are there only specific folders in the app you are supposed to publish?  Excuse my noobishness, .NET developer in PHP/*nix waters.  

Great job on the framework though, I've learned a ton from messing with it.

**Comment by alexweissman** [comment]
It's on our todo list.  In the meantime, please join us in chat.

**Comment by alexweissman** [comment]
This is complete!  Check out the new [Going Live](https://learn.userfrosting.com/going-live) chapter.
