### ISSUE TITLE
Create and Manage Multiple User Groups in UserFrocasting.

### ISSUE THREAD

**Issue by ils-rajnikantd** [userfrosting/UserFrosting#723]
Hello,
I am new to UserFrocasting Framework. Can anyone help me or provide some details about how can I create or manage multiple user groups in UserFrocasting.
Currently I am only able to see one primary user group and not able to add any new additional group.

Is it possible to do the same?

Waiting for valuable comments.

**Comment by lcharette** [comment]
You can create multiple groups (see `/admin/groups` route), but the default behavior is for a user to belong only to one group. It is not possible to assign a user to multiple groups.

**Comment by ils-rajnikantd** [comment]
Thanks @lcharette for your comment. 
Can't we write custom script to fulfill the requirement of a user assign to multiple groups?
Another question is, how can we assign user roles or group roles?

**Comment by lcharette** [comment]
You can add this feature yourself by extending the core code using the Sprinkle system. You can assign one or more role to a user using the UI, but you can't assign a role to a group by design. 

Join us in chat if you need more help figuring this out : https://chat.userfrosting.com
