### ISSUE TITLE
Improve table row menus in mobile views

### ISSUE THREAD

**Issue by alexweissman** [userfrosting/UserFrosting#724]
We're using the [`dropdown-menu-right` Bootstrap class](http://getbootstrap.com/components/#dropdowns-alignment) to make row menus in tables line up nicely with the dropdown button:

![screen shot 2017-06-01 at 4 40 27 pm](https://cloud.githubusercontent.com/assets/5004534/26699811/15634236-46e9-11e7-92ca-75b528cf0d95.png)

Unfortunately in the new reflowed mobile table views, it gets cut off by opening to the right:

![screen shot 2017-06-01 at 4 38 14 pm](https://cloud.githubusercontent.com/assets/5004534/26699821/26daf2c0-46e9-11e7-8127-487c4bf98e5a.png)

Honestly, these dropdown buttons don't look that great in mobile views anyway.  Something like an accordion menu might look nicer for mobile.  I don't know how to implement this, but maybe someone else can take a crack at it?

**Comment by lcharette** [comment]
Is that the button on each table row? Are the same options available on the user info page? If so, those buttons could be hidden completely on mobile view.

**Comment by alexweissman** [comment]
Oh, good point.  I hadn't thought of that option.

Actually, I'm probably the worst person to ask about mobile UX so...I'd like to hear others' thoughts as much as possible!

**Comment by SarahBaghdadi** [comment]
I'm fixing this in #792. But I'm still working on the best way to implement it, since this is a bootstrap problem.

**Comment by alexweissman** [comment]
Fixed in 4.1.12 (see 922313d2ecd49a64039ab0109ba9f963760a06fe)
