### ISSUE TITLE
Renaming folders and files

### ISSUE THREAD

**Issue by SarahBaghdadi** [userfrosting/UserFrosting#726]
- [x] `assets/local` to `assets/userfrosting`
- [ ] `locale` to `translations`
- [ ] `schema` to `validation` (or other more semantic name...)
- [x] `bundle.config.json` to `assets.json`

Not a folder, needs to be a separate issue:
- [x] root sprinkle to a style difference for the root user within admin sprinkle

**Comment by lcharette** [comment]
Root sprinkle actually related to #597...

For `locale`, I'm not a big fan of changing that (personal taste)... But if we do change that, `lang` or `language` would make more sense.

**Comment by SarahBaghdadi** [comment]
I just found a laravel skeleton that uses `lang`. I wonder if this is commonly used?

**Comment by SarahBaghdadi** [comment]
Sprinkles could be renamed more semantically as well.  Right now, its hard for a reader to distinguish between `core`, `account`, `admin`, and `root`.  My suggestion is to rename:
 
- `basic` in place of `core` 
- `user` in place of `account`
- and in the documentation suggest `mysitename` instead of `site`

This way your sprinkles would be:
- `admin`(admin functionality)
- `basic` (a basic website)
- `user` (user functionality)
- `mysitename` (my own functionality, content, and styles)

**Comment by SarahBaghdadi** [comment]
Templates...

The main change I have is renaming `layouts` to something more semantic. When I read `layouts` it suggests templates which format a page like: 

![image](https://cloud.githubusercontent.com/assets/8106569/26756968/5636449a-487c-11e7-92b7-bec0f4d99d5d.png)

Also when I read `layouts`, Its hard to understand the difference between layouts and pages.  This creates a problem especially when there are layouts with the same name as pages like `layouts/dashboard` and `pages/dashboard`.  

These aren't really layouts but foundations for pages that insert the basic elements of any page or page-grouping. The pages themselves are closer to the layouts. These are like foundations.  

I looked around in a thesaurus for a while and couldn't find anything really appropriate to name them. Undergarments? bedrock? groundwork? essence? None of these really fit. 

In the end, I'm suggesting `base`. I realize it sounds less semantic than `layouts`, but I think its way less confusing.  So `templates/base` works better for me.  

That way your template structure is:
- base (foundations for pages)
- components (elements of pages)
- mail
- pages

Or I just realized that you could go with `foundations`, you might like that better than `base`.

These last two may be nit picking, but...

- Within the core sprinkle, I see that you have both `layouts/basic` and `layouts/default`.  This is a little confusing.  If they need to be separate templates, I'd suggest renaming then to make it clear what the difference is.

- Within specific sprinkles, when you have a template folder with only one item in it, for example `account/templates/pages/error/compromised.twig.html` or `account/templates/components/default/main-nav.twig.html`is there usually a reason for it?

**Comment by alexweissman** [comment]
@SarahBaghdadi it's also worth noting that it's not just pages that have these base layout templates.  There are also base layouts for other components, like modals, tables, forms, etc.  So maybe we should have something like `pages/base`, `components/tables/base`, etc?

Or we could eliminate the special subdirectory altogether, and just keep these "base layouts" in the same directory as the leaf templates.

**Comment by SarahBaghdadi** [comment]
## Suggested changes to templates

### Account sprinkle
-`components/default/main-nav.html.twig` move up one level to `components/`
-`components/default/` delete  the folder `default/`

### Admin sprinkle
-`layouts/dashboard.html.twig` rename to `base.html.twig` and move to `pages/`
-`layouts` delete  the folder `layouts/`

### Core sprinkle
-`components/default/main-nav.html.twig` move up one level to `components/`
-`components/default/page-header.html.twig` move up one level to `components/`
-`components/default` delete  the folder `default/`
-`layouts/basic.html.twig` rename to `base.html.twig` and move to `pages/`
-`layouts/default.html.twig` move to `pages/`
-`layouts/error.html.twig` move to `pages/error/`
`layouts/modal.html.twig` move to `components/`
-`pages/error/default.html.twig` combine with `error.html.twig`

**Comment by lcharette** [comment]
I do like the idea of getting rid of `components/default/` actually. 

As for layout... I'm not sure. It does makes a lot of sense if you consider the inheritance from the Twig `extends` function. But since I don't know how themes will be handles in future version yet, I don't know if keeping the base layout separated might help... :/

**Comment by alexweissman** [comment]
I think we should keep `locale` the way it is for now.  The contents of `schema/` could perhaps be moved to `schema/requests/` - in case we end up having other types of schema in the future (or even if some community sprinkles use other kinds of schema).

As for templates, it's worth pointing out that other things besides pages can have base "abstract" templates.  For example, `table-paginated` is a template that is meant to only be used when it is extended.  I propose we have our base template directories look like:

```
dashboard/
forms/
mail/
modals/
navigation/
tables/
pages/
...
```

If necessary, the "abstract" templates could go inside `abstract/` directories _inside_ these main categorical directories.

**Comment by alexweissman** [comment]
Ok, I have finished my reorganization.

Templates have been reorganized as mentioned above.  Locale will remain as is.  Request schema have been moved to `schema/requests/`.
