### ISSUE TITLE
bower pulls down duplicate libraries

### ISSUE THREAD

**Issue by naeazach** [userfrosting/UserFrosting#727]
When adding a bower package, the installdoesn't seem to be checking if the items package's dependant items are installed in one of the other sprinkles.  Here is my bower file:
`{
  "name": "site-assets",
  "version": "0.0.1",
  "homepage": "https://github.com/userfrosting",
  "authors": [
    "zach"
  ],
  "moduleType": [
    "node"
  ],
  "license": "MIT",
  "ignore": [
    "**/.*",
    "node_modules",
    "bower_components",
    "assets/vendor",
    "examples",
    "demo-resources",
    "demo",
    "test",
    "tests"
  ],
  "dependencies": {
    "jqueryui-touch-punch" : "*",
    "fontIconPicker":"^2.0.0"
  }
}`

**Comment by Silic0nS0ldier** [comment]
This is a known issue, and any resolution would be a major undertaking. Since this presents no issue, its low priority. That said, I'll let you know if there are any developments.

**Comment by alexweissman** [comment]
🗿 ❄️

**Comment by Silic0nS0ldier** [comment]
As part of the pending introduction of NPM support for frontend assets (which requires a number of changes to be conducted to be efficient), this issue will soon be fixed. (still a major undertaking, but now it has the support of additional issues)

**Comment by Silic0nS0ldier** [comment]
I've got this issue resolved in a developmental UF 4.0 branch (`4.0-feature-npm-assets`).

By the next release (at least for UF4.0), all vendor assets will live in `app/assets/bower_components` and `app/assets/node_modules`.

When in default (or dev) mode, assets pulled from these locations will have `assets-raw/vendor-bower` and `assets-raw/vendor-npm`.

When installing vendor assets, console output will be similar to the following:
![image](https://user-images.githubusercontent.com/17376090/28489280-95104352-6f03-11e7-9a1c-db753705f371.png)

**Comment by alexweissman** [comment]
Does seem to make more sense than each Sprinkle having its own `assets/vendor` directory!
