### ISSUE TITLE
CLI command to manage sprinkle 

### ISSUE THREAD

**Issue by lcharette** [userfrosting/UserFrosting#728]
As of `4.1`, the new `bakery` cli will create a default `sprinkles.json` if none is present when first installing UF. Any modifications to the sprinkles list requires to edit the  file manually. Depending on the deployment option, it could be useful to have a command to manage the sprinkle list. It would also be easier to install community sprinkles.

One problem with such command is how to define the order of the sprinkles. We'll need to find a way to order stuff from within the cli...

**Comment by alexweissman** [comment]
How about:

1. Load the current contents of `sprinkles.json`, number them, and display the numbered list;
2. Prompt the user to choose "Load (l)ast" or "Load (b)efore...";
3. If they choose (b)efore, then can then specify the number of the Sprinkle to load before;
4. Insert the Sprinkle name in the appropriate position;
5. Write back the contents of `sprinkles.json`.

**Comment by alexweissman** [comment]
Should also provide a command-line option for this as well.  `--load last` and `--load before __`?
