### ISSUE TITLE
Table Filter-Select doesn't select the active option

### ISSUE THREAD

**Issue by lcharette** [userfrosting/UserFrosting#744]
When visiting a page with a table sorter instance (without any hash already defined in the url, a link for example), the active state won't be applied the `filter-select` (the select itself). The table filter is still set. 

It should work when reloading the page.

This was fixed in 4.1, but caused another bug (See #688 and commit 5b77d54).

Basically, when adding the select option from the API ([here](https://github.com/userfrosting/UserFrosting/blob/5b77d54f373777ae3b11d049029087920b7690f4/app/sprinkles/core/assets/userfrosting/js/uf-table.js#L438)), it also need to apply the active state. Previous option was [to refresh the filters](https://github.com/userfrosting/UserFrosting/commit/5b77d54f373777ae3b11d049029087920b7690f4), but that caused issue #688. 

When reloading the page, it shouldn't be an issue since [sort2hash apply a timeout](https://github.com/Mottie/tablesorter/blob/master/js/widgets/widget-sort2Hash.js#L28-L44) (To it apply the filter *after* the select is created).

**Comment by alexweissman** [comment]
Seems like the solution to this would be:

1. After the select options are generated (after `buildSelect` is called), determine the current filter value for that column;
2. Locate the select control using `.tablesorter-filter[data-column='{columnNumber}']` or something similar;
3. Set the active `option` based on the current filter value.

**Comment by alexweissman** [comment]
Ok, I've pushed a potential fix to `hotfix`.  Can you try it out and make sure it doesn't break anything?

**Comment by alexweissman** [comment]
Alright, fixed in 4.1.5 (https://github.com/userfrosting/UserFrosting/commit/81bf82248667ce8ab9eb2c55f8b58751012d8e41).
