### ISSUE TITLE
Missing permission slug in Manage permissions modal

### ISSUE THREAD

**Issue by lcharette** [userfrosting/UserFrosting#748]
![capture d ecran 2017-06-26 a 21 19 42](https://user-images.githubusercontent.com/2566513/27566759-37fe54ea-5ab5-11e7-85db-726031013b8d.png)

**Comment by alexweissman** [comment]
Ok, I figured this out.  This is my fault (and Handlebar's).  I added a `slug` Handlebars helper in 4.1, and this collides with the `slug` parameter that we're trying to pass in.

**Comment by alexweissman** [comment]
Oddly enough, the first place where I found this mentioned was here: https://github.com/adamrenklint/asimovjs.org/issues/20

**Comment by alexweissman** [comment]
Fixed in https://github.com/userfrosting/UserFrosting/commit/7396a2ca1d1d22ee1f5a652646572d3cf98fa2f2.  See #756 for discussion on the underlying issue.
