### ISSUE TITLE
Bakery errors show in HTML

### ISSUE THREAD

**Issue by abdullahseba** [userfrosting/UserFrosting#751]
![clipboard - june 28 2017 11_06 pm](https://user-images.githubusercontent.com/25548754/27664846-bcd84060-5c61-11e7-9ed4-ca220a8f9b8b.png)

**Comment by Silic0nS0ldier** [comment]
This has been around even before bakery. Any fatal unhandled error in any php based cli in uf does this.

**Comment by lcharette** [comment]
I can't even replicate an error that throw that kind of error :/

**Comment by alexweissman** [comment]
I'm pretty sure this is caused by the implementation of `ShutdownHandler`: https://github.com/userfrosting/UserFrosting/blob/master/app/sprinkles/core/src/Util/ShutdownHandler.php#L62-L69

**Comment by abdullahseba** [comment]
@Silic0nS0ldier Maybe this is a windows only issue. Can you replicate?

**Comment by abdullahseba** [comment]
@alexweissman I think so too from the error log.

**Comment by lcharette** [comment]
Ok got it. Need a syntax error in migration.

Problem is we define the thing as CLI [here](https://github.com/userfrosting/UserFrosting/blob/master/app/system/UserFrosting.php#L128), but we can't access that config elsewhere, like [here](https://github.com/userfrosting/UserFrosting/blob/master/app/sprinkles/core/src/Util/ShutdownHandler.php#L62-L69).

**Comment by Silic0nS0ldier** [comment]
Just for the record, any error that causes the slim application error handling to kick in will result in this being output. Would be nice if there were a way to make it more CLI friendly.

**Comment by Silic0nS0ldier** [comment]
Output comes from [here https://github.com/slimphp/Slim/blob/fb5356a0f16ef027035155067377239c938bb767/Slim/Handlers/PhpError.php] for reference.
