### ISSUE TITLE
Tables needs data-priority 

### ISSUE THREAD

**Issue by abdullahseba** [userfrosting/UserFrosting#752]
When disabling some columns than selecting auto, the searchbar name or both disappear.
This is apparently fixed by adding the `data-priority` attribute.
For some reason the users table doesn't appear to be affected.
![image](https://user-images.githubusercontent.com/25548754/27665791-4b6fda18-5c67-11e7-8745-a06bc5cd4d4e.png)

**Comment by alexweissman** [comment]
This is now taken care of in 4.0.24 and 4.1.3 (https://github.com/userfrosting/UserFrosting/commit/3da33a2a56610aa98b1b9bb37c6e8e375a6fe66b).
