### ISSUE TITLE
User class path is hardcoded in the AdminController

### ISSUE THREAD

**Issue by freakinhuge** [userfrosting/UserFrosting#753]
The `User` class path is hardcoded in the [`app/sprinkles/admin/src/Controller/AdminController.php`](https://github.com/userfrosting/UserFrosting/blob/master/app/sprinkles/admin/src/Controller/AdminController.php#L47) controller.

**Comment by alexweissman** [comment]
This is now taken care of in 4.0.24 and 4.1.3 (https://github.com/userfrosting/UserFrosting/commit/aa43591ee0c26c7d928b32b2ec682de199c60e23).
