### ISSUE TITLE
Avoiding collisions between Handlebars helper names and variable names

### ISSUE THREAD

**Issue by alexweissman** [userfrosting/UserFrosting#756]
As https://github.com/userfrosting/UserFrosting/issues/748 demonstrated, Handlebars doesn't distinguish between invoking a helper, versus referencing a variable parameter, in its syntax:

```
// Reference a helper called 'slug'
<code>{{slug}}</code>

// Reference a parameter called 'slug'
<code>{{slug}}</code>
```

There are basically two ways that we can avoid this issue:

1. Use `{{this.slug}}` to explicitly reference the variable, not the helper;
2. Come up with a special naming convention for our custom helpers.

I think (1) would be a better choice in terms of compatibility, not only with our current helpers but with other helper libraries that people might choose to load.  I'm not sure if there any drawbacks, other than having to make a lot of changes in the existing templates.  Thoughts?

**Comment by lcharette** [comment]
1 is probably a nasty BC, but looks like a better option.

**Comment by alexweissman** [comment]
Eh, most people won't experience collisions even if they don't update their templates to use `this.`.

**Comment by lcharette** [comment]
Oh. so it's not something that requires changes in the controllers?

**Comment by alexweissman** [comment]
Nope, these are just changes to the client-side templates.

**Comment by lcharette** [comment]
Closing, as plan is to get rid of Handlebar ASAP
