### ISSUE TITLE
POST, PUT, and DELETE methods should always return valid JSON

### ISSUE THREAD

**Issue by alexweissman** [userfrosting/UserFrosting#757]
Right now, on successful requests, most of our `POST, PUT, DELETE` endpoints return an empty response body.  I propose that we should change them so that they always return valid JSON (except when in AJAX debug mode), even on successful requests.

Even if the request body is "empty" (recall that error/success messages are sent via the separate `/alerts` endpoint), they should still return `{}` to indicate an empty response.

**Comment by alexweissman** [comment]
I'm a little reluctant to add this to 4.1, because it _is_ changing the API interface.  There could be, for example, client applications which use an empty response body to dictate behavior.

I recommend we implement this in 4.2.

**Comment by lcharette** [comment]
So.... We need to change `return $response->withStatus(200);` to `return $response->withJson([], 200);` ?

**Comment by alexweissman** [comment]
Yep. We could even start injecting success/error messages into the response body, in preparation for UF 5.0, when I want to deprecate the separate alert stream and instead cache messages in browser storage when necessary.

**Comment by lcharette** [comment]
Done in 32e6465 for 4.2
