### ISSUE TITLE
Missing german translation-keys 

### ISSUE THREAD

**Issue by kevinrombach** [userfrosting/UserFrosting#760]
Im updated to 4.1 and have now some translations missing in german language:
 
First: 

`PAGINATION.OUTPUT`

English version: https://github.com/userfrosting/UserFrosting/blob/master/app/sprinkles/core/locale/en_US/messages.php#L62
German version: https://github.com/userfrosting/UserFrosting/blob/master/app/sprinkles/core/locale/de_DE/messages.php#L54-L61

Also :

`TOGGLE_COLUMNS`

is missing in German admin sprinkles localization.

**Comment by splitt3r** [comment]
You could add them and create a pull request 😀

**Comment by kevinrombach** [comment]
Never did that but i can try haha

**Comment by splitt3r** [comment]
It´s really easy :) and you can ask for help in the chat if anything is not clear.

**Comment by alexweissman** [comment]
Seems like this has been completed?  And merged into `master` without a revision release?  😱
