### ISSUE TITLE
Set `display_errors` to `on` for development configs

### ISSUE THREAD

**Issue by TheMasquerader** [userfrosting/UserFrosting#762]
Seems like a good idea to have `display_errors` set to `on` by default for the `dev.php` development config.

**Comment by alexweissman** [comment]
Agreed.  Also, ref #653.

**Comment by alexweissman** [comment]
Should we make the `default.php` setting `on`, and then set it to `off` in `production.php`?  Or only set it to `on` in `debug.php`?

Or yet another idea - don't set it at all in `default.php` (just use whatever is configured as the default for PHP), and then set it to `on` in `debug.php` and `off` in `production.php`?

**Comment by lcharette** [comment]
Since default is the one used by default by UF, It might brings inconsistencies with the doc or problem experienced by new dev during install.

**Comment by alexweissman** [comment]
Hmm, good point.  But by the same token, what do we do about devs who deploy to a server where it is `off` by their default webserver config settings?  If UF's default configuration overrides it to be `on`, and they fail to switch their site over to `production`, that could be a security problem.

On the other hand, we could just say "well they need to read the manual before deploying".

**Comment by alexweissman** [comment]
Ok, I have decided to go with:

> make the `default.php` setting `on`, and then set it to `off` in `production.php`

I've also added `log_errors` and factored all PHP settings into a common `php` subkey.  We now let PHP handle logging/displaying fatal errors, and logging has been factored out of `ShutdownHandler`.

**Comment by alexweissman** [comment]
Fixed in v4.1.8.
