### ISSUE TITLE
Creating/Editing Groups - Description does not save

### ISSUE THREAD

**Issue by zharding** [userfrosting/UserFrosting#766]
When creating or editing a group the description field is passed via post however, it doesn't make it into the $data array to be saved. 

The YAML defines `description` but has no operators. This may be a cause?

Ref:
https://github.com/userfrosting/UserFrosting/blob/master/app/sprinkles/admin/schema/requests/group/edit-info.yaml

**Comment by alexweissman** [comment]
If YAML is supposed to support "empty" keys, then this is probably something we should fix in Fortress, if possible.

**Comment by alexweissman** [comment]
Fixed in v4.1.4 (https://github.com/userfrosting/UserFrosting/commit/4b8948ff6059afada439f282c83b9eeb06f2fec7)
