### ISSUE TITLE
checkAccess should confirm an interface, not a specific class

### ISSUE THREAD

**Issue by alexweissman** [userfrosting/UserFrosting#769]
```
PHP Catchable fatal error:  Argument 1 passed to UserFrosting\Sprinkle\Account\Authorize\AuthorizationManager::checkAccess() 
must be an instance of UserFrosting\Sprinkle\Account\Database\Models\User, 
instance of UserFrosting\Sprinkle\Btoms\Database\Models\Worker given, 
called in /Users/alexw/dev/htdocs/btoms/app/sprinkles/admin/src/Controller/AdminController.php 
on line 42 and defined in 
/Users/alexw/dev/htdocs/btoms/app/sprinkles/account/src/Authorize/AuthorizationManager.php 
on line 76
```

This is a problem because now my authenticated user object has to be either a `User`, or some class that inherits from `User`.  We should instead have it check that the class simply implements some interface (for example, a `UserInterface`) so that one could write their own custom class for users.

**Comment by alexweissman** [comment]
`Authenticator` should probably do something similar.  We have the dynamic class mapper in there, but it would be even better if we could factor that out and have `Authenticator` accept some kind of generic `UserProvider` interface instead.

**Comment by lcharette** [comment]
Done in 32b3046 for 4.2

@alexweissman Let me know if you don't like the interface name 😛
