### ISSUE TITLE
Improve styling for page description and breadcrumbs

### ISSUE THREAD

**Issue by SarahBaghdadi** [userfrosting/UserFrosting#772]
- Page description is too light to easily read and has odd padding.
- Breadcrumbs need some love. I think they'd look better to the left under the header and a little bigger (14px). Or maybe they're not needed since they effectively contain the same information as the site header and page header.

**Comment by lcharette** [comment]
Is this still an issue, now that we don't have a root sprinkle anymore ?

**Comment by alexweissman** [comment]
Seems like this issue was misnamed - descriptions and breadcrumbs aren't unique to the (nonexistent) `root` Sprinkle.
