### ISSUE TITLE
Incorrect link in the CSRF Protection section of the manual.

### ISSUE THREAD

**Issue by HenryHatten** [userfrosting/UserFrosting#774]
The [CSRF Protection page ](https://learn.userfrosting.com/routes-and-controllers/client-input/csrf-guard) of the manual has an incorrect twig file reference - in the [Injecting the Tokens Into Forms](https://learn.userfrosting.com/routes-and-controllers/client-input/csrf-guard#InjectingtheTokensIntoForms) it should read` {% include "forms/csrf.html.twig" %}` and not `{% include "pages/partials/csrf.html.twig" %}`.

**Comment by alexweissman** [comment]
Thanks, fixed!
