### ISSUE TITLE
Create User Without SMTP

### ISSUE THREAD

**Issue by pauljcurtis** [userfrosting/UserFrosting#776]
For development could a user be created without the requirement for SMTP settings. Could the 'email' go to logs instead?

**Comment by alexweissman** [comment]
I think we could consider a general switch that shunts all mail to a log file instead, during development.

**Comment by lcharette** [comment]
Would make the Vagrant install perfect... It's the only thing *not* set automatically in #829

**Comment by lcharette** [comment]
Duplicate of #763.
