### ISSUE TITLE
Support multiple strategies for database integration tests

### ISSUE THREAD

**Issue by alexweissman** [userfrosting/UserFrosting#777]
Right now, we only support the "database transaction" technique for integration tests that involve the database.  Basically, you start a transaction on the main database, make your assertions, and then roll back the transaction in the test teardown.

This is a fine approach, [but not the only one](https://softwareengineering.stackexchange.com/a/104522/149969).  We should also support the possibility to spin up an entirely new DB every time, running our migrations on this testing DB.

Even when using transactions, we should probably set up a temporary DB at the beginning of the test suite and run migrations on it once.  Each test class can then have the option of using a transaction-based approach _if it chooses_, to improve performance.  No matter what, though, UF's `default` database will never be touched.

**Comment by lcharette** [comment]
I'll close this issue as it's currently implemented in the `feature-migrator` branch slated for version 4.2 and included in #795. Bakery migrations commands now have a `--database` option to choose the desired global connection and new Traits (#826) now includes not only `useTransactions`, but also `testDatabase` to use the in memory database and `refreshDatabase` to use a clean, migrated, database.
