### ISSUE TITLE
Update PHPUnit dependency when PHP 5.x finally dies

### ISSUE THREAD

**Issue by alexweissman** [userfrosting/UserFrosting#779]
Starting in PHPUnit 6.3, there are some [useful features](https://github.com/sebastianbergmann/phpunit/issues/2353) that would help our testing framework quite a bit.  Unfortunately PHPUnit 6.3 requires PHP 7.

I'd like for UF to continue supporting PHP 5.6 [until it is out of security support](http://php.net/supported-versions.php), so we can't bump our version of PHPUnit yet 😕 .

**Comment by lcharette** [comment]
Related : [Roadmap for 4.3](https://github.com/userfrosting/UserFrosting/wiki/Roadmap-for-UserFrosting-4.3#require-at-least-php-71)

**Comment by Silic0nS0ldier** [comment]
Guess what's now out of support. 🍾 🎆
