### ISSUE TITLE
Parse error in vendor/illuminate/support/helpers.php on line 510

### ISSUE THREAD

**Issue by saliakhtar** [userfrosting/UserFrosting#781]
Hi,

I am getting below parse error when opening http://myuserfrosting/index.php:

Parse error: syntax error, unexpected '.', expecting '&' or variable (T_VARIABLE) in ../userfrosting/app/vendor/illuminate/support/helpers.php on line 510

The error is getting thrown from line 510:     function dd(...$args), from the below function:

if (! function_exists('dd')) {
    /**
     * Dump the passed variables and end the script.
     *
     * @param  mixed
     * @return void
     */
    function dd(...$args)
    {
        foreach ($args as $x) {
            (new Dumper)->dump($x);
        }

        die(1);
    }
}

**Comment by saliakhtar** [comment]
Looks liked a php issue. Able to resolve it. closing this issue...

**Comment by alexweissman** [comment]
Usually this is due to not meeting the minimum required version of PHP (5.6).
