### ISSUE TITLE
Activities with empty user infomation

### ISSUE THREAD

**Issue by splitt3r** [userfrosting/UserFrosting#782]
After deleting a user the activities page / widget still shows the users activities but without the user information:

![Activities](https://user-images.githubusercontent.com/1869584/29242429-6c357ed0-7f8d-11e7-8523-88a1a96e5226.png)

Something like 'User deleted' instead of the username would be a good solution.

**Comment by alexweissman** [comment]
Fixed as of v4.1.9.
