### ISSUE TITLE
ExceptionHandler should generate appropriate content type for generic responses

### ISSUE THREAD

**Issue by alexweissman** [userfrosting/UserFrosting#783]
I'm still not 100% satisfied with our exception-handling system.  Right now, the first thing that `ExceptionHandler::handle` does is to check if error debugging is currently enabled:

```
        if ($this->displayErrorDetails) {
            $response = $this->renderDebugResponse();
        } else {
            // Write exception to log
            $this->writeToErrorLog();

            // Render generic error page
            $response = $this->renderGenericResponse();
        }
```

`renderDebugResponse` invokes the appropriate `Renderer` class to generate a debugging message based on the requested content type.  Oddly, some `Renderer` classes check the value of `displayErrorDetails` again in their logic, even though we've already done this check in `handle`.  Seems weird.

Also, `renderGenericResponse` doesn't do any checking of the requested content type at all!  It appears to always generate content for an HTML response, even if some other type was requested.
One thing we could do is change the `ErrorRenderer` interface so that it has `renderGeneric` and `renderDebug` methods, and call the appropriate method from within the exception handler.  Alternatively, we could replicate some functionality in `ExceptionHandler::renderGenericResponse` to check the content type and generate the appropriate type of response.

**Comment by alexweissman** [comment]
Still an issue.

**Comment by lcharette** [comment]
The `renderGenericResponse` is a real issue, as a json request will return an HTML response when `displayErrorDetails` is false instead of a valid json one.

**Comment by lcharette** [comment]
Ref : https://github.com/userfrosting/sprinkle-core/commit/e6cc26229fcdb36a809ff30a5c7dc66fc8f65ad5

**Comment by lcharette** [comment]
Error handling has been completely rewritten for UF5. A new issue should be open for further issue related to this
