### ISSUE TITLE
Implement MethodNotAllowedHandler

### ISSUE THREAD

**Issue by alexweissman** [userfrosting/UserFrosting#784]
Right now we rely on Slim's default `NotAllowed` handler for dealing with `MethodNotAllowedException` ([405 errors](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/405)).  This sucks because it is stylistically inconsistent and diverges from our generic/debug exception handling system.

We should do a passthrough in Slim's `notAllowedHandler`, just like we have now done with `phpErrorHandler` and `notFoundHandler`, to throw our own `MethodNotAllowedException` and process it with one of our exception handlers (`HttpExceptionHandler` or a subtype).

However since the [default handler](https://github.com/slimphp/Slim/blob/3.x/Slim/Handlers/NotAllowed.php#L36-L59) can already return multiple different content types, I recommend we resolve #783 first, before attempting to resolve this issue.

**Comment by alexweissman** [comment]
Still an issue

**Comment by lcharette** [comment]
FYI, as of https://github.com/userfrosting/sprinkle-core/commit/5c6f47cb5db67a6d0972815e86dd853d9e3fc1a4, `MethodNotAllowedException` is properly handled by UF Error Handler in V5.
