### ISSUE TITLE
Support multiple ServicesProvider classes in a Sprinkle

### ISSUE THREAD

**Issue by alexweissman** [userfrosting/UserFrosting#786]
Would make it easier to organize services when there are a lot of them (which could happen, given the way we're starting to [rely on services as a primary extension mechanism](https://github.com/userfrosting/UserFrosting/issues/680#issuecomment-323597109).

This may depend on resolving #743, first.

**Comment by Silic0nS0ldier** [comment]
As long as doesn't mean multiple services providers accessible from controller methods (e.g. `$this->ci1`, `$this->ci2`), it does sound like a good way to handle scenarios like the referenced.

**Comment by alexweissman** [comment]
Yes, they would all register on the same dependency container.

**Comment by lcharette** [comment]
While `serviceProvider` is automatically registered, a sprinkle class can manually register it's own provider. So I guess this can already be done (manually).
