### ISSUE TITLE
Detach Migrator from the CLI 

### ISSUE THREAD

**Issue by lcharette** [userfrosting/UserFrosting#795]
[Migrator](https://github.com/userfrosting/UserFrosting/blob/master/app/system/Bakery/Migrator.php#L442) shouldn't be tied to so much to the CLI and `migrate` command. Right now, there's no standard way to test, outside of the migrate command, if a migration has been run. For example : https://github.com/userfrosting/UserFrosting/blob/9bad0431ffc9d7538fdaeafa6926d4ee3aadb992/app/sprinkles/account/src/Bakery/CreateAdminUser.php#L68-L79

Should also help with #778.

# Progress
- [x] Make migrator it's own class, detached from Bakery
- [x] Move Migrator to the core sprinkle
- [x] Add tests
- [x] Add `--database` option for Bakery command
- [x] Add status Bakery command
- [x] Run tests against the SQLite in memory db
- [x] Update helper traits (related #826)
- [x] Find a way to integrate data seeders (See #778)
- [x] [Add batch number to status command](https://github.com/laravel/framework/pull/21391)

**Comment by lcharette** [comment]
Some notes and references for later:

- [Laravel Migration](https://github.com/laravel/framework/blob/master/src/Illuminate/Database/Migrations/Migrator.php). [This part](https://github.com/laravel/framework/blob/master/src/Illuminate/Database/Migrations/Migrator.php#L415) is important. Laravel migration doesn't have namespaces. This would actually avoid issues people had on the chat. Will also makes the migration names less dependent of [our stupid convention](https://github.com/userfrosting/UserFrosting/issues/743) (#743).

- [Migration test](https://github.com/laravel/framework/blob/master/tests/Database/DatabaseMigrationMigrateCommandTest.php). Because we need those (and I need to learn what Mockery is).

- [Laravel migration commands](https://github.com/laravel/framework/tree/master/src/Illuminate/Database/Console/Migrations). Because that `status` command could be useful.

- The `database` option would also be useful.

**Comment by alexweissman** [comment]
![](http://25.media.tumblr.com/tumblr_m6gqx1ZSyo1r2qbw5o1_500.gif)

**Comment by lcharette** [comment]
Most work has been done in the [`feature-migrator`](https://github.com/userfrosting/UserFrosting/tree/feature-migrator) branch regarding this issue. 

One thing that could left to do, beside updating learn, would be to re-implement the `sprinkle` option for the `migrate:rollback` command (and probably `reset` and `refresh` too). First, that option for the base `migrate` command doesn't make sense. Why would you want to migrate up a sprinkle, but not the other? But for rolling back, it does makes sense if you want to delete a previously loaded sprinkle you don't want anymore. So yeah, stil looking into this.

(Sprinkle support for migration is the reason the migrator wasn't moved to a separate package btw)

Some other notes in case I forgot : 
We can't go away from using namespaces with our migrations. As pointed in my previous comment, Laravel doesn't use them (and doesn't have to deal with namespace issue) because they store all their migration in a single path OR migrate a single path at the time. This is something we can't do with sprinkles, as two sprinkles can have dependent migrations between each other and two sprinkles can have the same class names for their migrations. This is still taken care of more accurately in the new migrator since we don't enforce the `version` part of the migration anymore (can be in the top level).

Last of all, this update should be (squashed) merge into `4.2.0` version. There no big breaking change, but some stuff got deprecated. So, just in case...

For a list of other fix in this branch : [Changelog](https://github.com/userfrosting/UserFrosting/blob/feature-migrator/CHANGELOG.md#unreleased)


And yes, I did learn how Mockery works. It's great.

**Comment by lcharette** [comment]
[This is a good idea...](https://github.com/laravel/framework/pull/21391)
