### ISSUE TITLE
Testing environment should set PHP exit code on exceptions

### ISSUE THREAD

**Issue by alexweissman** [userfrosting/UserFrosting#796]
Right now, even in the testing environment we get a `0` [exit code](http://php.net/manual/en/function.exit.php) (success) when an exception is thrown.  For example when `sprinkles.json` is not found, we throw an exception. 

This is probably because we're catching all exceptions to generate HTTP response codes.  So, we need a way to tell Travis that this is actually a failure, by generating an appropriate exit code.

**Comment by Silic0nS0ldier** [comment]
Found a way to do this. Don't know if a 'good' solution, or if it'll cover for all the handlers, but its 'a' solution.

1. Add
    ```php
    $this->ci['errorTriggered'] = function($c) { return true; };
    ```
    to `renderDebugResponse` and `renderGenericResponse` functions in `UserFrosting\Sprinkle\Core\Error\Handler\ExceptionHandler`.

2. Add
    ```php
    if ($this->ci->has('errorTriggered')) { exit(1); }
    ````
    to end of `run` function in `UserFrosting\System\UserFrosting`.

Exceptions (seem) to render as expected in the browser, and the php exits with an error code.

**Comment by alexweissman** [comment]
I believe this is the Travis job log that prompted this issue: https://travis-ci.org/userfrosting/UserFrosting/builds/282078428

**Comment by lcharette** [comment]
I don’t think this is still valid. If an issue occurs again with Travis we can investigate.
