### ISSUE TITLE
Load different sprinkle for each domain

### ISSUE THREAD

**Issue by mgpro94** [userfrosting/UserFrosting#806]
Hello,

i have many domains that access the UserFrosting,
every domain is a different site but with the same management..

can i load a different sprinkle for each domain separately?

Thank you in advance for helpers :)

**Comment by alexweissman** [comment]
This is more of a usage question, so it would probably be best asked on the [forums](https://forums.userfrosting.com) or [chat](https://chat.userfrosting.com).
