### ISSUE TITLE
How to get CSRF token from Phonegap app?

### ISSUE THREAD

**Issue by sergio11** [userfrosting/UserFrosting#807]
Hi, Thanks for the framework.

I wanted to develop a Sprinkles to manage products. There will be paths to display screens from the web browser protected with "authGuard", but there will be other routes to get results in JSON format to be presented in my Phonegap application.

I think CSRF protection is important for all of these routes. But the problem is that I do not know how I can get the current CSRF token that generated the Middleware.

That token is available for JS scripts through a global variable in config.js. But for this case how could you get that value?

Thanks in advance.

**Comment by alexweissman** [comment]
This is more of a usage question, so it would probably be best asked on the [forums](https://forums.userfrosting.com) or [chat](https://chat.userfrosting.com).

Also, have you read the docs on [CSRF](https://learn.userfrosting.com/routes-and-controllers/client-input/csrf-guard)?
