### ISSUE TITLE
Variable Undefined in Strict Mode issue when logging in in IE11

### ISSUE THREAD

**Issue by delicado54** [userfrosting/UserFrosting#809]
This appears to be an issue in uf-alerts.js on line 203 (`alert = this.alerts[i];`).

I thought this might be my own implementation somehow but I see the same issue occurs on the demo site.   This error occurs intermittently when a user is logging in or registering in IE11 (and I'm guessing IE10). When it occurs, it prevents the form from submitting.  

I wonder if this might be related to a similar intermittent issue I've experienced in Chrome where the following console error appears but disappears on refresh:

   jquery-2.2.4.min.js:2 Uncaught TypeError: Cannot read property 'length' of null
    at Function.merge (jquery-2.2.4.min.js:2)
    at Plugin._fetchSuccess (uf-alerts.js:119)
    at Object.f (jquery-2.2.4.min.js:2)
    at i (jquery-2.2.4.min.js:2)
    at Object.fireWith [as resolveWith] (jquery-2.2.4.min.js:2)
    at z (jquery-2.2.4.min.js:4)
    at XMLHttpRequest.<anonymous> (jquery-2.2.4.min.js:4)

Overall I have found UF to be amazing and these are the only issues I've encountered.

**Comment by Silic0nS0ldier** [comment]
True to the error, I missed a `var` declaration (7 months ago). Would have caught onto this earlier if the newer browsers actually followed the spec regarding `'use strict';` scoping.
