### ISSUE TITLE
Callable UserFrosting\Sprinkle\Site\Controller\PageController does not exist

### ISSUE THREAD

**Issue by centauromax** [userfrosting/UserFrosting#812]
Hi, I installed UserFrosting a few days ago and tried to create a new page, but it didn't work because UserFrosting did not find the class. I tried to follow the documentation, creating the "Site" sprinkle and the "members" page and gave the same error:
```
RuntimeException
Callable UserFrosting\Sprinkle\Site\Controller\PageController does not exist
```

I checked the various steps several times, to exclude permission problems I put 777 to all the files and directories, everything seems correct, but I still have the same error. 

Composers and routes seem to be correct: 
```
./routes/routes.php
$app->get('/members', 'UserFrosting\Sprinkle\Site\Controller\PageController:pageMembers');

./composer.json
    "description": "Site sprinkle for owlfancy.com.",
            "UserFrosting\\Sprinkle\\Site\\": "src/"

./vendor/composer/autoload_psr4.php
    'UserFrosting\\Sprinkle\\Site\\' => array($baseDir . '/src'),

```

I Googled for a solution but I haven't found anything. What else do I have to check?
I have Linux AWS and Nginx.

**Comment by alexweissman** [comment]
This is a usage question, so it is best asked in [chat](https://chat.userfrosting.com), or on our [forums](https://forums.userfrosting.com).  See you there!
