### ISSUE TITLE
Updating bootstrap to version 4.x

### ISSUE THREAD

**Issue by blacksector** [userfrosting/UserFrosting#818]
I recently started using UF and although the documentation is amazing and very clear with most topics, I am very confused on how to update or add new assets. I realized that UF seems to use Bower for installation of assets but running the bower command "doesn't work" as in the assets downloaded are not installed in the `core/assets/vendor` folder. Anyway, maybe I am messing it up by I finally decided to just download bootstrap in my custom `site` sprinkle and when I added the asset-bundles.json file to my sprinkle like so, it messes up the entire site theme:
```
{
    "bundle": {
        "js/main": {
            "scripts": [
                "dist/js/bootstrap.min.js"
            ],
            "options": {
                "result": {
                    "type": {
                        "scripts": "plain"
                    }
                },
                "sprinkle": {
                  "onCollision": "replace"
                }
            }
        },
        "css/main": {
            "styles" : [
                "dist/css/bootstrap.min.css"
            ],
            "options": {
                "result": {
                    "type": {
                        "styles": "plain"
                    }
                },
                "sprinkle": {
                    "onCollision": "replace"
                }
            }
        }
    }
}

```
even the login page is no longer functioning. I get errors like `$(...).ufForm is not a function` in Google Chrome's console and trying to submit the form gives me "Method not allowed"

**Comment by blacksector** [comment]
Note, I apologize but I fixed a lot of it by changing "replace" to "merge" and in the base template changing query slim to the full version of query. Unfortunately, a lot of the functions on the site still don't work. The user database isn't loaded and I get errors like:
```
Cannot read property 'config' of undefined
    at new Plugin (http://localhost/userfrosting/public/assets-raw/core/assets/userfrosting/js/uf-table.js:269:34)
```

**Comment by lcharette** [comment]
You’ll need to copy all of the `main/js` bundle in there. The way you did it, you replaced all the files in that bundle with only bootstrap... I’m not sure what merge/replaces does, but it might help. 

Note we haven’t tested bootstrap 4 compatibility yet I think, so might be unstable. But if you get it to work, it would makes a great contribution ;)

**Comment by blacksector** [comment]
@lcharette Thanks for the response! I will give that a go, but after reading the documentation I got: `The second definition would completely replace the css/main bundle.` from [https://learn.userfrosting.com/asset-management/asset-bundles](asset-bundles) and it seems that if I had `replace` it removed all of the css or javascript bundle... So changing it to `merge` fixed it.

I would love to push a bootstrap 4 change! But unfortunately, I still can't figure out how to get bower working and updating the packages...? Any tips on how to do that or should I manually modify the bower.json file?

**Comment by lcharette** [comment]
Ok so `merge` is definitively what you want (I should use that more often...)

Does another bundle defines Bootstrap? Or maybe another dependency in the stack requires it and there's a version conflict ?

You can also join us on the [chat ](https://chat.userfrosting.com) to debug this. Since BS4 is coming quickly, this should probably be fixed and even updated as standard (or provide an option to use it) in future version of UF so we can keep up to date.

**Comment by Silic0nS0ldier** [comment]
Yeah, bower is manually invoked in a gulp script. (`npm run uf-assets-install`, of something like that is used from the `build` folder) And as you've discovered, lots of breaking changes in BS4. Once https://github.com/userfrosting/UserFrosting/projects/7 is done, it should be easier to pick up on these kinds of breaking changes.

**Comment by lcharette** [comment]
Since Bootstrap is included with [AdminLTE](https://github.com/almasaeed2010/AdminLTE), UF default theme, UF won't be officially including BS4 until AdminLTE 3 is release and updated in UF. It is something however we can look at in #597.  

Anyone having trouble including BS4 in his sprinkle should ask on the [chat](https://chat.userfrosting.com) or open a new issue if something is really broken.
