### ISSUE TITLE
HTTPS problems

### ISSUE THREAD

**Issue by trilleplay** [userfrosting/UserFrosting#823]
Hello there UF community!
This is my first error post here so sorry if i make a mistake!

Browser: Firefox and Chrome.
Web Server: Apache2
PHP Version: 7.0.24
Hosting Provider: one.com

The issue: When i tried to access UF using HTTPS, the site wouldn't fully load (I've tested using both Firefox and Chrome.) And i get errors thrown at me, so i opened up console and saw that resources was trying to be grabbed from https://trilleplay.net:80/brokengroundoneaccount/

Additional: I Asked around in the userfrosting chat and apparently this happens to Apache2 Servers. 

Thanks, Trilleplay

**Comment by splitt3r** [comment]
It´s https://trilleplay.net/brokengroundoneaccount/ SSL / TLS is port 443 not 80 but you don´t need to enter it anyway.

**Comment by lcharette** [comment]
Wasn’t this solved on the chat? Either way, it’s clearly an Apache configuration issue. I would bet for a hardcoded port somewhere in the config where it doesn’t belong. 

If this is still an issue, comes see us again on the chat.

**Comment by trilleplay** [comment]
I managed to fix it, by editing the config, just if anyone encounters the same problem

**Comment by alexweissman** [comment]
@trilleplay want to do a quick write-up, and we can post it on https://learn.userfrosting.com/troubleshooting/common-problems ?

**Comment by trilleplay** [comment]
@alexweissman Yeah sure.

**Comment by alexweissman** [comment]
Cool, just submit a PR!  Or, join us in chat if you need help 😄
