### ISSUE TITLE
Move test Trait to their respective sprinkle

### ISSUE THREAD

**Issue by lcharette** [userfrosting/UserFrosting#826]
Along with the new migrator (#795), migration related Classes and Bakery command where moved to the `core` sprinkle. This makes more sense as the database setup is done there.

Now [Test Traits](https://github.com/userfrosting/UserFrosting/tree/feature-migrator/app/tests) should also be moved to the core Sprinkle. Problem is, to be applied, they need to be registered in the main [TestCase](https://github.com/userfrosting/UserFrosting/blob/feature-migrator/app/tests/TestCase.php#L85-L95) in `app/system`.

Any idea how a Trait (or something else) [can be added to a Test](https://github.com/userfrosting/UserFrosting/blob/feature-migrator/app/sprinkles/account/tests/Unit/FactoriesTest.php#L20-L21) while residing in any given sprinkle? Does it make sense (while less pretty and prone to error) to call the Test Trait function manually by extending the `setUp` method?

**Comment by alexweissman** [comment]
Why not just register them as needed in the individual test cases in each Sprinkle?  If there is a lot of additional setup code required, then you could extend the base `app/system/TestCase` in the core Sprinkle, e.g. `class DatabaseTestCase extends TestCase`.

**Comment by lcharette** [comment]
Moving the test case to `core` would introduce a Breaking change. Plus other sprinkle won't be able to add their own stuff... I guess manually calling the function in `setUp` might be the best option. Less pretty than Laravel implementation, but would work.

Other solution would be to standardize test Trait location, ie dynamically load all of the Traits located in `app/sprinkles/*/test/Traits/` instead of [hard coding them](https://github.com/userfrosting/UserFrosting/blob/feature-migrator/app/tests/TestCase.php#L85-L95) ?

**Comment by lcharette** [comment]
Actually, dynamically loading Trait woudn't work either. Since they are traits, they can't share a common initialization method. 

So either you use the ` withTestDatabase` trait then add `$this->withTestDatabase()` in your `setUp` or we switch those Traits to something else entirely, for example a (static) class that can be initialized.
