### ISSUE TITLE
Blacklist common passwords

### ISSUE THREAD

**Issue by alexweissman** [userfrosting/UserFrosting#832]
Together with minimum length, [blacklisting common passwords](https://github.com/danielmiessler/SecLists/tree/master/Passwords) is the most effective known password policy.

Not sure how many we should blacklist by default.

Probably, we should also enforce an entropy requirement and blacklist `password = username` and `password = email`.  See https://blog.codinghorror.com/password-rules-are-bullshit/

**Comment by Silic0nS0ldier** [comment]
Probably (definitely?) overkill, but https://haveibeenpwned.com/Passwords has a known exposed passwords list. All encoded in SHA1 (cause there are people out there that have passwords that identify them 🤦‍♂️). Pity it has no frequency with them.

**Comment by splitt3r** [comment]
@Silic0nS0ldier awesome idea. https://github.com/nextcloud/password_policy/pull/60 This is a good examplte / an easy way of getting started.

**Comment by Silic0nS0ldier** [comment]
Since you've reminded me, there is a password manager that has since integrated with the service. And based on Troy Hunt's blog posts, the API endpoints are highly optimised (most requests don't get past the CDN which Cloudflare footed the bill of) so any potential bandwidth theft implications are essentially eliminated.

Hmm... What would be the best place to perform the check? Server-side or client-side?

**Comment by lcharette** [comment]
If you rely on a 3rd party API, we should consider caching the info on our side using the cache service. Then it's either a question or doing the check in either form validation (client or server side).

**Comment by Silic0nS0ldier** [comment]
Update regarding the API: only anonymous requests will be accepted in the future.

The anonymous API works by giving the first few characters of the hash, and receiving hashes that match in return (minus the characters that were sent originally).

**Comment by Silic0nS0ldier** [comment]
On the topic of caching, we'd need some system to keep the size to a reasonable amount. We could also limit caching to common results, since each hashed password is paired with a number indicating the number of items its appeared. I'm sure one of Troy's blogs has a graph we can use to get an idea of what a good number would be.

**Comment by Silic0nS0ldier** [comment]
Some things to consider are mentioned here https://twitter.com/alexjamesbrown/status/1063552695133487104

**Comment by amosfolz** [comment]
> 
> 
> Probably (definitely?) overkill, but https://haveibeenpwned.com/Passwords has a known exposed passwords list. All encoded in SHA1 (cause there are people out there that have passwords that identify them 🤦‍♂️). Pity it has no frequency with them.

I have been playing around with this idea to see what I can come up with. I am having a hard time trying to determine if it would really be worth using this with the cache service or not? Would the purpose of that just be for server-side validation?

**Comment by Silic0nS0ldier** [comment]
Cache service would be to minimise the total amount of bandwidth consumed (have to consider HIBP and the site making the request if server side) and cut out an extra request where we can.

As for if it should be server side or client side enforced... Sounds like something that should be configurable. Personally a requirement is my preference. Also worth considering if we want to do the check at login, to keep accounts having a secure password.

**Comment by amosfolz** [comment]
Would the best place to store configuration options for something like this be inside the `site` variable? Options could be added under something like `site.password_security`

**Comment by lcharette** [comment]
Depends if you want to store the base config (on /off switch) or the whole list in that config. If the list is long, or dynamically loaded, it might not be the best place. The `site` config is pushed into every request. Putting too much in the site config could add unnecessary overhead. 

I think for this kind of feature, server-side only check could be enough. 

We need to be careful with the HIBP list. More then 7 GB of data 😱

**Comment by amosfolz** [comment]
> 
> 
> Depends if you want to store the base config (on /off switch) or the whole list in that config. If the list is long, or dynamically loaded, it might not be the best place. The `site` config is pushed into every request. Putting too much in the site config could add unnecessary overhead.
> 
> I think for this kind of feature, server-side only check could be enough.
> 
> We need to be careful with the HIBP list. More then 7 GB of data 😱

Yes I think just the base config would be stored there. Just as an example I have this so far: 
```
  'password_security' => [
                'enforce_no_compromised'   => '5', // Set to false to turn off this feature. Otherwise, provide a numeric string, which sets the maximum number
                                                   // of times that is "acceptable" for a password to have appeared in breaches. The recommended and most secure
                                                   // option is '0' - meaning only passwords that are not on the list of compromised passwords will be allowed.
                                                   //
                'enforce_update_passwords' => true // Settings this to true will check user's passwords against list of known compromised passwords at each log on.
            ]
```

A short refresher on how the HIBP API works: It uses a k-anonymity model. So, you send the first 5 characters of SHA1 hash of password, and get back a list of hash suffix. Then you compare the long list of hash suffix with your actual password hash suffix. Their website states the smallest result is 381, the largest 584.

**Comment by lcharette** [comment]
Oh, so you don't have to fetch the whole list... makes sense...

**Comment by obendev** [comment]
I can recommend the Nextcloud example. As being said they also use haveibeenpwned

**Comment by Silic0nS0ldier** [comment]
I just noticed that the PR related to this doesn't appear to be linked here. https://github.com/userfrosting/UserFrosting/pull/974

**Comment by Silic0nS0ldier** [comment]
To harken back to what Alex mentioned initially, we probably still want to keep https://blog.codinghorror.com/password-rules-are-bullshit/ in mind as I'm sure there are lessons to be learned and applied from that article.

**Comment by amosfolz** [comment]
> To harken back to what Alex mentioned initially, we probably still want to keep https://blog.codinghorror.com/password-rules-are-bullshit/ in mind as I'm sure there are lessons to be learned and applied from that article.

As mentioned in 5. of the article, I think there would be benefit from also restricting use of these two:
```
    password equal to username
    password equal to email address
```

And possibly these two:
```
    password equal to URL or domain of website
    password equal to app name
```

**Comment by lcharette** [comment]
Open to suggestion, but I think it would be a good community sprinkle instead. Not priority for now IMO.
