### ISSUE TITLE
getInfo method is missing in GroupController

### ISSUE THREAD

**Issue by Stijnbak** [userfrosting/UserFrosting#837]
I noticed the following route while trying to recreate the group edit modal:

`$this->get('/g/{slug}', 'UserFrosting\Sprinkle\Admin\Controller\GroupController:getInfo');`

But the method getInfo does not exist in the GroupController.php class.

**Comment by alexweissman** [comment]
It would seem that `RoleController::getInfo` is also missing.

**Comment by alexweissman** [comment]
Not sure why this is still open, as it has been fixed as of 4.1.17.
