### ISSUE TITLE
What are your thoughts on Reactive Programming?

### ISSUE THREAD

**Issue by iohannis** [userfrosting/UserFrosting#842]
I saw a bridge between the Slim Framework and ReactPHP, and got a bit curious on your take on using ReactPHP with UserFrosting, and Reactive Programming in general?

https://github.com/NigelGreenway/reactive-slim

I've only just begun to explore Reactive Programming - do you have experience with it? Would it be worth implementing - and why (not)?

**Comment by Silic0nS0ldier** [comment]
I doubt it could be reliably implemented in UF right now, at least in a meaningful way. Its definitely something worth considering for the next major release though.

Not sure if it uses `pthreads` underneath though, so I wonder how it actually achieves non-blocking code.
