### ISSUE TITLE
ACCOUNT.REGISTRATION_BROKEN

### ISSUE THREAD

**Issue by jy2008** [userfrosting/UserFrosting#843]
all of sudden, my website registration doesn't work, when i register it gave me `ACCOUNT.REGISTRATION_BROKEN`, why? i cannot tell from console, it just say 500 error

**Comment by jy2008** [comment]
sorry, i still don't know where i should go to fix it. I don't think i changed anything on default group.

**Comment by lcharette** [comment]
This errors means [`Account registration is not working because the default group '{{GROUP_NAME}}' does not exist`](https://github.com/userfrosting/UserFrosting/blob/master/app/sprinkles/account/src/Controller/AccountController.php#L799-L800). @jy2008 Did you delete the [default group](https://github.com/userfrosting/UserFrosting/blob/master/app/sprinkles/account/config/default.php#L59) ? 

Actually, this errors brings something in mind. Should this be an error at all? Shouldn't it fallback to "no group" if the default group doesn't exist?

**Comment by jy2008** [comment]
i didn't del default group at all.
This error incurred after my email server went down due to late payment. But afterwards the email server went back and i didn't change the email password.

**Comment by Silic0nS0ldier** [comment]
Anything in the error logs? Its a 500 response so in theory there should be something in there.

**Comment by jy2008** [comment]
OK, so i checked database, under `group` table, there is nothing. There should be something right? How do i add it back? by `bake`? 
I saw in nignx error log this error:
```
2018/01/29 02:34:28 [error] 1544#1544: *82187 FastCGI sent in stderr: "Unable to                                                                                         open primary script: /var/www/usor/public/database/sql.php (No such file or dir                                                                                        ectory)" while reading response header from upstream, client: 149.202.92.198, se                                                                                        rver: usorgames.net, request: "GET /database/sql.php HTTP/1.1", upstream: "fastc                                                                                        gi://unix:/run/php/php7.0-fpm.sock:", host: "backup.shopgreddy.com"	
```

**Comment by lcharette** [comment]
Groups can be created in the admin UI :unamused:

**Comment by alexweissman** [comment]
Ok let's fix the error message for now, and then we will remove the requirement for `group_id` in 4.2.

**Comment by jy2008** [comment]
ok, so i added a group terran, now the user can register but only with email not user name.
Also all my user's default landing page changed, I changed it in the code to non-dashboard page, now it went back to dashboard page. Has this have anything to do with adding the new group?

**Comment by lcharette** [comment]
Since the missing locale key is fixed in master, I'll close this issue. Further work on the null group thing should go in #867.
