### ISSUE TITLE
Automatic timezone conversion

### ISSUE THREAD

**Issue by Silic0nS0ldier** [userfrosting/UserFrosting#847]
Dealing with timezone conversion is always a pain. Client timezone is unknown on the backend, and writing scripts to convert for the frontend is easy to mess up. A standardised out-of-box solution would be fantastic.

**Comment by lcharette** [comment]
Question is, should the backend or the frontend be in charge of setting the timezone for the other one?

It could be set as a per user in their profile, but it's not great UX if the user physically travel to a new timezone...

**Comment by alexweissman** [comment]
There's gotta be a third-party library for this somewhere.

**Comment by Silic0nS0ldier** [comment]
@Malou Hence the "needs discussion" and "long-range planning" labels.

Issue with backend is that you don't necessarily know the users timezone since it isn't sent with the request. Which is annoying cause if its done on the backend automatically, its a lot less tedious since there isn't some script you need to remember to apply. Hmm. Would have to remember to convert back to data source timezone on save too.

@alexweissman I'm sure there is. Just not too sure how well it would go with abstracting all the work away. Ideal scenario would be all stuff directly integrated (plus official addons) don't require any manual conversions at all. Libraries can probably help (unless what we already have can be put to work).

Depending on scope, this could be a feature of a 4.X release behind a config switch (for backwards compatibility), or a part of the mythical UF5.

**Comment by Silic0nS0ldier** [comment]
On the note of scope, its probably worth doing an audit to figure out where time is written and read in UF.

**Comment by lcharette** [comment]
This should probably be figured out along the localized date PIA, especially if we’re looking at date input and new external library.
