### ISSUE TITLE
sync() on a belongsToMany() does not set created_at, updated_at

### ISSUE THREAD

**Issue by ascl-charlie** [userfrosting/UserFrosting#849]
The `sync()` function, when used on a `belongsToMany()` relationship, does not appear to set the `created_at` or `updated_at` timestamp fields.

**Comment by lcharette** [comment]
This is more of an [Eloquent related question](https://stackoverflow.com/a/26062812/445757)? 

Or do we actually fail to update the timestamps somewhere in our code ?
