### ISSUE TITLE
authGuard makes no distinction between expired login and new user

### ISSUE THREAD

**Issue by Silic0nS0ldier** [userfrosting/UserFrosting#851]
Discovered a bit of a semantics issue with authGuard. As it currently is, the alert generated only makes sense to someone who's login session has expired. This simply makes no sense to a new user whom has navigated to a protected page.

**Comment by Silic0nS0ldier** [comment]
Easiest way I can see for handling this, is that whatever function cleans up the expired session sets a server side user session variable (on the new session) to indicate the current session was spawned by an expired login. This flag would get cleared AFTER middleware has had a chance to execute. Then within `authGuard` we can check for this flag, and throw the appropriate exception (like `AuthRequiredException` when appropriate).

**Comment by linkhousemedia** [comment]
@Silic0nS0ldier Jordan, have you tried to implement your suggestion? Wondering if this is on the radar for a fix at all.

**Comment by Silic0nS0ldier** [comment]
Not yet. Currently busy on other projects. It is on the radar though. Just no time frame presently.

**Comment by lcharette** [comment]
I have a feeling this could be solved by putting a cap on the delta of when the session/cookie was last used vs the current time 🤔.

```
* Session was last touched 5 days ago => Don't show
* Session was last touched 1 hour ago => Do show
```

**Comment by lcharette** [comment]
Hey, this has finally been fixed in UF5!
