### ISSUE TITLE
Use Repository for dealing with raw input in bundle loader

### ISSUE THREAD

**Issue by Silic0nS0ldier** [userfrosting/UserFrosting#860]
https://github.com/userfrosting/UserFrosting/blob/fc6d78bf8a33d48ec4cc8981ad5290a31dc53a3d/app/sprinkles/core/src/Util/RawAssetBundles.php#L45 triggers `PHP Notice:  Trying to get property of non-object in /Users/alexw/dev/htdocs/btoms/app/sprinkles/core/src/Util/RawAssetBundles.php on line 45`.

This is basically a null pointer exception. Its worth adopting Repository here, as it'll make things a lot easier to process (less guarded checking).

**Comment by alexweissman** [comment]
Repository will let you use the dot notation for accessing nested key-value pairs (e.g. `$bundle->options['sprinkle.onCollision']`).

**Comment by Silic0nS0ldier** [comment]
Fix for this is now in `develop`. Should land in `4.2-beta.2` or `4.2`.
