### ISSUE TITLE
Allow null group assignment for users

### ISSUE THREAD

**Issue by lcharette** [userfrosting/UserFrosting#867]
This will probably require a db migration to allow nullable value. The UI need to be allow for a "no group" option.

(Ref #843)

**Comment by amosfolz** [comment]
Since this will require another DB migration I thought it might be good to include it in the same release as https://github.com/userfrosting/UserFrosting/pull/957 since that will require one as well. If there are no problems I will start working on it.

**Comment by amosfolz** [comment]
I am running into some problems trying to figure out the best way to handle this. I am running into foreign key constraints from the relationships added here https://github.com/userfrosting/UserFrosting/blob/master/app/sprinkles/account/src/Database/Migrations/v420/AddingForeignKeys.php#L44

Even if we make the `users.group_id` column nullable, we will not be able to save a value unless it also exists in the `groups.id` 
![image](https://user-images.githubusercontent.com/33728190/55841033-9c795800-5afb-11e9-9ee1-bf6d1a6b0b2d.png)

**Comment by lcharette** [comment]
That's because the `group_id` is `0` while it should be `null`.

See : https://stackoverflow.com/a/15082906/445757

**Comment by amosfolz** [comment]
> 
> 
> That's because the `group_id` is `0` while it should be `null`.
> 
> See : https://stackoverflow.com/a/15082906/445757

Can we use `value="0"` on the form, then in the controller do a check? Something like this right before the update is made:
 ```
        if ($data['group_id'] == 0) {
            $data['group_id'] = null;
        }
```
Otherwise validation fails if `group_id` is not a integer.

**Comment by amosfolz** [comment]
Was addressed in https://github.com/userfrosting/UserFrosting/pull/964.
