### ISSUE TITLE
Update to FontAwesome 5

### ISSUE THREAD

**Issue by lcharette** [userfrosting/UserFrosting#870]

**Comment by haywirephoenix** [comment]
Download FA5, rename/delete and replace "userfrosting\app\sprinkles\core\assets\vendor\fontawesome" 

Change
`"vendor/fontawesome/css/font-awesome.css"`
`
"vendor/fontawesome/css/fontawesome.css",
                "vendor/fontawesome/css/all.css" `

in "userfrosting\app\sprinkles\core\asset-bundles.json"

done :)

**Comment by lcharette** [comment]
Didn’t FA also changed icon names and prefix in 5?

**Comment by lcharette** [comment]
> Download FA5, rename/delete and replace `"userfrosting\app\sprinkles\core\assets\vendor\fontawesome"`

Actually, for a permanent fix, it should be changed in the [bower](https://github.com/userfrosting/UserFrosting/blob/master/app/sprinkles/core/bower.json#L16) file.

We also need to provide support if someone wants to use the pro version (which I don't know how it works).

**Comment by haywirephoenix** [comment]
The additional CSS files are supposed to add backwards compatibility.

Also note that they have removed the hyphen in font-awesome file and folder names

**Comment by amosfolz** [comment]
I have been working on upgrading to FA 5 [here](https://github.com/amosfolz/UserFrosting/tree/fa5).

FA5 removed all aliases. As long as people are aware about the change it should not be a difficult transition. Probably easiest for people to just do the update and then go through their site looking for any missing icons, then update the FA tags as needed. 
[Here is a list](https://fontawesome.com/how-to-use/on-the-web/setup/upgrading-from-version-4#name-changes) of all icons/aliases and any changes in FA5.

I'm not sure we could really make using FA 5 Pro any easier on the UserFrosting side. The user must decide between global/per-project setup and then add their authentication token.. See https://fontawesome.com/how-to-use/on-the-web/setup/using-package-managers

**Comment by lcharette** [comment]
> It may be more appropriate for FA Pro to be added in a Sprinkle.

If we can't have a config for it, I guess so. 

Can we load with NPM both free and pro version, or does loading both will produce errors?

**Comment by amosfolz** [comment]
> 
> 
> > It may be more appropriate for FA Pro to be added in a Sprinkle.
> 
> If we can't have a config for it, I guess so.
> 
> Can we load with NPM both free and pro version, or does loading both will produce errors?

You need to add special NPM registry entry with authentication key
 ```
npm config set "@fortawesome:registry" https://npm.fontawesome.com/ && \
npm config set "//npm.fontawesome.com/:_authToken" TOKEN
```

**Comment by amosfolz** [comment]
I have not really looked into the bakery much myself. If we could use a special bakery command that asked for the authentication key and then ran those two commands, I guess that might be an option.

**Comment by lcharette** [comment]
More the interaction between those two : 
``` 
npm install --save-dev @fortawesome/fontawesome-free
npm install --save-dev @fortawesome/fontawesome-pro
```

Afterward, we can have a `iconset` bundle that can be easily overwritten. 

I do have a pro license if you need someone to test a custom sprinkle ;)

**Comment by amosfolz** [comment]
Where would be the best place to store the config setting for this? `.env` or a `config` file?

**Comment by amosfolz** [comment]
> Afterward, we can have a `iconset` bundle that can be easily overwritten.


I'm not exactly sure how this would look. 
Is there something similar I can use as a reference?

**Comment by lcharette** [comment]
All password or secrets should be in `.env`.

> I'm not exactly sure how this would look.
> Is there something similar I can use as a reference?

Those bundle : https://github.com/userfrosting/UserFrosting/blob/master/app/sprinkles/core/asset-bundles.json#L67-L78

**Comment by amosfolz** [comment]
I started working on a bakery command. [Here's what I have so far ](https://github.com/amosfolz/UserFrosting/commit/41f0e3cf8b2fe49410ec6b16abde77179c8ececb)
