### ISSUE TITLE
Proxy pass https -> http

### ISSUE THREAD

**Issue by crisciunas** [userfrosting/UserFrosting#871]
I have installed UserFrosting on my Server Nr.2 (NGINX HTTP 80), all incoming connections are via Server Nr.1 (NGINX HTTPS 443 with Let's Encrypt certificate). Server Nr.1 does proxy_pass http://server_2

Mixed Content: The page at xxx was loaded over HTTPS, but requested an insecure script 'http://assets-raw/core/assets/vendor/bootstrap/dist/js/bootstrap.js'. This request has been blocked; 

is there any way to change the response so that it is https://domain_name/ ?

**Comment by alexweissman** [comment]
General troubleshooting/installation questions should be posted to the [forums](https://forums.userfrosting.com) or discussed in [chat](https://chat.userfrosting.com) first.
