### ISSUE TITLE
The asset 'vendor/font-awesome/css/font-awesome.css' could not be found

### ISSUE THREAD

**Issue by pnenov** [userfrosting/UserFrosting#880]
An exception has been thrown during the rendering of a template ("The asset 'vendor/font-awesome/css/font-awesome.css' could not be found. Referenced in '/opt/sites/dev-tool-plamen.transport.int.bell.ca/UserFrosting/app/sprinkles/core/asset-bundles.json [css/main]'.").

**Comment by alexweissman** [comment]
Sounds like asset installation did not complete successfully (either Gulp didn't install, or there was a problem with Bower). Since this is a support question, you should direct it to the [forums](https://forums.userfrosting.com) or [chat](https://chat.userfrosting.com) instead.

**Comment by pnenov** [comment]
or i just could use another software which is less buggy

i am sick and tired of the arrogance of megagigs like yourself who are not
capable to put 2 line of code together

**Comment by lcharette** [comment]
@pnenov This issue is the most common **installation issue** people encounter with UserFrosting. It's not something wrong with our two line of code, but something wrong with people not reading the installation doc.

Nevertheless, feel free to seek out other software and let us know if you find anything you like, we always try to improve our stuff ;)

**Comment by alexweissman** [comment]
LOL @pnenov, thus says the person who has exactly zero activity on GitHub. Go back to Code Canyon, I'm sure you'll find lots of friends who don't contribute to open source and still haven't figured out that the `mysql_` library is deprecated.

I hope no one hires you, ever.

**Comment by jannik-kramer** [comment]
Just leaving this here in case someone has this issue just like i did:
Rerunning `docker-compose run node npm install` after the first `docker-compose up` (which kinda failed due to gulp not being present) did the trick.
