### ISSUE TITLE
Email is case-sensitive

### ISSUE THREAD

**Issue by x00x70** [userfrosting/UserFrosting#881]
Currently it is possible to create to user accounts with the same email address, as long as the email addresses have different cases.  For example, a user can register with "bob@example.com" and another user can register with "BOB@example.com" and this is allowed by the userfrosting application.  I have tested this with PostgreSQL - but I assume this will be the case with all databases as `bob@hotmail.com` != `BOB@hotmail.com` for database string uniqueness.

I suggest the email address is either converted to lowercase at user input points, e.g. registration, the login form, password reset etc. and the email is converted to lowercase when storing in the database.

I originally found this to be an issue, when a user signed up, using an email with the first letter capitalized, however they then could not login with their lowercase email.

**Comment by alexweissman** [comment]
> I assume this will be the case with all databases as bob@hotmail.com != BOB@hotmail.com for database string uniqueness

I tested this with my local MariaDB installation, and it correctly gave me the "email address already in use" when I used variances of an email address with different capitalizations. So, I believe this is [an issue specific to Postgres](https://stackoverflow.com/questions/7005302/postgresql-how-to-make-case-insensitive-query).

I don't like the solution of normalizing the user's email address to be all lowercase. Users might have a specific way of expressing their email address that makes sense to them (recall the whole expertsexchange vs ExpertsExchange confusion) that we should try to preserve.

Clearly though, we need some solution if Postgres behaves this way.

**Comment by x00x70** [comment]
Related to this : https://github.com/laravel/framework/issues/9430

**Comment by JohnSlaughter** [comment]
They need to be made lowercase.  Either in the DB or in PHP, but email addresses should lNEVER be case sensitive.  (Passwords, yes, but never email.)

The same applied to domains.  GoDaddy.com still goes to godaddy.com because we should be smart enough to know they are identical.  Email addresses should be too.

**Comment by sinfuljosh** [comment]
Regarding the php method, if that route was used then there would be no changes on the scheme or in the model.
You would need to apply php’s strtolower function to both the value pulled from the database, and the value submitted by the user prior to comparing.

Once validated the the actual value existing in the database would be used when getting the users email.

The only issue I see here is that strtolower by itself does not handle multi byte characters, any character like those that include accents would be passed through with whichever case they were submitted as.

There is an mb_strtolower that accounts for that , but from reading it appears to be a big performance impact.

http://php.net/manual/en/function.strtolower.php

**Comment by Silic0nS0ldier** [comment]
Plenty of systems out there that process unicode inconsistently, so I think its best to not put the normalisation onto the database for this. It is also worth looking into how email services (or web browsers) see unicode as any normalisation made could potentially produce a different email address.

**Comment by amosfolz** [comment]
It seems the consensus is to use PHP to accomplish this. Is there an existing class it would make sense to add a method to?

Right now [`findUnique`](http://api.userfrosting.com/class-UserFrosting.Sprinkle.Core.Database.Models.Model.html#_findUnique) is used to check if a username or email already exists. 

As we need to do the same thing to both the data submission from user and the database records, would it be better to use two methods or try to combine everything into one? 

Maybe a `findUniqueCaseInsensitive` method inside the `Model` class, and then another method somewhere else for the form submission? (or possibly a transformation)?

**Comment by x00x70** [comment]
given that this has so far just been a postgres issue - we could just put in a DB fix for postgres setup's using the CITEXT field.  https://bambielli.com/til/2016-12-28-postgres-extensions-citext/ 

I don't think this would be an optimal solution, but it would at least give consistent behaviour between postgres and mariaDB....

**Comment by lcharette** [comment]
Done in PR #1012
