### ISSUE TITLE
Dissonant verb form in es_ES

### ISSUE THREAD

**Issue by silvioq** [userfrosting/UserFrosting#890]
Hi.

I detected some language dissonances in Spanish, specifically in verb person

An example:
`"No pudimos encontrar la página que buscabas."` https://github.com/userfrosting/UserFrosting/blob/4dda14f611b6de5764e05d22538f5c179b0a18f7/app/sprinkles/core/locale/es_ES/errors.php#L27

In this case the message uses the second person of the singular form in simple mode ("tú buscabas" or "vos buscabas")

but

`"De cualquier manera, haga clic en <a href="{{url}}"> aquí </a> para volver a la página principal." `
https://github.com/userfrosting/UserFrosting/blob/4dda14f611b6de5764e05d22538f5c179b0a18f7/app/sprinkles/core/locale/es_ES/errors.php#L28

Uses the same person for imperative, but in courtesy mode ("usted haga")

I suppose the normal language of UF is colloquial, then, I think is necessary change courtesy mode ("usted") by normal mode ("tú" or "vos"). In this case, the imperative must be

"De cualquier manera, **haz** clic en ..." ("tú" in es_*)

or 

"De cualquier manera, **hacé** clic en...."` ("vos" only in es_AR)

Thanks

**Comment by lcharette** [comment]
As you might guess, we are not fluent in Spanish. Any improvement in the translations you think of can be submitted in a Pull Request. We'll be happy to take a quick look and merge it for future releases,
