### ISSUE TITLE
Add preview feature to Mailer

### ISSUE THREAD

**Issue by alexweissman** [userfrosting/UserFrosting#891]
It would be extremely useful to have a `preview` method in `Mailer` that renders a message as an HTML page response instead of actually sending the email. This could be useful in development (see #776), or even in a production environment where you have a mail-building tool and want to preview a message before it is actually sent.

**Comment by lcharette** [comment]
https://laravel.com/docs/5.6/mail#previewing-mailables-in-the-browser

**Comment by lcharette** [comment]
This might also be useful for testing : https://laravel.com/docs/5.8/mail#mail-and-local-development

**Comment by lcharette** [comment]
UF5 doc now recommend using Mailpit or Mailtrap to solve this issue
