### ISSUE TITLE
All Config from <config>.php should be exposed to Twig Templates using a new config function

### ISSUE THREAD

**Issue by slcraft** [userfrosting/UserFrosting#895]
Currently, only elements under "site" are accessible from Twig.  Please allow all config elements to be accessible from Twig (in my case, I need access to "address_book".)

**Comment by lcharette** [comment]
I like Alex idea from the chat ;
> there is a good chance that we should just deprecate the `site` global variable and introduce a `config(...)` global helper instead in UF 4.2

**Comment by lcharette** [comment]
Done in https://github.com/userfrosting/sprinkle-core/commit/91c2452dd32c89bea5a98b49a462a20afce8442b for 5.1 release.
