### ISSUE TITLE
A "forUser" method could be defined into the "RoleSprunje" to simplify and better code understanding

### ISSUE THREAD

**Issue by EdwinRiveraF** [userfrosting/UserFrosting#896]
I was exploring a bit the Controllers that come with UserFrosting to have a better understanding of how the User/Roles/Groups relation is established and while reading the code I bumped into a small wall.

The example I discussed in chat was the following: At some point I wanted to know about how the `UserController` got to find Roles associated with a specific user. I couldn't find any additional reference to `forUser` within the rest of UF code.

While exchanging some lines in chat @alexweissman found out that there was no `RoleSprunje::forUser` method.

It turns out that `forUser` is actually extending the base query in `RoleSprunje`, which is creating a new query based on the `Role` model 
```
    protected function baseQuery()
    {
        return $this->classMapper->createInstance('role')->newQuery();
    }
```
and the `Role` model has `scopeForUser`, which Laravel exposes as the `forUser` method.
```
    public function scopeForUser($query, $userId)
    {
        return $query->join('role_users', function ($join) use ($userId) {
            $join->on('role_users.role_id', 'roles.id')
                 ->where('user_id', $userId);
        });
    }
```
So far as we talked it seems that this can be simplified by defining a `forUser` method in the `RoleSprunje` or something similar.

This also seems to be the same case for the `RoleController` which in its case uses the method `forRole` and I guess it follows the same logic since a `scopeForRole` also exists in the `User` Model.

@alexweissman was actually the one to figure this out, I just wrote above what we actually discussed in chat.

**Comment by amosfolz** [comment]
I am failing to understand how this change would be beneficial. Currently it is using a Local Scope, which seems like it is intended to be used in exactly this type of situation. From the Laravel documentation:

_Local scopes allow you to define common sets of constraints that you may easily re-use throughout your application. For example, you may need to frequently retrieve all users that are considered "popular". To define a scope, simply prefix an Eloquent model method with scope._
