### ISSUE TITLE
Please add my website to the 'Built with Userfrosting'

### ISSUE THREAD

**Issue by SamIvory1** [userfrosting/UserFrosting#906]
Feature Request.

Could my website https://www.quotecalculator.co be added tot the list of websites in the 'Build with UserFrosting' section of the home page?
Could the like please also use the following URL: https://www.quotecalculator.co/?utm_source=userfrosting

I have attached a screenshot that could be used.
![screen shot 2018-10-17 at 7 37 26 am](https://user-images.githubusercontent.com/7372640/47067048-f26de280-d1df-11e8-907f-3662a0c324ec.png)

Thanks!

**Comment by lcharette** [comment]
Hey @SarahBaghdadi, can you take care of this? :)

**Comment by SarahBaghdadi** [comment]
Yup. I'll add it to my to do list.

**Comment by amosfolz** [comment]
Just browsing through issues and noticed the links from OP are not valid anymore. @SamIvory1 is this still a project you are working on? If not, this can probably be closed.

**Comment by SamIvory1** [comment]
Hi,

This has now been shut down and so can be removed.
________________________________
