### ISSUE TITLE
Ignore untestable files in code coverage

### ISSUE THREAD

**Issue by Silic0nS0ldier** [userfrosting/UserFrosting#924]
As part of the <kbd>4.2.0-beta.1</kbd> release codecov.io was enabled, however currently the shown coverage is misleading. Many files (like `routes.php` and `index.php`) are simply untestable and having them included in report generation is ultimately doing more harm then good (looks bad to people considering the framework and its harder to identify where coverage needs to improve).

We need to add a `codecov.yml` (if not there already) and define ignore globs as per https://docs.codecov.io/docs/ignoring-paths.

**Comment by hpez** [comment]
I wanna take this one. Anything I should consider?

**Comment by lcharette** [comment]
I was looking at this for my own Sprinkle and I too realized it should be applied to UF as well. Only `/src` for each core sprinkle + system should be included in the report. 

I think a filter in `phpunit.xml` could be used for this, as I used this before for the [FormGenerator Sprinkle](https://github.com/lcharette/UF_FormGenerator/blob/master/phpunit.xml#L17-L21).

**Comment by lcharette** [comment]
@hpez If you have experience with unitTesting, our main objective right now is increasing test coverage. So any new tests are welcomed in a PR !

**Comment by Silic0nS0ldier** [comment]
@hpez Work of the develop branch, only ignore files that need to be ignored (https://codecov.io/gh/userfrosting/UserFrosting/branch/develop should help regarding this, files like tests are already ignored), and try to use glob rules where you can to keep things concise and maintainable.. And as @lcharette says, if you've got experience in unit testing feel free to make additions.

**Comment by lcharette** [comment]
Went from 23.7% to 35.6%. That's a start.
