### ISSUE TITLE
Differentiate non-existent group from group deletion redirect

### ISSUE THREAD

**Issue by Silic0nS0ldier** [userfrosting/UserFrosting#932]
And discussed in https://github.com/userfrosting/UserFrosting/pull/929 we should be handling deletion of groups better. The current solution (redirect on not found) is incorrect use of HTTP response codes, will give people trying to build an app grief, and adds an unnecessary extra request.

**Comment by Silic0nS0ldier** [comment]
Probably a good idea to see this fixed in 4.2 given the current solution is an unnecessary breaking change.

**Comment by UrsBoller** [comment]
I made some testing and I think the following solution might work without breaking the current implementations:

1. add new form attribute 'onSuccess' to controller where needed (only where the page should not reload but do a redirect on success), eg. when ['getModalConfirmDelete'](https://github.com/userfrosting/UserFrosting/blob/master/app/sprinkles/admin/src/Controller/GroupController.php#L314) 
`'onSuccess' => '/groups'`
2. add new atribute to the form (as ['attribute in the form tag'](https://github.com/userfrosting/UserFrosting/blob/master/app/sprinkles/admin/templates/forms/group.html.twig#L1))
`successuri="{{site.uri.public}}/{{form.onSuccess}}"`
3. [onSuccess of modal](https://github.com/userfrosting/UserFrosting/blob/master/app/sprinkles/admin/assets/userfrosting/js/widgets/groups.js#L49) check if new attribute exists and redirect accordingly (fallback is old behavior)
`if('undefined' !== typeof form.attr('successuri') && form.attr('successuri')) {
    window.location = form.attr('successuri');
} else {
window.location.reload();
}`

**Comment by Silic0nS0ldier** [comment]
Looked into it and there is already a callback (the one already used) which can receive API response data. Threw together a local prototype, and so far looking good.

I'll look into the other pages that new redirect, could be other cases where this can be applied.

**Comment by Silic0nS0ldier** [comment]
Wait... I see now why it just refreshes the page. The JS is a reused widget. Properly solving this just got trickier.

**Comment by UrsBoller** [comment]
thats what I mean. Having this "widget" which is used all over the pages doesn't allow any "single behavior". My prefered solution would be to have an option when "calling the modal" and not somewhere on "validation". this would allow to call the modal from anywhere and add behavior "onSuccess".

**Comment by lcharette** [comment]
If it can help, I used this in a private repo, which also uses FormGenerator : 

```
            $("#widget-decomptes > .box-body").find(".js-displayConfirm").formGenerator('confirm', {
                redirectAfterSuccess: false,
                successCallback: function() { $("#widget-decomptes").ufTable('refresh'); }
            });
```

You can look here for inspiration : https://github.com/lcharette/UF_FormGenerator/blob/master/assets/js/widget-formGenerator.js#L242

**Comment by Silic0nS0ldier** [comment]
Given that the widget essentially is a clean slate as it is (aside from having the id of what is to be removed), I'm thinking the solution should go something like.

1. Button event code invokes widget, but passes along if it wants to redirect on completion
2. Widget updated to respect intent of caller (redirect if asked, otherwise use logic from UF 4.1).
3. Controller method that _should_ 404 instead of redirecting, is updated to 404 as expected.

Just so I don't forget, this change will need to be reflected on _all_ entities that can be deleted.

**Comment by Silic0nS0ldier** [comment]
This is now implemented on `develop`.

Solution was to have controller methods 404 (as they should do), have multipage scripts support and extra optional options object (which contains the redirect path), have page specific scripts pass in the configuration, and pages that would need to redirect hold the value to redirect to.
