### ISSUE TITLE
Caching of unchanged developmental assets

### ISSUE THREAD

**Issue by Silic0nS0ldier** [userfrosting/UserFrosting#938]
Currently while in dev mode (and I believe some others) we disable caching of assets to ensure that the newest data always arrives. This however can increase load times substantially during development, during which few files are changed at once.

What we can do here is enable caching and add `?YYYY.MM.DD-HH:mm` or similiar to the end of the resource URL which is based on the files last modification date. This will be enough to serve as a cache buster, and is already widely used for cache busting purposes.

Given how the system is implemented in <kbd>4.2</kbd> it shouldn't be too difficult to implement with changes only needing to be made in `UserFrosting\Assets`, which houses the developmental asset server and tag generator. Once published, the feature would just "light up" once people run `composer update`.

In the past (and perhaps still) the barrage of asset requests caused session management to bug out somewhat, particularly around alerts. Implementing this would mitigate this problem, and any others that are caused by the same phenomenon. Race conditions are still something to bare in mind however.

**Comment by lcharette** [comment]
Closing, as it's not relevant anymore with UF5
