### ISSUE TITLE
Return a more helpful error for missing CSS assets

### ISSUE THREAD

**Issue by lcharette** [userfrosting/UserFrosting#945]
Since this error is the most common one new comers encounter : 

``` 
An exception has been thrown during the rendering of a template ("The asset 'vendor/font-awesome/css/font-awesome.css' could not be found. Referenced in '/home/vagrant/userfrosting/app/sprinkles/core/asset-bundles.json [css/main]'.").
```

We should probably display a fancy error when this is detected. Maybe something we should add to the ` CheckEnvrionement`  page, and force it to display in any env mode, not only production.

Related : 
 - https://github.com/userfrosting/learn/issues/65
 - #630

**Comment by Silic0nS0ldier** [comment]
Its a no from me regarding showing an information error on production. Beyond the user not being shown redundant info, you don't want to risk exposing internal data.

That said, we can certainly improve the debugging experience, even in production environments. I recommend pointing the way somehow to where the error would be logged. And then in the logs, have the more helpful error for missing resources.

**Comment by lcharette** [comment]
Yeah... production might not be a good idea after all. I guess this could be easily solved by keeping the exception, but detailing the exception message more :  

> An exception has been thrown during the rendering of a template ("The asset 'vendor/font-awesome/css/font-awesome.css' could not be found. Referenced in '/home/vagrant/userfrosting/app/sprinkles/core/asset-bundles.json [css/main]'."). Missing fronted dependencies can be solved by running `php bakery build-assets` again.

Not sure talking about Bakery is wise, but again this message is only displayed in non-production mode & in the log when production is enabled.

**Comment by amosfolz** [comment]
So would we want to add this into `Assets` at [this line](https://github.com/userfrosting/assets/blob/d97ac83733a7c9551e9ee17b71c473ff03d5e866/src/Assets.php#L178)?

Here is the error just for reference:
![image](https://user-images.githubusercontent.com/33728190/60775432-2207a680-a0f1-11e9-8600-fa4e26062a62.png)


Looks like `FileNotFoundException` is passed to Twig `RuntimeError`, and we probably do not want to change that?

**Comment by lcharette** [comment]
Closing, as it's not relevant anymore with UF5
