### ISSUE TITLE
Userfrosting did not detect nodejs? ?

### ISSUE THREAD

**Issue by zhangchenglin** [userfrosting/UserFrosting#971]
![QQ截图20190427110804](https://user-images.githubusercontent.com/30773389/56844337-669ce780-68e1-11e9-8171-c06014b7b0ef.png)

Why is my nodejs installed on my centos7, but Userfrosting is not detected? The subsequent NPM could not be implemented.

**Comment by zhangchenglin** [comment]
Subsequent NPM cannot be automatically implemented by Userfrosting

**Comment by lcharette** [comment]
See docs : https://learn.userfrosting.com/installation/other-situations/centos#node-js

**Comment by lcharette** [comment]
General troubleshooting/installation questions should be posted to the [forums](https://forums.userfrosting.com) or discussed in [chat](https://chat.userfrosting.com) first. If there's a real issue, this could be reopened.

**Comment by zhangchenglin** [comment]
https://forums.userfrosting.com/t/userfrosting-did-not-detect-nodejs/528/23

No intention to offend, but it has been a long time, I did not think of a better way to try.

**Comment by zhangchenglin** [comment]
@lcharette
