### ISSUE TITLE
select2 don't close in edit form.

### ISSUE THREAD

**Issue by silvioq** [userfrosting/UserFrosting#972]
After a clean UF 4.2.1 installation, there are a rare behavior with select2 combos. They don't closes in a blur or click events.

![Captura de pantalla de 2019-04-30 20-51-53](https://user-images.githubusercontent.com/155036/57000478-45aaef80-6b8a-11e9-8e87-6beaaa1f774f.png)

For reproduce it, simply create a new installation with docker. I running "php bakery build-assets" in a nodejs container, because the docker recipe does not install assets.

**Comment by lcharette** [comment]
This is an issue with the latest Select2 version, which need to be fixed on their side, not our. See  
- https://github.com/select2/select2/issues/5490 
- https://chat.userfrosting.com/channel/select2?msg=jeTGNfMRAt5Yvn2YP
