### ISSUE TITLE
Native Installation. Userfrosting did not detect nodejs??

### ISSUE THREAD

**Issue by zhangchenglin** [userfrosting/UserFrosting#975]
[Userfrosting did not detect nodejs??](https://forums.userfrosting.com/t/userfrosting-did-not-detect-nodejs/528)

OS: centos 7.6 64
CentOS Linux release 7.6.1810 (**Core**)
3.10.0-957.12.1.el7.x86_64
64

Build lnmp (Linux + Nginx+ MySQL+ PHP) with [OneinStack](https://oneinstack.com/)

I refer to https://learn.userfrosting.com/installation/other-situations/centos#node-js
Nodejs installed
Nodejs integrates with NPM
Why am I stopping at the steps above? ?

**Comment by lcharette** [comment]
As noted [here](https://forums.userfrosting.com/t/userfrosting-did-not-detect-nodejs/528/33) and [here](https://github.com/userfrosting/UserFrosting/issues/971), I could not not replicate this issue on CentOS 7... 

> So it's definitively an issue on your side, not UF one. Check again for permissions issue, or PHP (CLI) config. Might have a setting in your PHP that messes with the `exec` function, as your issue is strictly related to this core PHP function.

As this is not an issue with UF (as long as a code change is not required to fix this), this issue will be closed, but you're welcome to discuss it on the forum and chat.

**Comment by andhub-cn** [comment]
张成林，请问您的问题是否解决了 我遇到了和您一样的问题

**Comment by zhangchenglin** [comment]
@andhub-cnhttps://forums.userfrosting.com/t/userfrosting-did-not-detect-nodejs-solved/5282019年5月13日 22:42，andhub-cn <notifications@github.com>写道：张成林，请问您的问题是否解决了 我遇到了和您一样的问题

**Comment by zhangchenglin** [comment]
@andhub-cn
https://forums.userfrosting.com/t/userfrosting-did-not-detect-nodejs-solved/528
