### ISSUE TITLE
Package phpunit/phpunit-mock-objects is abandoned, you should avoid using it. No replacement was suggested.

### ISSUE THREAD

**Issue by andhub-cn** [userfrosting/UserFrosting#977]
Package phpunit/phpunit-mock-objects is abandoned, you should avoid using it. No replacement was suggested.

**Comment by lcharette** [comment]
This warning can be ignored for now.

I'll still tag it for 4.3.0, as updating phpunit will probably solve this (not a direct dependency of UF), just in case. Not sure if it impact our tests, as we usually use Mockery

**Comment by lcharette** [comment]
I can confirm this will be automatically solved when #779 is solved.
