### ISSUE TITLE
After the local installation is completed, the access prompt is as follows:

### ISSUE THREAD

**Issue by andhub-cn** [userfrosting/UserFrosting#979]
Twig\Error\RuntimeError thrown with message "An exception has been thrown during the rendering of a template ("No file could be resolved for the stream path 'assets://vendor/font-awesome/css/font-awesome.css'.")."

**Comment by amosfolz** [comment]
This is a common issue and you can see there is a note under ["common problems" on the website](https://learn.userfrosting.com/troubleshooting/common-problems#when-trying-to-view-my-site-i-get-an-error-like-an-exception-has-been-thrown-during-the-rendering-of-a-template-the-asset-vendor-font-awesome-css-font-awesome-css-could-not-be-found-referenced-in-home-vagrant-userfrosting-app-sprinkles-core-asset-bundles-json-css-main-)

Please ask for help in [chat](https://chat.userfrosting.com/) as this is likely an user installation error, not something wrong with UF.
