### ISSUE TITLE
When internationalizing, the lang attribute value of the Twig template is not set to follow changes.

### ISSUE THREAD

**Issue by zhangchenglin** [userfrosting/UserFrosting#982]
https://github.com/userfrosting/UserFrosting/blob/07d90351230727a4dbb95d783c1fe8f3e6aca70b/app/sprinkles/core/templates/pages/abstract/base.html.twig#L5

Please excuse me.I won't provide the corresponding code PR for Twig, so I only ask questions and hope that UserFrosting will get better.

**Comment by lcharette** [comment]
This tag  `<html lang="en-US">` ?

**Comment by zhangchenglin** [comment]
> This tag `<html lang="en-US">` ?

Yes!

**Comment by lcharette** [comment]
Done in https://github.com/userfrosting/UserFrosting/commit/0ba8ab4ce6bca724b07d118c90e3692cbf465520 for UF 4.4
