### ISSUE TITLE
Certain classes of assets broken by sourcemaps

### ISSUE THREAD

**Issue by Silic0nS0ldier** [userfrosting/UserFrosting#985]
There has been a report of sourcemap comment annotations appearing in some non-css/js files such as fonts (`.woff`) and svg images (`.svg`) for production builds. Annotation appears like `//# sourceMappingURL=fontawesome-webfont.woff.map`.

This shouldn't be happening, and needs to investigated and have reproduction steps documented..

**Comment by splitt3r** [comment]
Thanks for creating the issue 👍

**Comment by Silic0nS0ldier** [comment]
I'm currently performing a major refactor of the bundling logic, as part of this I'll revise the build logic to ensure sourcemaps aren't affecting assets other than CSS and JS.

**Comment by Silic0nS0ldier** [comment]
Update: Asset pipeline overhaul is very close to completion and includes a fix for this issue.

**Comment by Silic0nS0ldier** [comment]
This has been released.
