### ISSUE TITLE
Translation fields are not synchronized to other language files, such as Chinese.

### ISSUE THREAD

**Issue by zhangchenglin** [userfrosting/UserFrosting#989]
https://github.com/userfrosting/UserFrosting/blob/fb1b72148d23654315f849d7188fab306211b227/app/sprinkles/account/locale/en_US/messages.php#L162

`https://xxx.com/userfrosting/public/account/register
`
The above is an example address, and no other comparisons have been made. If it is automated, please update it in time.

**Comment by lcharette** [comment]
There could be some locale that are missing keys or are out of sync with English. If you can submit a Pull Request with the missing translation, that would be great.

Related #671

**Comment by zhangchenglin** [comment]
> There could be some locale that are missing keys or are out of sync with English. If you can submit a Pull Request with the missing translation, that would be great.
> 
> Related #671


https://github.com/rasmusbe/wp-pot
https://github.com/rasmusbe/gulp-wp-pot


There is this tool under WordPress that can help theme or plugin developers to quickly and accurately generate corresponding po translation files based on php files. Perhaps the author of this tool has the ability to help UF to do a similar tool if he can generate interest. 

Now, even the most basic en_US does not contain all the fields that need to be translated, because there is no need to translate in the English state, but it is cumbersome and incomplete for those who want to translate other languages ​​according to the en_US file. .

**Comment by lcharette** [comment]
Looks like the screenshot also catch block that moved around (not in the same order). Usually, it's best to have entries in the translation files sorted alphabetically. 

A simple tool for #671 could be getting a list of all keys (ie `HASH_FAILED` ) available in EN_US and comparing if the same key exist in another language (and is the same translated value), returning a list of keys that are missing from the targeted translation.

**Comment by zhangchenglin** [comment]
https://github.com/umpirsky/Twig-Gettext-Extractor

This looks like a good tool.

**Comment by amosfolz** [comment]
@zhangchenglin I have a open PR https://github.com/userfrosting/UserFrosting/pull/1005 that should have all the missing keys generated. Can you help translate?

**Comment by amosfolz** [comment]
@zhangchenglin Can you help with translating? #1027

**Comment by lcharette** [comment]
Closing this issue. Let's focus on #1027
