### ISSUE TITLE
Update to latest AdminLTE

### ISSUE THREAD

**Issue by lcharette** [userfrosting/UserFrosting#994]
> I had a quick look and even between 2.3.6 (which comes with UF4) and 2.4.10 there are quite a number of changes. There's something like 3 years between these releases which in our world is/feels like ages

**Comment by amosfolz** [comment]
Newest release is now `2.4.12`

I believe the files that need to be updated are:

- [ ] - `core/assets/userfrosting/js/AdminLTE.js`
- [ ] - `core/assets/userfrosting/js/AdminLTE-custom.js`
- [ ] - `core/assets/userfrosting/css/AdminLTE.css`
- [ ] - `core/assets/userfrosting/css/AdminLTE-skins-all.css`

**Comment by amosfolz** [comment]
@lcharette do you remember what specifically [these lines](https://github.com/userfrosting/UserFrosting/blob/master/app/sprinkles/core/assets/userfrosting/js/AdminLTE-custom.js#L17-L71) were meant to fix?

**Comment by lcharette** [comment]
FYI : https://github.com/ColorlibHQ/AdminLTE/releases/tag/v2.4.13

**Comment by lcharette** [comment]
When upgrading to AdminLTE 3 later on, we should probably try using their NPM repo.

**Comment by lcharette** [comment]
FYI : https://github.com/ColorlibHQ/AdminLTE/releases/tag/v2.4.14

(They're playing with you :P )

**Comment by amosfolz** [comment]
Okay, updated to `2.4.14`! Only a few lines of code changed.

**Comment by amosfolz** [comment]
> 
> 
> When upgrading to AdminLTE 3 later on, we should probably try using their NPM repo.

I'm not sure if it will be the same using their NPM repo or not, but the package is pretty large when downloading the ZIP file.
![image](https://user-images.githubusercontent.com/33728190/61316642-6b31b780-a7cf-11e9-9116-4ead0e012c9f.png)
