### ISSUE TITLE
Can't put README.md files in Database Migration path

### ISSUE THREAD

**Issue by xrobau** [userfrosting/UserFrosting#995]
When adding a README.md to a sprinkle's Database/Migration directory, it is treated like a .php file.

My suggestion would be to add a check in `app/sprinkles/core/src/Database/Migrator/MigrationLocator.php` to make sure the file ends with .php, but maybe you want to mess with the locator (which I didn't trace further back).

Suggested patch:

```
        foreach ($migrationFiles as $migrationFile) {
            if (preg_match('/php$/', $migrationFile)) {
                $migrations[] = $this->getMigrationDetails($migrationFile);
            }
        }
````
The error is:

```
root@6a08ab995299:/var/www# php bakery migrate

UserFrosting's Migrator
=======================
 [ERROR] Unable to find the migration class '\UserFrosting\Sprinkle\Zoho\Database\Migrations\README'.

root@6a08ab995299:/var/www#
```

**Comment by lcharette** [comment]
Duplicate #965.
