### ISSUE TITLE
bug - Twig \ Error \ RuntimeError

### ISSUE THREAD

**Issue by asixtioso** [userfrosting/UserFrosting#997]
Twig \ Error \ RuntimeError

An exception has been thrown during the rendering of a template ("No file could be resolved for the stream path 'assets://vendor/font-awesome/css/font-awesome.css'.").
Previous exceptions
No file could be resolved for the stream path 'assets://vendor/font-awesome/css/font-awesome.css'. (0)

----
C:\xampp\htdocs\uf42\app\vendor\userfrosting\assets\src\AssetsTemplatePlugin.php
 
        foreach ($assetPaths as $assetPath) {
            $assetsTagged .= $this->makeRegularTag('script', array_merge(['src' => $assetPath], $attributes));
        }
 
        return $assetsTagged;
    }
 
    /**
     * Returns HTML ready tags for all assets in the requested CSS bundle.
     *
     * @param  string $bundleName Bundle name.
     * @param  array  $attributes Attributes generated tags should include.
     * @return string
     */
    public function css($bundleName = 'css/main', $attributes = [])
    {
        $attributes = array_merge(['rel' => 'stylesheet', 'type' => 'text/css'], $attributes);
 
        $assetPaths = $this->assets->getCssBundleAssets($bundleName);
        $assetsTagged = '';
 
        foreach ($assetPaths as $assetPath) {
            $assetsTagged .= $this->makeSelfClosingTag('link', true, array_merge(['href' => $assetPath], $attributes));
        }
 
        return $assetsTagged;
    }
 
    /**
     * Returns URL to asset specified by stream.
     *
     * @param string|string[] $streamPath A valid stream. EG: 'assets://path.to' or ['assets', 'path.to']
     */
    public function url($streamPath)
    {
        return $this->assets->getAbsoluteUrl($streamPath);
    }
 
    /**

**Comment by lcharette** [comment]
▶️ [When trying to view my site I get an error like "An exception has been thrown during the rendering of a template](https://learn.userfrosting.com/troubleshooting/common-problems#when-trying-to-view-my-site-i-get-an-error-like-an-exception-has-been-thrown-during-the-rendering-of-a-template-the-asset-vendor-font-awesome-css-font-awesome-css-could-not-be-found-referenced-in-home-vagrant-userfrosting-app-sprinkles-core-asset-bundles-json-css-main-)

General troubleshooting/installation questions should be posted to the [forums](https://forums.userfrosting.com) or discussed in [chat](https://chat.userfrosting.com) first.
